// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_push.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpsertAnnotations = `-- name: BulkUpsertAnnotations :many
INSERT INTO annotations (
    content_hash, owner_id, target_kind, session_id,
    entry_session_id, entry_index, entry_end_index,
    annotation_id, project_hash, target_association_id, type_id, value,
    is_primary, confidence, reason, annotator_name, provenance
)
SELECT
    r.content_hash, $1::uuid, r.target_kind, r.session_id,
    r.entry_session_id, r.entry_index, r.entry_end_index,
    r.annotation_id, r.project_hash, r.target_association_id, r.type_id, r.value,
    r.is_primary, r.confidence, r.reason, r.annotator_name, r.provenance
FROM jsonb_to_recordset($2::jsonb) AS r(
    content_hash     text,
    target_kind      text,
    session_id       text,
    entry_session_id text,
    entry_index      integer,
    entry_end_index  integer,
    annotation_id    text,
    project_hash     text,
    target_association_id text,
    type_id          text,
    value            text,
    is_primary       boolean,
    confidence       double precision,
    reason           text,
    annotator_name   text,
    provenance       jsonb
)
ON CONFLICT (owner_id, content_hash) DO UPDATE SET updated_at = now()
RETURNING content_hash, COALESCE(created_at = updated_at, false)::boolean AS created
`

type BulkUpsertAnnotationsParams struct {
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
	Items   []byte      `db:"items" json:"items"`
}

type BulkUpsertAnnotationsRow struct {
	ContentHash string `db:"content_hash" json:"content_hash"`
	Created     bool   `db:"created" json:"created"`
}

// Batched multi-row upsert of pushed annotations in a SINGLE statement
// replaces the per-item UpsertAnnotation loop's N round trips with one. Rows are
// passed as one JSONB array (jsonb_to_recordset, NULL-preserving)
// and all share the scalar owner_id, so the upsert is owner-scoped. ON CONFLICT
// (owner_id, content_hash) bumps updated_at (the existing skip semantics). RETURNING the
// content_hash plus (created_at = updated_at) lets the caller classify each row
// as created (true) vs updated (false) per item — the client manifest skip-gate
// and retraction depend on per-item outcomes.
func (q *Queries) BulkUpsertAnnotations(ctx context.Context, arg BulkUpsertAnnotationsParams) ([]BulkUpsertAnnotationsRow, error) {
	rows, err := q.db.Query(ctx, bulkUpsertAnnotations, arg.OwnerID, arg.Items)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkUpsertAnnotationsRow{}
	for rows.Next() {
		var i BulkUpsertAnnotationsRow
		if err := rows.Scan(&i.ContentHash, &i.Created); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createManualAnnotation = `-- name: CreateManualAnnotation :one
INSERT INTO annotations (
    content_hash, owner_id, target_kind, session_id,
    entry_session_id, entry_index, entry_end_index,
    target_transcript_id, type_id, value, is_primary, reason, annotator_name, annotator_kind
) VALUES (
    $1, $2, 'entry', NULL,
    $3, $4, $5,
    $6, $7, $8, $9, $10, $11, 'human'
)
ON CONFLICT (owner_id, content_hash) DO UPDATE SET updated_at = now()
RETURNING id, content_hash, owner_id, target_kind, session_id, entry_session_id, entry_index, entry_end_index, annotation_id, project_hash, type_id, value, is_primary, confidence, reason, annotator_name, provenance, created_at, updated_at, annotator_kind, target_association_id, target_transcript_id
`

type CreateManualAnnotationParams struct {
	ContentHash        string      `db:"content_hash" json:"content_hash"`
	OwnerID            pgtype.UUID `db:"owner_id" json:"owner_id"`
	EntrySessionID     pgtype.Text `db:"entry_session_id" json:"entry_session_id"`
	EntryIndex         pgtype.Int4 `db:"entry_index" json:"entry_index"`
	EntryEndIndex      pgtype.Int4 `db:"entry_end_index" json:"entry_end_index"`
	TargetTranscriptID pgtype.UUID `db:"target_transcript_id" json:"target_transcript_id"`
	TypeID             string      `db:"type_id" json:"type_id"`
	Value              string      `db:"value" json:"value"`
	IsPrimary          bool        `db:"is_primary" json:"is_primary"`
	Reason             pgtype.Text `db:"reason" json:"reason"`
	AnnotatorName      pgtype.Text `db:"annotator_name" json:"annotator_name"`
}

// Inserts a single entry-level annotation created manually on the village
// (village-only, no propagation). annotator_kind is fixed to 'human'.
// content_hash dedups identical labels: a repeat insert bumps updated_at and
// returns the existing row rather than creating a duplicate.
func (q *Queries) CreateManualAnnotation(ctx context.Context, arg CreateManualAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, createManualAnnotation,
		arg.ContentHash,
		arg.OwnerID,
		arg.EntrySessionID,
		arg.EntryIndex,
		arg.EntryEndIndex,
		arg.TargetTranscriptID,
		arg.TypeID,
		arg.Value,
		arg.IsPrimary,
		arg.Reason,
		arg.AnnotatorName,
	)
	var i Annotation
	err := row.Scan(
		&i.ID,
		&i.ContentHash,
		&i.OwnerID,
		&i.TargetKind,
		&i.SessionID,
		&i.EntrySessionID,
		&i.EntryIndex,
		&i.EntryEndIndex,
		&i.AnnotationID,
		&i.ProjectHash,
		&i.TypeID,
		&i.Value,
		&i.IsPrimary,
		&i.Confidence,
		&i.Reason,
		&i.AnnotatorName,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnnotatorKind,
		&i.TargetAssociationID,
		&i.TargetTranscriptID,
	)
	return i, err
}

const deleteAnnotationByContentHash = `-- name: DeleteAnnotationByContentHash :exec
DELETE FROM annotations
WHERE content_hash = $1 AND owner_id = $2
`

type DeleteAnnotationByContentHashParams struct {
	ContentHash string      `db:"content_hash" json:"content_hash"`
	OwnerID     pgtype.UUID `db:"owner_id" json:"owner_id"`
}

// Hard-deletes the owner-scoped annotation identified by content_hash
// during retraction. Owner-scoped so a caller can never drop another owner's
// copy even on a hash collision across owners. Idempotent: deleting an
// absent (already-gone) hash affects zero rows and is not an error.
func (q *Queries) DeleteAnnotationByContentHash(ctx context.Context, arg DeleteAnnotationByContentHashParams) error {
	_, err := q.db.Exec(ctx, deleteAnnotationByContentHash, arg.ContentHash, arg.OwnerID)
	return err
}

const listAnnotationContentHashesByOwner = `-- name: ListAnnotationContentHashesByOwner :many
SELECT content_hash FROM annotations
WHERE owner_id = $1
ORDER BY content_hash ASC
`

// Returns every annotation content-hash the village currently holds for the
// given owner's server manifest. Index-bounded on
// idx_annotations_owner. Hashes only — no content — so the result is
// privacy-safe. Ordered for a deterministic wire payload.
func (q *Queries) ListAnnotationContentHashesByOwner(ctx context.Context, ownerID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAnnotationContentHashesByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content_hash string
		if err := rows.Scan(&content_hash); err != nil {
			return nil, err
		}
		items = append(items, content_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnnotationsByTranscriptID = `-- name: ListAnnotationsByTranscriptID :many
SELECT a.id, a.content_hash, a.owner_id, a.target_kind, a.session_id, a.entry_session_id, a.entry_index, a.entry_end_index, a.annotation_id, a.project_hash, a.type_id, a.value, a.is_primary, a.confidence, a.reason, a.annotator_name, a.provenance, a.created_at, a.updated_at, a.annotator_kind, a.target_association_id, a.target_transcript_id FROM annotations a
JOIN transcripts t ON t.id = $1
WHERE (a.owner_id = t.owner_id AND (
	       a.session_id = t.local_id
	       OR a.entry_session_id = t.local_id
	   ))
	   OR a.target_transcript_id = t.id
	   OR EXISTS (
       SELECT 1
       FROM transcript_associations ta
       WHERE ta.owner_id = a.owner_id
         AND ta.association_id = a.target_association_id
         AND ta.transcript_id = t.id
   )
ORDER BY a.created_at ASC, a.id ASC
`

// Returns every annotation whose target resolves to the exact transcript UUID,
// ordered oldest first. Village-created manual rows use target_transcript_id;
// pushed local session ids are owner-scoped, so their direct session and entry
// arms join through both the transcript UUID and owner. Association arms use the
// immutable ledger's exact transcript_id.
func (q *Queries) ListAnnotationsByTranscriptID(ctx context.Context, id pgtype.UUID) ([]Annotation, error) {
	rows, err := q.db.Query(ctx, listAnnotationsByTranscriptID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Annotation{}
	for rows.Next() {
		var i Annotation
		if err := rows.Scan(
			&i.ID,
			&i.ContentHash,
			&i.OwnerID,
			&i.TargetKind,
			&i.SessionID,
			&i.EntrySessionID,
			&i.EntryIndex,
			&i.EntryEndIndex,
			&i.AnnotationID,
			&i.ProjectHash,
			&i.TypeID,
			&i.Value,
			&i.IsPrimary,
			&i.Confidence,
			&i.Reason,
			&i.AnnotatorName,
			&i.Provenance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnnotatorKind,
			&i.TargetAssociationID,
			&i.TargetTranscriptID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerAnnotationHashesForTranscriptIDs = `-- name: ListOwnerAnnotationHashesForTranscriptIDs :many
SELECT a.content_hash,
       t.id AS transcript_id
FROM annotations a
JOIN transcripts t ON t.id = ANY($1::uuid[])
WHERE a.owner_id = $2
   AND (
       a.target_transcript_id = t.id
       OR
       (a.owner_id = t.owner_id AND (
          a.session_id = t.local_id
          OR a.entry_session_id = t.local_id
      ))
      OR EXISTS (
          SELECT 1
          FROM transcript_associations ta
          WHERE ta.owner_id = a.owner_id
            AND ta.association_id = a.target_association_id
            AND ta.transcript_id = t.id
      )
  )
`

type ListOwnerAnnotationHashesForTranscriptIDsParams struct {
	TranscriptIds []pgtype.UUID `db:"transcript_ids" json:"transcript_ids"`
	OwnerID       pgtype.UUID   `db:"owner_id" json:"owner_id"`
}

type ListOwnerAnnotationHashesForTranscriptIDsRow struct {
	ContentHash  string      `db:"content_hash" json:"content_hash"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// Pull skip-gate: the requester's OWN annotation content-hashes that link to any
// of the given transcript UUIDs, for the owner-scoped annotationsCurrent compare.
// The UUID is the identity boundary: owner-local session ids are not globally
// unique. Village-created manual rows use target_transcript_id directly; pushed
// session and entry arms additionally require t.owner_id = a.owner_id;
// association arms require the ledger's exact transcript UUID.
// Hashes only, so the result stays privacy-safe.
func (q *Queries) ListOwnerAnnotationHashesForTranscriptIDs(ctx context.Context, arg ListOwnerAnnotationHashesForTranscriptIDsParams) ([]ListOwnerAnnotationHashesForTranscriptIDsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerAnnotationHashesForTranscriptIDs, arg.TranscriptIds, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerAnnotationHashesForTranscriptIDsRow{}
	for rows.Next() {
		var i ListOwnerAnnotationHashesForTranscriptIDsRow
		if err := rows.Scan(&i.ContentHash, &i.TranscriptID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
