// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apikeys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, key_hash, key_prefix, label)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, key_hash, key_prefix, label, created_at, last_used, revoked_at
`

type CreateAPIKeyParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	KeyHash   string      `db:"key_hash" json:"key_hash"`
	KeyPrefix string      `db:"key_prefix" json:"key_prefix"`
	Label     pgtype.Text `db:"label" json:"label"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Label,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsed,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT ak.id, ak.user_id, ak.key_hash, ak.key_prefix, ak.label, ak.created_at, ak.last_used, ak.revoked_at, u.id as uid, u.github_id, u.github_username, u.display_name, u.avatar_url
FROM api_keys ak
JOIN users u ON ak.user_id = u.id
WHERE ak.key_hash = $1 AND ak.revoked_at IS NULL
`

type GetAPIKeyByHashRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	UserID         pgtype.UUID        `db:"user_id" json:"user_id"`
	KeyHash        string             `db:"key_hash" json:"key_hash"`
	KeyPrefix      string             `db:"key_prefix" json:"key_prefix"`
	Label          pgtype.Text        `db:"label" json:"label"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsed       pgtype.Timestamptz `db:"last_used" json:"last_used"`
	RevokedAt      pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	Uid            pgtype.UUID        `db:"uid" json:"uid"`
	GithubID       int64              `db:"github_id" json:"github_id"`
	GithubUsername string             `db:"github_username" json:"github_username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsed,
		&i.RevokedAt,
		&i.Uid,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
	)
	return i, err
}

const listUserAPIKeys = `-- name: ListUserAPIKeys :many
SELECT id, key_prefix, label, created_at, last_used, revoked_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListUserAPIKeysRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	Label     pgtype.Text        `db:"label" json:"label"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsed  pgtype.Timestamptz `db:"last_used" json:"last_used"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

func (q *Queries) ListUserAPIKeys(ctx context.Context, userID pgtype.UUID) ([]ListUserAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listUserAPIKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAPIKeysRow{}
	for rows.Next() {
		var i ListUserAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.KeyPrefix,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsed,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1 AND user_id = $2
`

type RevokeAPIKeyParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.UserID)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
