// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attestations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttestation = `-- name: CreateAttestation :one
INSERT INTO attestations (transcript_id, attester_id, org_login, attestation_type, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, transcript_id, attester_id, org_login, attestation_type, note, created_at
`

type CreateAttestationParams struct {
	TranscriptID    pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	AttesterID      pgtype.UUID `db:"attester_id" json:"attester_id"`
	OrgLogin        string      `db:"org_login" json:"org_login"`
	AttestationType string      `db:"attestation_type" json:"attestation_type"`
	Note            pgtype.Text `db:"note" json:"note"`
}

func (q *Queries) CreateAttestation(ctx context.Context, arg CreateAttestationParams) (Attestation, error) {
	row := q.db.QueryRow(ctx, createAttestation,
		arg.TranscriptID,
		arg.AttesterID,
		arg.OrgLogin,
		arg.AttestationType,
		arg.Note,
	)
	var i Attestation
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.AttesterID,
		&i.OrgLogin,
		&i.AttestationType,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttestation = `-- name: DeleteAttestation :exec
DELETE FROM attestations
WHERE id = $1 AND attester_id = $2
`

type DeleteAttestationParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	AttesterID pgtype.UUID `db:"attester_id" json:"attester_id"`
}

func (q *Queries) DeleteAttestation(ctx context.Context, arg DeleteAttestationParams) error {
	_, err := q.db.Exec(ctx, deleteAttestation, arg.ID, arg.AttesterID)
	return err
}

const listAttestationsByTranscriptIDs = `-- name: ListAttestationsByTranscriptIDs :many
SELECT a.transcript_id, a.org_login, a.attestation_type, a.created_at
FROM attestations a
WHERE a.transcript_id = ANY($1::uuid[])
ORDER BY a.created_at DESC
`

type ListAttestationsByTranscriptIDsRow struct {
	TranscriptID    pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	OrgLogin        string             `db:"org_login" json:"org_login"`
	AttestationType string             `db:"attestation_type" json:"attestation_type"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListAttestationsByTranscriptIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListAttestationsByTranscriptIDsRow, error) {
	rows, err := q.db.Query(ctx, listAttestationsByTranscriptIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttestationsByTranscriptIDsRow{}
	for rows.Next() {
		var i ListAttestationsByTranscriptIDsRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.OrgLogin,
			&i.AttestationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptAttestations = `-- name: ListTranscriptAttestations :many
SELECT a.id, a.transcript_id, a.org_login, a.attestation_type, a.note, a.created_at,
       u.github_username as attester_username, u.avatar_url as attester_avatar
FROM attestations a
JOIN users u ON a.attester_id = u.id
WHERE a.transcript_id = $1
ORDER BY a.created_at DESC
`

type ListTranscriptAttestationsRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	TranscriptID     pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	OrgLogin         string             `db:"org_login" json:"org_login"`
	AttestationType  string             `db:"attestation_type" json:"attestation_type"`
	Note             pgtype.Text        `db:"note" json:"note"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	AttesterUsername string             `db:"attester_username" json:"attester_username"`
	AttesterAvatar   pgtype.Text        `db:"attester_avatar" json:"attester_avatar"`
}

func (q *Queries) ListTranscriptAttestations(ctx context.Context, transcriptID pgtype.UUID) ([]ListTranscriptAttestationsRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptAttestations, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptAttestationsRow{}
	for rows.Next() {
		var i ListTranscriptAttestationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.OrgLogin,
			&i.AttestationType,
			&i.Note,
			&i.CreatedAt,
			&i.AttesterUsername,
			&i.AttesterAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
