// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cli_sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const exchangeCLISession = `-- name: ExchangeCLISession :one
UPDATE cli_auth_sessions
SET exchanged_at = now()
WHERE exchange_code = $1
  AND cli_state = $2
  AND exchanged_at IS NULL
  AND created_at > now() - interval '5 minutes'
RETURNING id, oauth_state, cli_port, cli_state, exchange_code, user_id, username, created_at, exchanged_at
`

type ExchangeCLISessionParams struct {
	ExchangeCode pgtype.Text `db:"exchange_code" json:"exchange_code"`
	CliState     string      `db:"cli_state" json:"cli_state"`
}

func (q *Queries) ExchangeCLISession(ctx context.Context, arg ExchangeCLISessionParams) (CliAuthSession, error) {
	row := q.db.QueryRow(ctx, exchangeCLISession, arg.ExchangeCode, arg.CliState)
	var i CliAuthSession
	err := row.Scan(
		&i.ID,
		&i.OauthState,
		&i.CliPort,
		&i.CliState,
		&i.ExchangeCode,
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
		&i.ExchangedAt,
	)
	return i, err
}

const getCLISessionByState = `-- name: GetCLISessionByState :one
SELECT id, oauth_state, cli_port, cli_state, exchange_code, user_id, username, created_at, exchanged_at FROM cli_auth_sessions
WHERE oauth_state = $1
`

func (q *Queries) GetCLISessionByState(ctx context.Context, oauthState string) (CliAuthSession, error) {
	row := q.db.QueryRow(ctx, getCLISessionByState, oauthState)
	var i CliAuthSession
	err := row.Scan(
		&i.ID,
		&i.OauthState,
		&i.CliPort,
		&i.CliState,
		&i.ExchangeCode,
		&i.UserID,
		&i.Username,
		&i.CreatedAt,
		&i.ExchangedAt,
	)
	return i, err
}

const insertCLISession = `-- name: InsertCLISession :one
INSERT INTO cli_auth_sessions (oauth_state, cli_port, cli_state)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertCLISessionParams struct {
	OauthState string `db:"oauth_state" json:"oauth_state"`
	CliPort    int32  `db:"cli_port" json:"cli_port"`
	CliState   string `db:"cli_state" json:"cli_state"`
}

func (q *Queries) InsertCLISession(ctx context.Context, arg InsertCLISessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCLISession, arg.OauthState, arg.CliPort, arg.CliState)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateCLISessionWithCode = `-- name: UpdateCLISessionWithCode :exec
UPDATE cli_auth_sessions
SET exchange_code = $2,
    user_id = $3,
    username = $4
WHERE oauth_state = $1
`

type UpdateCLISessionWithCodeParams struct {
	OauthState   string      `db:"oauth_state" json:"oauth_state"`
	ExchangeCode pgtype.Text `db:"exchange_code" json:"exchange_code"`
	UserID       pgtype.UUID `db:"user_id" json:"user_id"`
	Username     pgtype.Text `db:"username" json:"username"`
}

func (q *Queries) UpdateCLISessionWithCode(ctx context.Context, arg UpdateCLISessionWithCodeParams) error {
	_, err := q.db.Exec(ctx, updateCLISessionWithCode,
		arg.OauthState,
		arg.ExchangeCode,
		arg.UserID,
		arg.Username,
	)
	return err
}
