// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collective_grouped.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCollectiveGroupedCandidates = `-- name: ListCollectiveGroupedCandidates :many
SELECT t.id, t.owner_id, t.local_id, t.title, t.description, t.visibility, t.model_provider, t.model_name, t.harness_version, t.session_start, t.session_end, t.turn_count, t.token_count, t.blob_key, t.blob_size_bytes, t.schema_version, t.published_at, t.updated_at, t.parent_session_id, t.ingested_at, t.source_file_path, t.source_format, t.git_branch, t.git_remote, t.git_worktree, t.project_hash, t.project_path, t.project_name, t.tool_call_count, t.subagent_count, t.duration_ms, t.subagents, t.diagnostics_warnings, t.diagnostics_partial, t.tokens_in, t.tokens_out, t.title_generated, t.outcome, t.files_touched, t.lines_changed, t.retry_loops, t.retry_tokens_wasted, t.within_session_reverts, t.signal_density, t.spec_quality_score, t.exploration_ratio, t.scope_breadth, t.discovery_turns, t.m2_token_outcome_ratio, t.m3_unique_tool_count, t.m4_error_recovery_count, t.m4_consecutive_error_max, t.m5_context_utilization_pct, t.m5_peak_context_tokens, t.m5_avg_message_tokens, t.m6_output_survival_pct, t.m6_lines_survived, t.m6_lines_total, t.m7_spec_word_count, t.m7_spec_has_examples, t.m7_spec_has_constraints, t.computed_at, t.compute_version, t.content_hash, t.license_id, t.wrapped_data_key, t.encryption_algorithm, t.key_version, t.accepted_request_operation_fingerprint, t.session_origin, t.input_submission_count, t.root_session_id, t.session_purpose, t.session_relationships,
       u.github_username AS owner_username,
       u.avatar_url AS owner_avatar_url,
       u.is_discoverable AS owner_is_discoverable,
       COALESCE(ts.status, '')::text AS share_status,
       ts.shared_at,
       EXISTS (
           SELECT 1 FROM transcript_share_attempts a
           WHERE a.transcript_id = t.id AND a.group_id = $1
             AND a.status IN ('pending', 'approved')
             AND a.event_num = (
                 SELECT max(b.event_num) FROM transcript_share_attempts b
                 WHERE b.transcript_id = t.id AND b.group_id = $1
             )
       )::boolean AS already_shared
FROM transcripts t
JOIN users u ON u.id = t.owner_id
JOIN groups g ON g.id = $1
LEFT JOIN group_members gm ON gm.group_id = g.id AND gm.user_id = $2
LEFT JOIN transcript_shares ts ON ts.transcript_id = t.id AND ts.group_id = g.id
WHERE (
    ($3::text = 'collective' AND ts.status = 'approved' AND (
        g.data_access = 'public'
        OR (g.data_access = 'contributors' AND gm.role IN ('contributor', 'member', 'owner'))
        OR (g.data_access = 'members_only' AND gm.role IN ('member', 'owner'))
    ))
    OR ($3::text = 'pending' AND ts.status = 'pending' AND gm.role = 'owner')
    OR ($3::text = 'my-shares' AND ts.transcript_id IS NOT NULL AND t.owner_id = $2)
    OR ($3::text = 'contributable' AND gm.user_id IS NOT NULL AND t.owner_id = $2
        AND NOT EXISTS (
            SELECT 1 FROM transcript_share_attempts a
            WHERE a.transcript_id = t.id AND a.group_id = g.id
              AND a.status IN ('pending', 'approved')
              AND a.event_num = (
                  SELECT max(b.event_num) FROM transcript_share_attempts b
                  WHERE b.transcript_id = t.id AND b.group_id = g.id
              )
        ))
)
AND ($4::text = '' OR t.project_hash = $4)
AND ($5::text = '' OR t.title ILIKE '%' || $5 || '%' OR t.description ILIKE '%' || $5 || '%')
ORDER BY COALESCE(t.session_start, t.published_at) DESC, t.id ASC
`

type ListCollectiveGroupedCandidatesParams struct {
	GroupID     pgtype.UUID `db:"group_id" json:"group_id"`
	ViewerID    pgtype.UUID `db:"viewer_id" json:"viewer_id"`
	RouteKind   string      `db:"route_kind" json:"route_kind"`
	ProjectHash string      `db:"project_hash" json:"project_hash"`
	Search      string      `db:"search" json:"search"`
}

type ListCollectiveGroupedCandidatesRow struct {
	Transcript          Transcript         `db:"transcript" json:"transcript"`
	OwnerUsername       string             `db:"owner_username" json:"owner_username"`
	OwnerAvatarUrl      pgtype.Text        `db:"owner_avatar_url" json:"owner_avatar_url"`
	OwnerIsDiscoverable bool               `db:"owner_is_discoverable" json:"owner_is_discoverable"`
	ShareStatus         string             `db:"share_status" json:"share_status"`
	SharedAt            pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
	AlreadyShared       bool               `db:"already_shared" json:"already_shared"`
}

// Complete candidates, never a flat transcript page. The grouped pager and
// member replay consume this identical set. route_kind is a server-selected
// closed variant, not a caller-supplied SQL or authorization expression.
func (q *Queries) ListCollectiveGroupedCandidates(ctx context.Context, arg ListCollectiveGroupedCandidatesParams) ([]ListCollectiveGroupedCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listCollectiveGroupedCandidates,
		arg.GroupID,
		arg.ViewerID,
		arg.RouteKind,
		arg.ProjectHash,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectiveGroupedCandidatesRow{}
	for rows.Next() {
		var i ListCollectiveGroupedCandidatesRow
		if err := rows.Scan(
			&i.Transcript.ID,
			&i.Transcript.OwnerID,
			&i.Transcript.LocalID,
			&i.Transcript.Title,
			&i.Transcript.Description,
			&i.Transcript.Visibility,
			&i.Transcript.ModelProvider,
			&i.Transcript.ModelName,
			&i.Transcript.HarnessVersion,
			&i.Transcript.SessionStart,
			&i.Transcript.SessionEnd,
			&i.Transcript.TurnCount,
			&i.Transcript.TokenCount,
			&i.Transcript.BlobKey,
			&i.Transcript.BlobSizeBytes,
			&i.Transcript.SchemaVersion,
			&i.Transcript.PublishedAt,
			&i.Transcript.UpdatedAt,
			&i.Transcript.ParentSessionID,
			&i.Transcript.IngestedAt,
			&i.Transcript.SourceFilePath,
			&i.Transcript.SourceFormat,
			&i.Transcript.GitBranch,
			&i.Transcript.GitRemote,
			&i.Transcript.GitWorktree,
			&i.Transcript.ProjectHash,
			&i.Transcript.ProjectPath,
			&i.Transcript.ProjectName,
			&i.Transcript.ToolCallCount,
			&i.Transcript.SubagentCount,
			&i.Transcript.DurationMs,
			&i.Transcript.Subagents,
			&i.Transcript.DiagnosticsWarnings,
			&i.Transcript.DiagnosticsPartial,
			&i.Transcript.TokensIn,
			&i.Transcript.TokensOut,
			&i.Transcript.TitleGenerated,
			&i.Transcript.Outcome,
			&i.Transcript.FilesTouched,
			&i.Transcript.LinesChanged,
			&i.Transcript.RetryLoops,
			&i.Transcript.RetryTokensWasted,
			&i.Transcript.WithinSessionReverts,
			&i.Transcript.SignalDensity,
			&i.Transcript.SpecQualityScore,
			&i.Transcript.ExplorationRatio,
			&i.Transcript.ScopeBreadth,
			&i.Transcript.DiscoveryTurns,
			&i.Transcript.M2TokenOutcomeRatio,
			&i.Transcript.M3UniqueToolCount,
			&i.Transcript.M4ErrorRecoveryCount,
			&i.Transcript.M4ConsecutiveErrorMax,
			&i.Transcript.M5ContextUtilizationPct,
			&i.Transcript.M5PeakContextTokens,
			&i.Transcript.M5AvgMessageTokens,
			&i.Transcript.M6OutputSurvivalPct,
			&i.Transcript.M6LinesSurvived,
			&i.Transcript.M6LinesTotal,
			&i.Transcript.M7SpecWordCount,
			&i.Transcript.M7SpecHasExamples,
			&i.Transcript.M7SpecHasConstraints,
			&i.Transcript.ComputedAt,
			&i.Transcript.ComputeVersion,
			&i.Transcript.ContentHash,
			&i.Transcript.LicenseID,
			&i.Transcript.WrappedDataKey,
			&i.Transcript.EncryptionAlgorithm,
			&i.Transcript.KeyVersion,
			&i.Transcript.AcceptedRequestOperationFingerprint,
			&i.Transcript.SessionOrigin,
			&i.Transcript.InputSubmissionCount,
			&i.Transcript.RootSessionID,
			&i.Transcript.SessionPurpose,
			&i.Transcript.SessionRelationships,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerIsDiscoverable,
			&i.ShareStatus,
			&i.SharedAt,
			&i.AlreadyShared,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
