// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collective_repositories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRepositoryCommits = `-- name: CountRepositoryCommits :one
SELECT count(*) FROM repository_commits
WHERE lower(owner) = lower($1) AND lower(name) = lower($2)
`

type CountRepositoryCommitsParams struct {
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower_2"`
}

func (q *Queries) CountRepositoryCommits(ctx context.Context, arg CountRepositoryCommitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRepositoryCommits, arg.Lower, arg.Lower_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCollectiveRepository = `-- name: GetCollectiveRepository :one
SELECT id, group_id, owner, name, installation_id, is_private, linked_by, commits_etag, last_synced_at, created_at FROM collective_repositories
WHERE group_id = $1 AND lower(owner) = lower($2) AND lower(name) = lower($3)
`

type GetCollectiveRepositoryParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	Lower   string      `db:"lower" json:"lower"`
	Lower_2 string      `db:"lower_2" json:"lower_2"`
}

func (q *Queries) GetCollectiveRepository(ctx context.Context, arg GetCollectiveRepositoryParams) (CollectiveRepository, error) {
	row := q.db.QueryRow(ctx, getCollectiveRepository, arg.GroupID, arg.Lower, arg.Lower_2)
	var i CollectiveRepository
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Owner,
		&i.Name,
		&i.InstallationID,
		&i.IsPrivate,
		&i.LinkedBy,
		&i.CommitsEtag,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getGitHubAppInstallation = `-- name: GetGitHubAppInstallation :one
SELECT installation_id, account_login, account_id, account_type, created_at, updated_at FROM github_app_installations WHERE installation_id = $1
`

func (q *Queries) GetGitHubAppInstallation(ctx context.Context, installationID int64) (GithubAppInstallation, error) {
	row := q.db.QueryRow(ctx, getGitHubAppInstallation, installationID)
	var i GithubAppInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountID,
		&i.AccountType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkCollectiveRepository = `-- name: LinkCollectiveRepository :one
INSERT INTO collective_repositories (
    group_id, owner, name, installation_id, is_private, linked_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (group_id, owner, name) DO UPDATE SET
    installation_id = EXCLUDED.installation_id,
    is_private      = EXCLUDED.is_private,
    linked_by       = EXCLUDED.linked_by
RETURNING id, group_id, owner, name, installation_id, is_private, linked_by, commits_etag, last_synced_at, created_at
`

type LinkCollectiveRepositoryParams struct {
	GroupID        pgtype.UUID `db:"group_id" json:"group_id"`
	Owner          string      `db:"owner" json:"owner"`
	Name           string      `db:"name" json:"name"`
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	IsPrivate      bool        `db:"is_private" json:"is_private"`
	LinkedBy       pgtype.UUID `db:"linked_by" json:"linked_by"`
}

// Links a repo to a collective. UNIQUE(group_id, owner, name) means a repeat
// link is a no-op-ish upsert that refreshes the installation/privacy/linker.
func (q *Queries) LinkCollectiveRepository(ctx context.Context, arg LinkCollectiveRepositoryParams) (CollectiveRepository, error) {
	row := q.db.QueryRow(ctx, linkCollectiveRepository,
		arg.GroupID,
		arg.Owner,
		arg.Name,
		arg.InstallationID,
		arg.IsPrivate,
		arg.LinkedBy,
	)
	var i CollectiveRepository
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Owner,
		&i.Name,
		&i.InstallationID,
		&i.IsPrivate,
		&i.LinkedBy,
		&i.CommitsEtag,
		&i.LastSyncedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCollectiveRepositories = `-- name: ListCollectiveRepositories :many
SELECT id, group_id, owner, name, installation_id, is_private, linked_by, commits_etag, last_synced_at, created_at FROM collective_repositories
WHERE group_id = $1
ORDER BY owner ASC, name ASC
`

func (q *Queries) ListCollectiveRepositories(ctx context.Context, groupID pgtype.UUID) ([]CollectiveRepository, error) {
	rows, err := q.db.Query(ctx, listCollectiveRepositories, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CollectiveRepository{}
	for rows.Next() {
		var i CollectiveRepository
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Owner,
			&i.Name,
			&i.InstallationID,
			&i.IsPrivate,
			&i.LinkedBy,
			&i.CommitsEtag,
			&i.LastSyncedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryCommits = `-- name: ListRepositoryCommits :many
SELECT id, owner, name, sha, message, author_name, author_email, authored_at, committed_at, fetched_at FROM repository_commits
WHERE lower(owner) = lower($1) AND lower(name) = lower($2)
ORDER BY committed_at DESC NULLS LAST, sha ASC
LIMIT $3
`

type ListRepositoryCommitsParams struct {
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower_2"`
	Limit   int32  `db:"limit" json:"limit"`
}

// Returns cached commits for a repo, newest first.
func (q *Queries) ListRepositoryCommits(ctx context.Context, arg ListRepositoryCommitsParams) ([]RepositoryCommit, error) {
	rows, err := q.db.Query(ctx, listRepositoryCommits, arg.Lower, arg.Lower_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RepositoryCommit{}
	for rows.Next() {
		var i RepositoryCommit
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.Sha,
			&i.Message,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.AuthoredAt,
			&i.CommittedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkCollectiveRepository = `-- name: UnlinkCollectiveRepository :execrows
DELETE FROM collective_repositories
WHERE group_id = $1 AND lower(owner) = lower($2) AND lower(name) = lower($3)
`

type UnlinkCollectiveRepositoryParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	Lower   string      `db:"lower" json:"lower"`
	Lower_2 string      `db:"lower_2" json:"lower_2"`
}

// Removes a repo link from a collective. Returns rows affected so the handler
// can distinguish "unlinked" from "was not linked" (404).
func (q *Queries) UnlinkCollectiveRepository(ctx context.Context, arg UnlinkCollectiveRepositoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkCollectiveRepository, arg.GroupID, arg.Lower, arg.Lower_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCollectiveRepositorySync = `-- name: UpdateCollectiveRepositorySync :exec
UPDATE collective_repositories
SET commits_etag = $4, last_synced_at = now()
WHERE group_id = $1 AND lower(owner) = lower($2) AND lower(name) = lower($3)
`

type UpdateCollectiveRepositorySyncParams struct {
	GroupID     pgtype.UUID `db:"group_id" json:"group_id"`
	Lower       string      `db:"lower" json:"lower"`
	Lower_2     string      `db:"lower_2" json:"lower_2"`
	CommitsEtag pgtype.Text `db:"commits_etag" json:"commits_etag"`
}

// Persists the latest ETag + sync time after a commit refresh so the next
// refresh can issue a conditional request.
func (q *Queries) UpdateCollectiveRepositorySync(ctx context.Context, arg UpdateCollectiveRepositorySyncParams) error {
	_, err := q.db.Exec(ctx, updateCollectiveRepositorySync,
		arg.GroupID,
		arg.Lower,
		arg.Lower_2,
		arg.CommitsEtag,
	)
	return err
}

const upsertGitHubAppInstallation = `-- name: UpsertGitHubAppInstallation :exec
INSERT INTO github_app_installations (
    installation_id, account_login, account_id, account_type
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (installation_id) DO UPDATE SET
    account_login = EXCLUDED.account_login,
    account_id    = EXCLUDED.account_id,
    account_type  = EXCLUDED.account_type,
    updated_at    = now()
`

type UpsertGitHubAppInstallationParams struct {
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	AccountLogin   string      `db:"account_login" json:"account_login"`
	AccountID      int64       `db:"account_id" json:"account_id"`
	AccountType    pgtype.Text `db:"account_type" json:"account_type"`
}

// Records (or refreshes) a known GitHub App installation. Idempotent on
// installation_id so re-observing the same installation just updates metadata.
func (q *Queries) UpsertGitHubAppInstallation(ctx context.Context, arg UpsertGitHubAppInstallationParams) error {
	_, err := q.db.Exec(ctx, upsertGitHubAppInstallation,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountID,
		arg.AccountType,
	)
	return err
}

const upsertRepositoryCommit = `-- name: UpsertRepositoryCommit :exec
INSERT INTO repository_commits (
    owner, name, sha, message, author_name, author_email, authored_at, committed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (owner, name, sha) DO UPDATE SET
    message      = EXCLUDED.message,
    author_name  = EXCLUDED.author_name,
    author_email = EXCLUDED.author_email,
    authored_at  = EXCLUDED.authored_at,
    committed_at = EXCLUDED.committed_at,
    fetched_at   = now()
`

type UpsertRepositoryCommitParams struct {
	Owner       string             `db:"owner" json:"owner"`
	Name        string             `db:"name" json:"name"`
	Sha         string             `db:"sha" json:"sha"`
	Message     pgtype.Text        `db:"message" json:"message"`
	AuthorName  pgtype.Text        `db:"author_name" json:"author_name"`
	AuthorEmail pgtype.Text        `db:"author_email" json:"author_email"`
	AuthoredAt  pgtype.Timestamptz `db:"authored_at" json:"authored_at"`
	CommittedAt pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
}

// Caches a single repo commit. Idempotent on (owner, name, sha): re-fetching the
// same commit refreshes its row rather than duplicating it.
func (q *Queries) UpsertRepositoryCommit(ctx context.Context, arg UpsertRepositoryCommitParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryCommit,
		arg.Owner,
		arg.Name,
		arg.Sha,
		arg.Message,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthoredAt,
		arg.CommittedAt,
	)
	return err
}
