// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_webhook_deliveries.sql

package sqlc

import (
	"context"
)

const recordGitHubWebhookDelivery = `-- name: RecordGitHubWebhookDelivery :execrows
INSERT INTO github_webhook_deliveries (delivery_id)
VALUES ($1)
ON CONFLICT (delivery_id) DO NOTHING
`

// Records one webhook delivery id. Returns the number of rows inserted: 1 for a
// first delivery, 0 when the id was already recorded (a replay), which is how
// the receiver tells the two apart without a second round trip.
func (q *Queries) RecordGitHubWebhookDelivery(ctx context.Context, deliveryID string) (int64, error) {
	result, err := q.db.Exec(ctx, recordGitHubWebhookDelivery, deliveryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
