// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Role    string      `db:"role" json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, created_by, acceptance_mode, data_access, linked_github_org)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy
`

type CreateGroupParams struct {
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	CreatedBy       pgtype.UUID `db:"created_by" json:"created_by"`
	AcceptanceMode  string      `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess      string      `db:"data_access" json:"data_access"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.AcceptanceMode,
		arg.DataAccess,
		arg.LinkedGithubOrg,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, joined_at FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listAllGroups = `-- name: ListAllGroups :many
SELECT g.id, g.name, g.description, g.acceptance_mode, g.data_access, g.linked_github_org, g.created_at,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
GROUP BY g.id
ORDER BY member_count DESC, g.name
`

type ListAllGroupsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AcceptanceMode  string             `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess      string             `db:"data_access" json:"data_access"`
	LinkedGithubOrg pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MemberCount     int32              `db:"member_count" json:"member_count"`
	TranscriptCount int32              `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) ListAllGroups(ctx context.Context) ([]ListAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGroupsRow{}
	for rows.Next() {
		var i ListAllGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AcceptanceMode,
			&i.DataAccess,
			&i.LinkedGithubOrg,
			&i.CreatedAt,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectivesByGitHubOrg = `-- name: ListCollectivesByGitHubOrg :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
WHERE lower(g.linked_github_org) = lower($1)
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $2
        )
      )
GROUP BY g.id
ORDER BY member_count DESC, transcript_count DESC
`

type ListCollectivesByGitHubOrgParams struct {
	Lower  string      `db:"lower" json:"lower"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type ListCollectivesByGitHubOrgRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

// Returns collectives linked to the given GitHub org (case-insensitive),
// filtered to those the caller can see (same rules as SearchCollectives).
// $1 = org login (case-insensitive match).
// $2 = caller user_id (nullable: use NULL for unauthenticated callers).
func (q *Queries) ListCollectivesByGitHubOrg(ctx context.Context, arg ListCollectivesByGitHubOrgParams) ([]ListCollectivesByGitHubOrgRow, error) {
	rows, err := q.db.Query(ctx, listCollectivesByGitHubOrg, arg.Lower, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectivesByGitHubOrgRow{}
	for rows.Next() {
		var i ListCollectivesByGitHubOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url,
       COALESCE(ARRAY_AGG(ugo.org_login) FILTER (WHERE ugo.org_login IS NOT NULL), '{}')::TEXT[] AS github_orgs
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN user_github_orgs ugo ON ugo.user_id = u.id AND ugo.visible = TRUE
WHERE gm.group_id = $1
  AND gm.role != 'pending'
  AND (u.is_discoverable = TRUE OR $2::boolean)
GROUP BY gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url
ORDER BY gm.role, u.github_username
`

type ListGroupMembersParams struct {
	GroupID       pgtype.UUID `db:"group_id" json:"group_id"`
	ViewerIsOwner bool        `db:"viewer_is_owner" json:"viewer_is_owner"`
}

type ListGroupMembersRow struct {
	Role           string             `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	GithubUsername string             `db:"github_username" json:"github_username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	GithubOrgs     []string           `db:"github_orgs" json:"github_orgs"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.ViewerIsOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.Role,
			&i.JoinedAt,
			&i.ID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GithubOrgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupPendingMembers = `-- name: ListGroupPendingMembers :many
SELECT gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url,
       COALESCE(ARRAY_AGG(ugo.org_login) FILTER (WHERE ugo.org_login IS NOT NULL), '{}')::TEXT[] AS github_orgs
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN user_github_orgs ugo ON ugo.user_id = u.id AND ugo.visible = TRUE
WHERE gm.group_id = $1
  AND gm.role = 'pending'
GROUP BY gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url
ORDER BY gm.joined_at, u.github_username
`

type ListGroupPendingMembersRow struct {
	Role           string             `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	GithubUsername string             `db:"github_username" json:"github_username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	GithubOrgs     []string           `db:"github_orgs" json:"github_orgs"`
}

func (q *Queries) ListGroupPendingMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupPendingMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupPendingMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupPendingMembersRow{}
	for rows.Next() {
		var i ListGroupPendingMembersRow
		if err := rows.Scan(
			&i.Role,
			&i.JoinedAt,
			&i.ID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GithubOrgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.created_by, g.created_at, g.updated_at,
       g.acceptance_mode, g.data_access, g.linked_github_org, g.display_members,
       g.transcript_deletion_policy,
       gm.role, gm.joined_at AS member_since,
       (SELECT COUNT(*) FROM group_members gm2
          WHERE gm2.group_id = g.id AND gm2.role != 'pending')::int AS member_count,
       (SELECT COUNT(*) FROM transcript_shares ts
          WHERE ts.group_id = g.id AND ts.status = 'approved')::int AS transcript_count
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.name
`

type ListUserGroupsRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Name                     string             `db:"name" json:"name"`
	Description              pgtype.Text        `db:"description" json:"description"`
	CreatedBy                pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AcceptanceMode           string             `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess               string             `db:"data_access" json:"data_access"`
	LinkedGithubOrg          pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	DisplayMembers           bool               `db:"display_members" json:"display_members"`
	TranscriptDeletionPolicy string             `db:"transcript_deletion_policy" json:"transcript_deletion_policy"`
	Role                     string             `db:"role" json:"role"`
	MemberSince              pgtype.Timestamptz `db:"member_since" json:"member_since"`
	MemberCount              int32              `db:"member_count" json:"member_count"`
	TranscriptCount          int32              `db:"transcript_count" json:"transcript_count"`
}

// member_count here deliberately EXCLUDES role='pending' members, to match
// the members roster (ListGroupMembers, which also filters role != 'pending').
// The 3 sibling list queries (ListAllGroups / SearchCollectives /
// ListCollectivesByGitHubOrg) INCLUDE pending members in their member_count.
// This per-surface split is intentional: the user-groups endpoint mirrors its
// member roster, while discovery surfaces report all memberships.
func (q *Queries) ListUserGroups(ctx context.Context, userID pgtype.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGroupsRow{}
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptanceMode,
			&i.DataAccess,
			&i.LinkedGithubOrg,
			&i.DisplayMembers,
			&i.TranscriptDeletionPolicy,
			&i.Role,
			&i.MemberSince,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const searchCollectives = `-- name: SearchCollectives :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
WHERE (
        g.name ILIKE '%' || $1 || '%'
        OR g.description ILIKE '%' || $1 || '%'
        OR g.linked_github_org ILIKE '%' || $1 || '%'
      )
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $2
        )
      )
GROUP BY g.id
ORDER BY member_count DESC, transcript_count DESC
LIMIT $3
`

type SearchCollectivesParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Limit   int32       `db:"limit" json:"limit"`
}

type SearchCollectivesRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

// Returns collectives matching the query, filtered to those the caller can see.
// A collective is visible if:
//   - data_access = 'public', OR
//   - acceptance_mode = 'open', OR
//   - the caller (when authenticated) is a member.
//
// $1 = query string (case-insensitive substring match against name/description/linked_github_org).
// $2 = caller user_id (nullable: use NULL for unauthenticated callers).
// $3 = limit.
func (q *Queries) SearchCollectives(ctx context.Context, arg SearchCollectivesParams) ([]SearchCollectivesRow, error) {
	rows, err := q.db.Query(ctx, searchCollectives, arg.Column1, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCollectivesRow{}
	for rows.Next() {
		var i SearchCollectivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = $2,
    description = $3,
    data_access = $4,
    acceptance_mode = $5,
    linked_github_org = $6,
    display_members = $7,
    transcript_deletion_policy = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy
`

type UpdateGroupParams struct {
	ID                       pgtype.UUID `db:"id" json:"id"`
	Name                     string      `db:"name" json:"name"`
	Description              pgtype.Text `db:"description" json:"description"`
	DataAccess               string      `db:"data_access" json:"data_access"`
	AcceptanceMode           string      `db:"acceptance_mode" json:"acceptance_mode"`
	LinkedGithubOrg          pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	DisplayMembers           bool        `db:"display_members" json:"display_members"`
	TranscriptDeletionPolicy string      `db:"transcript_deletion_policy" json:"transcript_deletion_policy"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DataAccess,
		arg.AcceptanceMode,
		arg.LinkedGithubOrg,
		arg.DisplayMembers,
		arg.TranscriptDeletionPolicy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE group_members SET role = $3 WHERE group_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Role    string      `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}
