// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grouped_transcripts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGroupedCyclicHelpers = `-- name: ListGroupedCyclicHelpers :many
WITH RECURSIVE parents AS (
    SELECT t.owner_id, t.local_id,
        CASE WHEN relation.value IS NOT NULL THEN
            CASE WHEN relation.value->>'targetState' IN ('target_known', 'target_known_retained')
                 THEN relation.value->>'targetLocalId' END
        ELSE t.parent_session_id END AS parent_local_id
    FROM transcripts t
    LEFT JOIN LATERAL (
        SELECT edge.value FROM jsonb_array_elements(t.session_relationships) AS edge(value)
        WHERE edge.value->>'kind' = 'started_by'
    ) relation ON true
    WHERE t.owner_id IN (SELECT owner_id FROM transcripts WHERE id=ANY($1::uuid[]))
), walk AS (
    SELECT t.id AS transcript_id, p.owner_id, p.parent_local_id,
           ARRAY[p.local_id]::text[] AS visited, false AS cyclic
    FROM transcripts t JOIN parents p ON p.owner_id=t.owner_id AND p.local_id=t.local_id
    WHERE t.id = ANY($1::uuid[]) AND t.session_purpose='helper_review'
    UNION ALL
    SELECT w.transcript_id, p.owner_id, p.parent_local_id,
           w.visited || p.local_id, p.local_id=ANY(w.visited)
    FROM walk w JOIN parents p ON p.owner_id=w.owner_id AND p.local_id=w.parent_local_id
    WHERE NOT w.cyclic
)
SELECT DISTINCT transcript_id FROM walk WHERE cyclic
`

// A filtered-out ancestor must not change a helper's group identity. Read only
// owner-local edge identities to classify cycles; never return ancestor rows,
// titles, content, timestamps, or counts to the caller.
func (q *Queries) ListGroupedCyclicHelpers(ctx context.Context, transcriptIds []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupedCyclicHelpers, transcriptIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var transcript_id pgtype.UUID
		if err := rows.Scan(&transcript_id); err != nil {
			return nil, err
		}
		items = append(items, transcript_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupedTranscriptCandidates = `-- name: ListGroupedTranscriptCandidates :many
SELECT t.id, t.owner_id, t.local_id, t.title, t.description, t.visibility, t.model_provider, t.model_name, t.harness_version, t.session_start, t.session_end, t.turn_count, t.token_count, t.blob_key, t.blob_size_bytes, t.schema_version, t.published_at, t.updated_at, t.parent_session_id, t.ingested_at, t.source_file_path, t.source_format, t.git_branch, t.git_remote, t.git_worktree, t.project_hash, t.project_path, t.project_name, t.tool_call_count, t.subagent_count, t.duration_ms, t.subagents, t.diagnostics_warnings, t.diagnostics_partial, t.tokens_in, t.tokens_out, t.title_generated, t.outcome, t.files_touched, t.lines_changed, t.retry_loops, t.retry_tokens_wasted, t.within_session_reverts, t.signal_density, t.spec_quality_score, t.exploration_ratio, t.scope_breadth, t.discovery_turns, t.m2_token_outcome_ratio, t.m3_unique_tool_count, t.m4_error_recovery_count, t.m4_consecutive_error_max, t.m5_context_utilization_pct, t.m5_peak_context_tokens, t.m5_avg_message_tokens, t.m6_output_survival_pct, t.m6_lines_survived, t.m6_lines_total, t.m7_spec_word_count, t.m7_spec_has_examples, t.m7_spec_has_constraints, t.computed_at, t.compute_version, t.content_hash, t.license_id, t.wrapped_data_key, t.encryption_algorithm, t.key_version, t.accepted_request_operation_fingerprint, t.session_origin, t.input_submission_count, t.root_session_id, t.session_purpose, t.session_relationships FROM transcripts t
WHERE (
    t.visibility = 'public'
    OR t.owner_id = $1::uuid
    OR (t.visibility = 'shared' AND EXISTS (
        SELECT 1 FROM transcript_shares ts
        JOIN group_members gm ON gm.group_id = ts.group_id
        WHERE ts.transcript_id = t.id AND gm.user_id = $1::uuid
    ))
)
AND ($2::text = '' OR t.title ILIKE $3::text OR t.description ILIKE $3::text)
AND ($4::text = '' OR t.model_provider = $4::text)
AND ($5::text = '' OR t.owner_id = (SELECT id FROM users WHERE github_username = $5::text))
AND ($6::text = '' OR t.project_name ILIKE $7::text)
AND ($8::text = '' OR t.project_hash = $8::text)
AND ($9::text = '' OR t.git_remote ILIKE $10::text)
AND ($11::text = '' OR t.owner_id IN (
    SELECT user_id FROM user_github_orgs WHERE lower(org_login) = lower($11::text) AND visible = true
))
AND (cardinality($12::text[]) = 0 OR EXISTS (
    SELECT 1 FROM transcript_tags tt JOIN tags tg ON tg.id = tt.tag_id
    WHERE tt.transcript_id = t.id AND tg.name = ANY($12::text[])
))
AND (
    ($13::text <> '' AND t.session_origin = $13::text)
    OR ($13::text = '' AND (t.session_origin <> 'agent' OR t.session_purpose = 'helper_review'))
)
ORDER BY coalesce(t.session_start, t.published_at) DESC, t.id ASC
`

type ListGroupedTranscriptCandidatesParams struct {
	ViewerID          pgtype.UUID `db:"viewer_id" json:"viewer_id"`
	SearchText        string      `db:"search_text" json:"search_text"`
	SearchPattern     string      `db:"search_pattern" json:"search_pattern"`
	Provider          string      `db:"provider" json:"provider"`
	OwnerName         string      `db:"owner_name" json:"owner_name"`
	ProjectName       string      `db:"project_name" json:"project_name"`
	ProjectPattern    string      `db:"project_pattern" json:"project_pattern"`
	ProjectHash       string      `db:"project_hash" json:"project_hash"`
	Repository        string      `db:"repository" json:"repository"`
	RepositoryPattern string      `db:"repository_pattern" json:"repository_pattern"`
	Org               string      `db:"org" json:"org"`
	Tags              []string    `db:"tags" json:"tags"`
	Origin            string      `db:"origin" json:"origin"`
}

// No pagination here: group counts and top-level pages share this exact selected
// set. EXISTS avoids duplicating identities when tags or share memberships join.
func (q *Queries) ListGroupedTranscriptCandidates(ctx context.Context, arg ListGroupedTranscriptCandidatesParams) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listGroupedTranscriptCandidates,
		arg.ViewerID,
		arg.SearchText,
		arg.SearchPattern,
		arg.Provider,
		arg.OwnerName,
		arg.ProjectName,
		arg.ProjectPattern,
		arg.ProjectHash,
		arg.Repository,
		arg.RepositoryPattern,
		arg.Org,
		arg.Tags,
		arg.Origin,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcript{}
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.LocalID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.ModelProvider,
			&i.ModelName,
			&i.HarnessVersion,
			&i.SessionStart,
			&i.SessionEnd,
			&i.TurnCount,
			&i.TokenCount,
			&i.BlobKey,
			&i.BlobSizeBytes,
			&i.SchemaVersion,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.ParentSessionID,
			&i.IngestedAt,
			&i.SourceFilePath,
			&i.SourceFormat,
			&i.GitBranch,
			&i.GitRemote,
			&i.GitWorktree,
			&i.ProjectHash,
			&i.ProjectPath,
			&i.ProjectName,
			&i.ToolCallCount,
			&i.SubagentCount,
			&i.DurationMs,
			&i.Subagents,
			&i.DiagnosticsWarnings,
			&i.DiagnosticsPartial,
			&i.TokensIn,
			&i.TokensOut,
			&i.TitleGenerated,
			&i.Outcome,
			&i.FilesTouched,
			&i.LinesChanged,
			&i.RetryLoops,
			&i.RetryTokensWasted,
			&i.WithinSessionReverts,
			&i.SignalDensity,
			&i.SpecQualityScore,
			&i.ExplorationRatio,
			&i.ScopeBreadth,
			&i.DiscoveryTurns,
			&i.M2TokenOutcomeRatio,
			&i.M3UniqueToolCount,
			&i.M4ErrorRecoveryCount,
			&i.M4ConsecutiveErrorMax,
			&i.M5ContextUtilizationPct,
			&i.M5PeakContextTokens,
			&i.M5AvgMessageTokens,
			&i.M6OutputSurvivalPct,
			&i.M6LinesSurvived,
			&i.M6LinesTotal,
			&i.M7SpecWordCount,
			&i.M7SpecHasExamples,
			&i.M7SpecHasConstraints,
			&i.ComputedAt,
			&i.ComputeVersion,
			&i.ContentHash,
			&i.LicenseID,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
			&i.AcceptedRequestOperationFingerprint,
			&i.SessionOrigin,
			&i.InputSubmissionCount,
			&i.RootSessionID,
			&i.SessionPurpose,
			&i.SessionRelationships,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
