// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type AddGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Role    string      `db:"role" json:"role"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.Role)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, description, created_by, acceptance_mode, data_access, linked_github_org)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy
`

type CreateGroupParams struct {
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	CreatedBy       pgtype.UUID `db:"created_by" json:"created_by"`
	AcceptanceMode  string      `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess      string      `db:"data_access" json:"data_access"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.AcceptanceMode,
		arg.DataAccess,
		arg.LinkedGithubOrg,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id pgtype.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT group_id, user_id, role, joined_at FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listAllGroups = `-- name: ListAllGroups :many
SELECT g.id, g.name, g.description, g.acceptance_mode, g.data_access, g.linked_github_org, g.created_at,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
GROUP BY g.id
ORDER BY member_count DESC, g.name
`

type ListAllGroupsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AcceptanceMode  string             `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess      string             `db:"data_access" json:"data_access"`
	LinkedGithubOrg pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	MemberCount     int32              `db:"member_count" json:"member_count"`
	TranscriptCount int32              `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) ListAllGroups(ctx context.Context) ([]ListAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllGroupsRow{}
	for rows.Next() {
		var i ListAllGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.AcceptanceMode,
			&i.DataAccess,
			&i.LinkedGithubOrg,
			&i.CreatedAt,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectivesByGitHubOrg = `-- name: ListCollectivesByGitHubOrg :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
WHERE lower(g.linked_github_org) = lower($1)
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $2
        )
      )
GROUP BY g.id
ORDER BY member_count DESC, transcript_count DESC
`

type ListCollectivesByGitHubOrgParams struct {
	Lower  string      `db:"lower" json:"lower"`
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
}

type ListCollectivesByGitHubOrgRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

// Returns collectives linked to the given GitHub org (case-insensitive),
// filtered to those the caller can see (same rules as SearchCollectives).
// $1 = org login (case-insensitive match).
// $2 = caller user_id (nullable: use NULL for unauthenticated callers).
func (q *Queries) ListCollectivesByGitHubOrg(ctx context.Context, arg ListCollectivesByGitHubOrgParams) ([]ListCollectivesByGitHubOrgRow, error) {
	rows, err := q.db.Query(ctx, listCollectivesByGitHubOrg, arg.Lower, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCollectivesByGitHubOrgRow{}
	for rows.Next() {
		var i ListCollectivesByGitHubOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url,
       COALESCE(ARRAY_AGG(ugo.org_login) FILTER (WHERE ugo.org_login IS NOT NULL), '{}')::TEXT[] AS github_orgs
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN user_github_orgs ugo ON ugo.user_id = u.id AND ugo.visible = TRUE
WHERE gm.group_id = $1
  AND gm.role != 'pending'
  AND (u.is_discoverable = TRUE OR $2::boolean)
GROUP BY gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url
ORDER BY gm.role, u.github_username
`

type ListGroupMembersParams struct {
	GroupID       pgtype.UUID `db:"group_id" json:"group_id"`
	ViewerIsOwner bool        `db:"viewer_is_owner" json:"viewer_is_owner"`
}

type ListGroupMembersRow struct {
	Role           string             `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	GithubUsername string             `db:"github_username" json:"github_username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	GithubOrgs     []string           `db:"github_orgs" json:"github_orgs"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, arg ListGroupMembersParams) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, arg.GroupID, arg.ViewerIsOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.Role,
			&i.JoinedAt,
			&i.ID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GithubOrgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupPendingMembers = `-- name: ListGroupPendingMembers :many
SELECT gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url,
       COALESCE(ARRAY_AGG(ugo.org_login) FILTER (WHERE ugo.org_login IS NOT NULL), '{}')::TEXT[] AS github_orgs
FROM group_members gm
JOIN users u ON gm.user_id = u.id
LEFT JOIN user_github_orgs ugo ON ugo.user_id = u.id AND ugo.visible = TRUE
WHERE gm.group_id = $1
  AND gm.role = 'pending'
GROUP BY gm.role, gm.joined_at, u.id, u.github_username, u.display_name, u.avatar_url
ORDER BY gm.joined_at, u.github_username
`

type ListGroupPendingMembersRow struct {
	Role           string             `db:"role" json:"role"`
	JoinedAt       pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
	ID             pgtype.UUID        `db:"id" json:"id"`
	GithubUsername string             `db:"github_username" json:"github_username"`
	DisplayName    pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl      pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	GithubOrgs     []string           `db:"github_orgs" json:"github_orgs"`
}

func (q *Queries) ListGroupPendingMembers(ctx context.Context, groupID pgtype.UUID) ([]ListGroupPendingMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupPendingMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupPendingMembersRow{}
	for rows.Next() {
		var i ListGroupPendingMembersRow
		if err := rows.Scan(
			&i.Role,
			&i.JoinedAt,
			&i.ID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.GithubOrgs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerCollectiveContributions = `-- name: ListOwnerCollectiveContributions :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS approved_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'pending'  THEN ts.transcript_id END)::int AS pending_count,
       COUNT(CASE WHEN a.status = 'rejected' THEN 1 END)::int AS rejected_attempt_count
FROM transcript_share_attempts a
JOIN transcripts t ON t.id = a.transcript_id
JOIN groups g ON g.id = a.group_id
LEFT JOIN transcript_shares ts
       ON ts.transcript_id = a.transcript_id AND ts.group_id = a.group_id
WHERE t.owner_id = $1
GROUP BY g.id
ORDER BY approved_count DESC, pending_count DESC, g.name, g.id
`

type ListOwnerCollectiveContributionsRow struct {
	ID                   pgtype.UUID `db:"id" json:"id"`
	Name                 string      `db:"name" json:"name"`
	Description          pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg      pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	ApprovedCount        int32       `db:"approved_count" json:"approved_count"`
	PendingCount         int32       `db:"pending_count" json:"pending_count"`
	RejectedAttemptCount int32       `db:"rejected_attempt_count" json:"rejected_attempt_count"`
}

// The collectives the caller has offered transcripts to, with the three
// counters their profile renders, from ONE aggregate.
//
// approved_count and pending_count count DISTINCT TRANSCRIPTS: a transcript is
// either in a collective or it is not, so a contribution that was withdrawn and
// accepted again is still one contribution. rejected_attempt_count counts
// EVENTS, because one transcript can be refused by one collective repeatedly
// and each refusal is its own instance. The wire field says attempt for that
// reason. Withdrawn (retracted) and removed (revoked) events are counted in
// none of the three.
//
// The join is over the event ledger, so a collective holding nothing but
// submissions still awaiting review IS listed, with approved_count = 0. The
// counters do the filtering; the join must never do it.
//
// Owner-only: $1 is the authenticated caller. There is deliberately no username
// parameter and no username route, so no viewer can ask for another person's
// contributions. That is also why this statement carries no collective
// visibility predicate - the only thing such a predicate could hide is a
// collective the caller contributed to themselves.
// $1 = owner_id.
func (q *Queries) ListOwnerCollectiveContributions(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnerCollectiveContributionsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerCollectiveContributions, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerCollectiveContributionsRow{}
	for rows.Next() {
		var i ListOwnerCollectiveContributionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.ApprovedCount,
			&i.PendingCount,
			&i.RejectedAttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectCollectiveRollup = `-- name: ListProjectCollectiveRollup :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT ts.transcript_id)::int AS transcript_count
FROM transcripts t
JOIN transcript_shares ts ON ts.transcript_id = t.id AND ts.status = 'approved'
JOIN groups g ON g.id = ts.group_id
JOIN users u ON u.id = t.owner_id
WHERE t.owner_id = $1
  AND t.project_hash = $2
  AND (u.is_discoverable = TRUE OR $4::boolean)
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $3
        )
      )
GROUP BY g.id
ORDER BY transcript_count DESC, g.name, g.id
`

type ListProjectCollectiveRollupParams struct {
	OwnerID       pgtype.UUID `db:"owner_id" json:"owner_id"`
	ProjectHash   string      `db:"project_hash" json:"project_hash"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	ViewerIsOwner bool        `db:"viewer_is_owner" json:"viewer_is_owner"`
}

type ListProjectCollectiveRollupRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

// The collectives holding any accepted transcript of one project, for the
// project page. ONE aggregate over every transcript of the (owner, project)
// pair, grouped by collective - never a query per transcript.
//
// Two independent gates apply, and both must hold:
//   - the collective visibility rule, character-identical to SearchCollectives,
//     so a viewer never learns of a members-only collective they are outside;
//   - the contributor opt-in, the same predicate ListGroupContributors applies,
//     so a person who has not opted in to being listed as a contributor is not
//     listed by this surface either. When they have not opted in the result is
//     an EMPTY LIST rather than a refusal, because a refusal would itself
//     confirm that hidden memberships exist.
//
// $1 = owner_id, $2 = project_hash, $3 = viewer user_id (NULL when anonymous),
// viewer_is_owner = whether the viewer IS the project owner.
func (q *Queries) ListProjectCollectiveRollup(ctx context.Context, arg ListProjectCollectiveRollupParams) ([]ListProjectCollectiveRollupRow, error) {
	rows, err := q.db.Query(ctx, listProjectCollectiveRollup,
		arg.OwnerID,
		arg.ProjectHash,
		arg.UserID,
		arg.ViewerIsOwner,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectCollectiveRollupRow{}
	for rows.Next() {
		var i ListProjectCollectiveRollupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptCollectivesForViewer = `-- name: ListTranscriptCollectivesForViewer :many
SELECT g.id, g.name, g.description, g.linked_github_org, ts.shared_at
FROM transcript_shares ts
JOIN groups g ON g.id = ts.group_id
JOIN transcripts t ON t.id = ts.transcript_id
JOIN users u ON u.id = t.owner_id
WHERE ts.transcript_id = $1
  AND ts.status = 'approved'
  AND (u.is_discoverable = TRUE OR $3::boolean)
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $2
        )
      )
ORDER BY g.name, g.id
`

type ListTranscriptCollectivesForViewerParams struct {
	TranscriptID  pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	UserID        pgtype.UUID `db:"user_id" json:"user_id"`
	ViewerIsOwner bool        `db:"viewer_is_owner" json:"viewer_is_owner"`
}

type ListTranscriptCollectivesForViewerRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	Name            string             `db:"name" json:"name"`
	Description     pgtype.Text        `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	SharedAt        pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

// The accepted memberships of one transcript, restricted to the collectives the
// viewer may see. The visibility predicate is character-identical to
// SearchCollectives and is proven equivalent to it by a shared corpus, not by
// reading the two side by side.
//
// The contributor opt-in gates this surface too: the memberships are returned
// only when the transcript owner has opted in to being listed, or the viewer IS
// that owner. Otherwise the answer is an EMPTY LIST - never a refusal, which
// would itself confirm that hidden memberships exist.
// $1 = transcript_id, $2 = viewer user_id (NULL when anonymous),
// viewer_is_owner = whether the viewer IS the transcript owner.
func (q *Queries) ListTranscriptCollectivesForViewer(ctx context.Context, arg ListTranscriptCollectivesForViewerParams) ([]ListTranscriptCollectivesForViewerRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptCollectivesForViewer, arg.TranscriptID, arg.UserID, arg.ViewerIsOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptCollectivesForViewerRow{}
	for rows.Next() {
		var i ListTranscriptCollectivesForViewerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.description, g.created_by, g.created_at, g.updated_at,
       g.acceptance_mode, g.data_access, g.linked_github_org, g.display_members,
       g.transcript_deletion_policy,
       gm.role, gm.joined_at AS member_since,
       (SELECT COUNT(*) FROM group_members gm2
          WHERE gm2.group_id = g.id AND gm2.role != 'pending')::int AS member_count,
       (SELECT COUNT(*) FROM transcript_shares ts
          WHERE ts.group_id = g.id AND ts.status = 'approved')::int AS transcript_count
FROM groups g
JOIN group_members gm ON g.id = gm.group_id
WHERE gm.user_id = $1
ORDER BY g.name
`

type ListUserGroupsRow struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Name                     string             `db:"name" json:"name"`
	Description              pgtype.Text        `db:"description" json:"description"`
	CreatedBy                pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AcceptanceMode           string             `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess               string             `db:"data_access" json:"data_access"`
	LinkedGithubOrg          pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	DisplayMembers           bool               `db:"display_members" json:"display_members"`
	TranscriptDeletionPolicy string             `db:"transcript_deletion_policy" json:"transcript_deletion_policy"`
	Role                     string             `db:"role" json:"role"`
	MemberSince              pgtype.Timestamptz `db:"member_since" json:"member_since"`
	MemberCount              int32              `db:"member_count" json:"member_count"`
	TranscriptCount          int32              `db:"transcript_count" json:"transcript_count"`
}

// member_count here deliberately EXCLUDES role='pending' members, to match
// the members roster (ListGroupMembers, which also filters role != 'pending').
// The 3 sibling list queries (ListAllGroups / SearchCollectives /
// ListCollectivesByGitHubOrg) INCLUDE pending members in their member_count.
// This per-surface split is intentional: the user-groups endpoint mirrors its
// member roster, while discovery surfaces report all memberships.
func (q *Queries) ListUserGroups(ctx context.Context, userID pgtype.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.Query(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserGroupsRow{}
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AcceptanceMode,
			&i.DataAccess,
			&i.LinkedGithubOrg,
			&i.DisplayMembers,
			&i.TranscriptDeletionPolicy,
			&i.Role,
			&i.MemberSince,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const searchCollectives = `-- name: SearchCollectives :many
SELECT g.id, g.name, g.description, g.linked_github_org,
       COUNT(DISTINCT gm.user_id)::int AS member_count,
       COUNT(DISTINCT CASE WHEN ts.status = 'approved' THEN ts.transcript_id END)::int AS transcript_count
FROM groups g
LEFT JOIN group_members gm ON g.id = gm.group_id
LEFT JOIN transcript_shares ts ON g.id = ts.group_id
WHERE (
        g.name ILIKE '%' || $1 || '%'
        OR g.description ILIKE '%' || $1 || '%'
        OR g.linked_github_org ILIKE '%' || $1 || '%'
      )
  AND (
        g.data_access = 'public'
        OR g.acceptance_mode = 'open'
        OR EXISTS (
            SELECT 1 FROM group_members gm2
            WHERE gm2.group_id = g.id AND gm2.user_id = $2
        )
      )
GROUP BY g.id
ORDER BY member_count DESC, transcript_count DESC
LIMIT $3
`

type SearchCollectivesParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Limit   int32       `db:"limit" json:"limit"`
}

type SearchCollectivesRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	LinkedGithubOrg pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

// Returns collectives matching the query, filtered to those the caller can see.
// A collective is visible if:
//   - data_access = 'public', OR
//   - acceptance_mode = 'open', OR
//   - the caller (when authenticated) is a member.
//
// $1 = query string (case-insensitive substring match against name/description/linked_github_org).
// $2 = caller user_id (nullable: use NULL for unauthenticated callers).
// $3 = limit.
func (q *Queries) SearchCollectives(ctx context.Context, arg SearchCollectivesParams) ([]SearchCollectivesRow, error) {
	rows, err := q.db.Query(ctx, searchCollectives, arg.Column1, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCollectivesRow{}
	for rows.Next() {
		var i SearchCollectivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.LinkedGithubOrg,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups SET
    name = $2,
    description = $3,
    data_access = $4,
    acceptance_mode = $5,
    linked_github_org = $6,
    display_members = $7,
    transcript_deletion_policy = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, created_by, created_at, updated_at, acceptance_mode, data_access, linked_github_org, display_members, transcript_deletion_policy
`

type UpdateGroupParams struct {
	ID                       pgtype.UUID `db:"id" json:"id"`
	Name                     string      `db:"name" json:"name"`
	Description              pgtype.Text `db:"description" json:"description"`
	DataAccess               string      `db:"data_access" json:"data_access"`
	AcceptanceMode           string      `db:"acceptance_mode" json:"acceptance_mode"`
	LinkedGithubOrg          pgtype.Text `db:"linked_github_org" json:"linked_github_org"`
	DisplayMembers           bool        `db:"display_members" json:"display_members"`
	TranscriptDeletionPolicy string      `db:"transcript_deletion_policy" json:"transcript_deletion_policy"`
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DataAccess,
		arg.AcceptanceMode,
		arg.LinkedGithubOrg,
		arg.DisplayMembers,
		arg.TranscriptDeletionPolicy,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AcceptanceMode,
		&i.DataAccess,
		&i.LinkedGithubOrg,
		&i.DisplayMembers,
		&i.TranscriptDeletionPolicy,
	)
	return i, err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE group_members SET role = $3 WHERE group_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	UserID  pgtype.UUID `db:"user_id" json:"user_id"`
	Role    string      `db:"role" json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.GroupID, arg.UserID, arg.Role)
	return err
}
