// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Annotation struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	ContentHash         string             `db:"content_hash" json:"content_hash"`
	OwnerID             pgtype.UUID        `db:"owner_id" json:"owner_id"`
	TargetKind          string             `db:"target_kind" json:"target_kind"`
	SessionID           pgtype.Text        `db:"session_id" json:"session_id"`
	EntrySessionID      pgtype.Text        `db:"entry_session_id" json:"entry_session_id"`
	EntryIndex          pgtype.Int4        `db:"entry_index" json:"entry_index"`
	EntryEndIndex       pgtype.Int4        `db:"entry_end_index" json:"entry_end_index"`
	AnnotationID        pgtype.Text        `db:"annotation_id" json:"annotation_id"`
	ProjectHash         pgtype.Text        `db:"project_hash" json:"project_hash"`
	TypeID              string             `db:"type_id" json:"type_id"`
	Value               string             `db:"value" json:"value"`
	IsPrimary           bool               `db:"is_primary" json:"is_primary"`
	Confidence          pgtype.Float8      `db:"confidence" json:"confidence"`
	Reason              pgtype.Text        `db:"reason" json:"reason"`
	AnnotatorName       pgtype.Text        `db:"annotator_name" json:"annotator_name"`
	Provenance          []byte             `db:"provenance" json:"provenance"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AnnotatorKind       pgtype.Text        `db:"annotator_kind" json:"annotator_kind"`
	TargetAssociationID pgtype.Text        `db:"target_association_id" json:"target_association_id"`
	TargetTranscriptID  pgtype.UUID        `db:"target_transcript_id" json:"target_transcript_id"`
}

type ApiKey struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	KeyHash   string             `db:"key_hash" json:"key_hash"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	Label     pgtype.Text        `db:"label" json:"label"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastUsed  pgtype.Timestamptz `db:"last_used" json:"last_used"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
}

type Attestation struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	TranscriptID    pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	AttesterID      pgtype.UUID        `db:"attester_id" json:"attester_id"`
	OrgLogin        string             `db:"org_login" json:"org_login"`
	AttestationType string             `db:"attestation_type" json:"attestation_type"`
	Note            pgtype.Text        `db:"note" json:"note"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type CliAuthSession struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	OauthState   string             `db:"oauth_state" json:"oauth_state"`
	CliPort      int32              `db:"cli_port" json:"cli_port"`
	CliState     string             `db:"cli_state" json:"cli_state"`
	ExchangeCode pgtype.Text        `db:"exchange_code" json:"exchange_code"`
	UserID       pgtype.UUID        `db:"user_id" json:"user_id"`
	Username     pgtype.Text        `db:"username" json:"username"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExchangedAt  pgtype.Timestamptz `db:"exchanged_at" json:"exchanged_at"`
}

type CollectiveRepository struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	GroupID        pgtype.UUID        `db:"group_id" json:"group_id"`
	Owner          string             `db:"owner" json:"owner"`
	Name           string             `db:"name" json:"name"`
	InstallationID int64              `db:"installation_id" json:"installation_id"`
	IsPrivate      bool               `db:"is_private" json:"is_private"`
	LinkedBy       pgtype.UUID        `db:"linked_by" json:"linked_by"`
	CommitsEtag    pgtype.Text        `db:"commits_etag" json:"commits_etag"`
	LastSyncedAt   pgtype.Timestamptz `db:"last_synced_at" json:"last_synced_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type GithubAppInstallation struct {
	InstallationID int64              `db:"installation_id" json:"installation_id"`
	AccountLogin   string             `db:"account_login" json:"account_login"`
	AccountID      int64              `db:"account_id" json:"account_id"`
	AccountType    pgtype.Text        `db:"account_type" json:"account_type"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type GovernanceEventType struct {
	ID          string `db:"id" json:"id"`
	Description string `db:"description" json:"description"`
}

type Group struct {
	ID                       pgtype.UUID        `db:"id" json:"id"`
	Name                     string             `db:"name" json:"name"`
	Description              pgtype.Text        `db:"description" json:"description"`
	CreatedBy                pgtype.UUID        `db:"created_by" json:"created_by"`
	CreatedAt                pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	AcceptanceMode           string             `db:"acceptance_mode" json:"acceptance_mode"`
	DataAccess               string             `db:"data_access" json:"data_access"`
	LinkedGithubOrg          pgtype.Text        `db:"linked_github_org" json:"linked_github_org"`
	DisplayMembers           bool               `db:"display_members" json:"display_members"`
	TranscriptDeletionPolicy string             `db:"transcript_deletion_policy" json:"transcript_deletion_policy"`
}

type GroupMember struct {
	GroupID  pgtype.UUID        `db:"group_id" json:"group_id"`
	UserID   pgtype.UUID        `db:"user_id" json:"user_id"`
	Role     string             `db:"role" json:"role"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joined_at"`
}

type License struct {
	ID                  string `db:"id" json:"id"`
	Name                string `db:"name" json:"name"`
	Url                 string `db:"url" json:"url"`
	AttributionRequired bool   `db:"attribution_required" json:"attribution_required"`
	ShareAlike          bool   `db:"share_alike" json:"share_alike"`
	CommercialOk        bool   `db:"commercial_ok" json:"commercial_ok"`
}

type OwnerOverride struct {
	OwnerID    pgtype.UUID        `db:"owner_id" json:"owner_id"`
	TargetKind string             `db:"target_kind" json:"target_kind"`
	TargetKey  string             `db:"target_key" json:"target_key"`
	Field      string             `db:"field" json:"field"`
	Value      string             `db:"value" json:"value"`
	Provenance []byte             `db:"provenance" json:"provenance"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type RepositoryCommit struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Owner       string             `db:"owner" json:"owner"`
	Name        string             `db:"name" json:"name"`
	Sha         string             `db:"sha" json:"sha"`
	Message     pgtype.Text        `db:"message" json:"message"`
	AuthorName  pgtype.Text        `db:"author_name" json:"author_name"`
	AuthorEmail pgtype.Text        `db:"author_email" json:"author_email"`
	AuthoredAt  pgtype.Timestamptz `db:"authored_at" json:"authored_at"`
	CommittedAt pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	FetchedAt   pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

type Tag struct {
	ID   pgtype.UUID `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
}

type Transcript struct {
	ID                                  pgtype.UUID        `db:"id" json:"id"`
	OwnerID                             pgtype.UUID        `db:"owner_id" json:"owner_id"`
	LocalID                             string             `db:"local_id" json:"local_id"`
	Title                               pgtype.Text        `db:"title" json:"title"`
	Description                         pgtype.Text        `db:"description" json:"description"`
	Visibility                          string             `db:"visibility" json:"visibility"`
	ModelProvider                       string             `db:"model_provider" json:"model_provider"`
	ModelName                           pgtype.Text        `db:"model_name" json:"model_name"`
	HarnessVersion                      pgtype.Text        `db:"harness_version" json:"harness_version"`
	SessionStart                        pgtype.Timestamptz `db:"session_start" json:"session_start"`
	SessionEnd                          pgtype.Timestamptz `db:"session_end" json:"session_end"`
	TurnCount                           pgtype.Int4        `db:"turn_count" json:"turn_count"`
	TokenCount                          pgtype.Int4        `db:"token_count" json:"token_count"`
	BlobKey                             string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes                       pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	SchemaVersion                       string             `db:"schema_version" json:"schema_version"`
	PublishedAt                         pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UpdatedAt                           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ParentSessionID                     pgtype.Text        `db:"parent_session_id" json:"parent_session_id"`
	IngestedAt                          pgtype.Timestamptz `db:"ingested_at" json:"ingested_at"`
	SourceFilePath                      pgtype.Text        `db:"source_file_path" json:"source_file_path"`
	SourceFormat                        pgtype.Text        `db:"source_format" json:"source_format"`
	GitBranch                           pgtype.Text        `db:"git_branch" json:"git_branch"`
	GitRemote                           pgtype.Text        `db:"git_remote" json:"git_remote"`
	GitWorktree                         pgtype.Text        `db:"git_worktree" json:"git_worktree"`
	ProjectHash                         string             `db:"project_hash" json:"project_hash"`
	ProjectPath                         pgtype.Text        `db:"project_path" json:"project_path"`
	ProjectName                         pgtype.Text        `db:"project_name" json:"project_name"`
	ToolCallCount                       pgtype.Int4        `db:"tool_call_count" json:"tool_call_count"`
	SubagentCount                       pgtype.Int4        `db:"subagent_count" json:"subagent_count"`
	DurationMs                          pgtype.Int8        `db:"duration_ms" json:"duration_ms"`
	Subagents                           []byte             `db:"subagents" json:"subagents"`
	DiagnosticsWarnings                 []byte             `db:"diagnostics_warnings" json:"diagnostics_warnings"`
	DiagnosticsPartial                  pgtype.Bool        `db:"diagnostics_partial" json:"diagnostics_partial"`
	TokensIn                            pgtype.Int8        `db:"tokens_in" json:"tokens_in"`
	TokensOut                           pgtype.Int8        `db:"tokens_out" json:"tokens_out"`
	TitleGenerated                      pgtype.Text        `db:"title_generated" json:"title_generated"`
	Outcome                             pgtype.Text        `db:"outcome" json:"outcome"`
	FilesTouched                        pgtype.Int4        `db:"files_touched" json:"files_touched"`
	LinesChanged                        pgtype.Int4        `db:"lines_changed" json:"lines_changed"`
	RetryLoops                          pgtype.Int4        `db:"retry_loops" json:"retry_loops"`
	RetryTokensWasted                   pgtype.Int4        `db:"retry_tokens_wasted" json:"retry_tokens_wasted"`
	WithinSessionReverts                pgtype.Int4        `db:"within_session_reverts" json:"within_session_reverts"`
	SignalDensity                       pgtype.Float4      `db:"signal_density" json:"signal_density"`
	SpecQualityScore                    pgtype.Float4      `db:"spec_quality_score" json:"spec_quality_score"`
	ExplorationRatio                    pgtype.Float4      `db:"exploration_ratio" json:"exploration_ratio"`
	ScopeBreadth                        pgtype.Int4        `db:"scope_breadth" json:"scope_breadth"`
	DiscoveryTurns                      pgtype.Int4        `db:"discovery_turns" json:"discovery_turns"`
	M2TokenOutcomeRatio                 pgtype.Float4      `db:"m2_token_outcome_ratio" json:"m2_token_outcome_ratio"`
	M3UniqueToolCount                   pgtype.Int4        `db:"m3_unique_tool_count" json:"m3_unique_tool_count"`
	M4ErrorRecoveryCount                pgtype.Int4        `db:"m4_error_recovery_count" json:"m4_error_recovery_count"`
	M4ConsecutiveErrorMax               pgtype.Int4        `db:"m4_consecutive_error_max" json:"m4_consecutive_error_max"`
	M5ContextUtilizationPct             pgtype.Float4      `db:"m5_context_utilization_pct" json:"m5_context_utilization_pct"`
	M5PeakContextTokens                 pgtype.Int4        `db:"m5_peak_context_tokens" json:"m5_peak_context_tokens"`
	M5AvgMessageTokens                  pgtype.Int4        `db:"m5_avg_message_tokens" json:"m5_avg_message_tokens"`
	M6OutputSurvivalPct                 pgtype.Float4      `db:"m6_output_survival_pct" json:"m6_output_survival_pct"`
	M6LinesSurvived                     pgtype.Int4        `db:"m6_lines_survived" json:"m6_lines_survived"`
	M6LinesTotal                        pgtype.Int4        `db:"m6_lines_total" json:"m6_lines_total"`
	M7SpecWordCount                     pgtype.Int4        `db:"m7_spec_word_count" json:"m7_spec_word_count"`
	M7SpecHasExamples                   pgtype.Bool        `db:"m7_spec_has_examples" json:"m7_spec_has_examples"`
	M7SpecHasConstraints                pgtype.Bool        `db:"m7_spec_has_constraints" json:"m7_spec_has_constraints"`
	ComputedAt                          pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
	ComputeVersion                      pgtype.Int4        `db:"compute_version" json:"compute_version"`
	ContentHash                         pgtype.Text        `db:"content_hash" json:"content_hash"`
	LicenseID                           pgtype.Text        `db:"license_id" json:"license_id"`
	WrappedDataKey                      []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm                 string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion                          int32              `db:"key_version" json:"key_version"`
	AcceptedRequestOperationFingerprint pgtype.Text        `db:"accepted_request_operation_fingerprint" json:"accepted_request_operation_fingerprint"`
	SessionOrigin                       string             `db:"session_origin" json:"session_origin"`
}

type TranscriptAssociation struct {
	OwnerID           pgtype.UUID        `db:"owner_id" json:"owner_id"`
	AssociationID     string             `db:"association_id" json:"association_id"`
	TranscriptID      pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	ObservedCommitSha string             `db:"observed_commit_sha" json:"observed_commit_sha"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TranscriptCommit struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	CommitOrder  int32              `db:"commit_order" json:"commit_order"`
	Sha          string             `db:"sha" json:"sha"`
	Message      pgtype.Text        `db:"message" json:"message"`
	AuthorName   pgtype.Text        `db:"author_name" json:"author_name"`
	AuthorEmail  pgtype.Text        `db:"author_email" json:"author_email"`
	Additions    pgtype.Int4        `db:"additions" json:"additions"`
	Deletions    pgtype.Int4        `db:"deletions" json:"deletions"`
	AuthoredAt   pgtype.Timestamptz `db:"authored_at" json:"authored_at"`
	CommittedAt  pgtype.Timestamptz `db:"committed_at" json:"committed_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type TranscriptGovernanceEventsAudit struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Seq          pgtype.Int8        `db:"seq" json:"seq"`
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	EventType    string             `db:"event_type" json:"event_type"`
	LicenseID    pgtype.Text        `db:"license_id" json:"license_id"`
	Visibility   string             `db:"visibility" json:"visibility"`
	ChangedBy    pgtype.UUID        `db:"changed_by" json:"changed_by"`
	EffectiveAt  pgtype.Timestamptz `db:"effective_at" json:"effective_at"`
}

// DERIVED current-state row, written only by trg_derive_transcript_share from transcript_share_attempts. Application code never writes it. Rebuild with rebuild_transcript_shares(); verify with check_transcript_shares_drift().
type TranscriptShare struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	// The recorded_at of the CURRENT LATEST event for this (transcript, collective) pair - that is, when the submission behind the present state was made. It is NOT the first-ever submission for the pair: a rejected and resubmitted contribution carries the resubmission's time, which is what keeps a moderation queue ordered by genuine age. It is also NOT the approval time; that is decided_at on the underlying event.
	SharedAt pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
	// The current event's status, restricted to the three representable states. A pair whose latest event is retracted or revoked has NO row here at all.
	Status string `db:"status" json:"status"`
}

// The ledger: one row per recorded event in a transcript's relationship with a collective (submitted, decided, withdrawn, removed). transcript_shares is a projection of this table and is reconstructible from it with rebuild_transcript_shares().
type TranscriptShareAttempt struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	// Orders the events within one (transcript, collective) pair, from 1. The highest event_num for a pair is the current one.
	EventNum int32  `db:"event_num" json:"event_num"`
	Status   string `db:"status" json:"status"`
	// When this event was recorded. For a submission that is when it was offered; a later decision on the same event does not change it (decided_at carries that).
	RecordedAt pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
	DecidedAt  pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	DecidedBy  pgtype.UUID        `db:"decided_by" json:"decided_by"`
}

type TranscriptShareDrift struct {
	TranscriptID     pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	GroupID          pgtype.UUID        `db:"group_id" json:"group_id"`
	Problem          string             `db:"problem" json:"problem"`
	StoredStatus     pgtype.Text        `db:"stored_status" json:"stored_status"`
	ExpectedStatus   pgtype.Text        `db:"expected_status" json:"expected_status"`
	StoredSharedAt   pgtype.Timestamptz `db:"stored_shared_at" json:"stored_shared_at"`
	ExpectedSharedAt pgtype.Timestamptz `db:"expected_shared_at" json:"expected_shared_at"`
}

type TranscriptShareExpectedState struct {
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	Status       string             `db:"status" json:"status"`
	SharedAt     pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

type TranscriptShareLatestEvent struct {
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	EventNum     int32              `db:"event_num" json:"event_num"`
	Status       string             `db:"status" json:"status"`
	RecordedAt   pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

type TranscriptTag struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	TagID        pgtype.UUID `db:"tag_id" json:"tag_id"`
}

type User struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	GithubID         int64              `db:"github_id" json:"github_id"`
	GithubUsername   string             `db:"github_username" json:"github_username"`
	DisplayName      pgtype.Text        `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	IsDiscoverable   bool               `db:"is_discoverable" json:"is_discoverable"`
	Provider         string             `db:"provider" json:"provider"`
	ProviderUserID   string             `db:"provider_user_id" json:"provider_user_id"`
	UsernameChosen   bool               `db:"username_chosen" json:"username_chosen"`
	ProviderUsername pgtype.Text        `db:"provider_username" json:"provider_username"`
}

type UserGithubOrg struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	OrgLogin  string             `db:"org_login" json:"org_login"`
	OrgID     int64              `db:"org_id" json:"org_id"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Visible   bool               `db:"visible" json:"visible"`
	FetchedAt pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}
