// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: origin_backfill.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndSwapTranscriptSessionOrigin = `-- name: CompareAndSwapTranscriptSessionOrigin :execrows
UPDATE transcripts
SET session_origin = $1,
    updated_at = now()
WHERE id = $2
  AND session_origin = $3
  AND updated_at = $4
`

type CompareAndSwapTranscriptSessionOriginParams struct {
	SessionOrigin         string             `db:"session_origin" json:"session_origin"`
	ID                    pgtype.UUID        `db:"id" json:"id"`
	ExpectedSessionOrigin string             `db:"expected_session_origin" json:"expected_session_origin"`
	ExpectedUpdatedAt     pgtype.Timestamptz `db:"expected_updated_at" json:"expected_updated_at"`
}

func (q *Queries) CompareAndSwapTranscriptSessionOrigin(ctx context.Context, arg CompareAndSwapTranscriptSessionOriginParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapTranscriptSessionOrigin,
		arg.SessionOrigin,
		arg.ID,
		arg.ExpectedSessionOrigin,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTranscriptOriginBackfillBatch = `-- name: ListTranscriptOriginBackfillBatch :many
SELECT id, session_origin, updated_at,
       blob_key, blob_size_bytes, content_hash, wrapped_data_key,
       encryption_algorithm, key_version
FROM transcripts
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListTranscriptOriginBackfillBatchParams struct {
	AfterID   pgtype.UUID `db:"after_id" json:"after_id"`
	BatchSize int32       `db:"batch_size" json:"batch_size"`
}

type ListTranscriptOriginBackfillBatchRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	SessionOrigin       string             `db:"session_origin" json:"session_origin"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	BlobKey             string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes       pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	ContentHash         pgtype.Text        `db:"content_hash" json:"content_hash"`
	WrappedDataKey      []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion          int32              `db:"key_version" json:"key_version"`
}

func (q *Queries) ListTranscriptOriginBackfillBatch(ctx context.Context, arg ListTranscriptOriginBackfillBatchParams) ([]ListTranscriptOriginBackfillBatchRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptOriginBackfillBatch, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptOriginBackfillBatchRow{}
	for rows.Next() {
		var i ListTranscriptOriginBackfillBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionOrigin,
			&i.UpdatedAt,
			&i.BlobKey,
			&i.BlobSizeBytes,
			&i.ContentHash,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
