// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner_overrides.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOwnerOverride = `-- name: DeleteOwnerOverride :execrows
DELETE FROM owner_overrides
WHERE owner_id = $1
  AND target_kind = $2
  AND target_key = $3
  AND field = $4
`

type DeleteOwnerOverrideParams struct {
	OwnerID    pgtype.UUID `db:"owner_id" json:"owner_id"`
	TargetKind string      `db:"target_kind" json:"target_kind"`
	TargetKey  string      `db:"target_key" json:"target_key"`
	Field      string      `db:"field" json:"field"`
}

// Returns the affected row count so the caller can tell "the correction was
// removed" from "there was no correction to remove" without a preceding read.
func (q *Queries) DeleteOwnerOverride(ctx context.Context, arg DeleteOwnerOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOwnerOverride,
		arg.OwnerID,
		arg.TargetKind,
		arg.TargetKey,
		arg.Field,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOwnerOverride = `-- name: GetOwnerOverride :one
SELECT owner_id, target_kind, target_key, field, value, provenance, created_at, updated_at
FROM owner_overrides
WHERE owner_id = $1
  AND target_kind = $2
  AND target_key = $3
  AND field = $4
`

type GetOwnerOverrideParams struct {
	OwnerID    pgtype.UUID `db:"owner_id" json:"owner_id"`
	TargetKind string      `db:"target_kind" json:"target_kind"`
	TargetKey  string      `db:"target_key" json:"target_key"`
	Field      string      `db:"field" json:"field"`
}

func (q *Queries) GetOwnerOverride(ctx context.Context, arg GetOwnerOverrideParams) (OwnerOverride, error) {
	row := q.db.QueryRow(ctx, getOwnerOverride,
		arg.OwnerID,
		arg.TargetKind,
		arg.TargetKey,
		arg.Field,
	)
	var i OwnerOverride
	err := row.Scan(
		&i.OwnerID,
		&i.TargetKind,
		&i.TargetKey,
		&i.Field,
		&i.Value,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOwnerOverride = `-- name: UpsertOwnerOverride :one

INSERT INTO owner_overrides (owner_id, target_kind, target_key, field, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, target_kind, target_key, field)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING owner_id, target_kind, target_key, field, value, provenance, created_at, updated_at
`

type UpsertOwnerOverrideParams struct {
	OwnerID    pgtype.UUID `db:"owner_id" json:"owner_id"`
	TargetKind string      `db:"target_kind" json:"target_kind"`
	TargetKey  string      `db:"target_key" json:"target_key"`
	Field      string      `db:"field" json:"field"`
	Value      string      `db:"value" json:"value"`
}

// Owner corrections to derived, published metadata.
//
// Every statement here is pinned to one (target_kind, field) pair supplied by the
// caller. The table's CHECK constraints hold the full RESERVED menus so a later
// field is a code change rather than a migration; narrowing those menus to the one
// pair the application actually implements today is the handler's typed enum, not a
// second database constraint. That is why these statements take the kind and the
// field as parameters instead of hard-coding them: the closed set lives in exactly
// one place in Go.
//
// target_key is untyped TEXT by design — a project's key is its 64-hex hash, a
// transcript's would be a UUID — so the caller validates the key's shape for the
// kind it is writing before it gets here.
func (q *Queries) UpsertOwnerOverride(ctx context.Context, arg UpsertOwnerOverrideParams) (OwnerOverride, error) {
	row := q.db.QueryRow(ctx, upsertOwnerOverride,
		arg.OwnerID,
		arg.TargetKind,
		arg.TargetKey,
		arg.Field,
		arg.Value,
	)
	var i OwnerOverride
	err := row.Scan(
		&i.OwnerID,
		&i.TargetKind,
		&i.TargetKey,
		&i.Field,
		&i.Value,
		&i.Provenance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
