// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_request_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPullRequestTranscript = `-- name: AttachPullRequestTranscript :exec
INSERT INTO pull_request_attachment_transcripts (
    attachment_id, transcript_id, position, previous_visibility
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (attachment_id, transcript_id) DO UPDATE SET
    position            = EXCLUDED.position,
    previous_visibility = EXCLUDED.previous_visibility
`

type AttachPullRequestTranscriptParams struct {
	AttachmentID       pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID       pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Position           int32       `db:"position" json:"position"`
	PreviousVisibility string      `db:"previous_visibility" json:"previous_visibility"`
}

// Binds a transcript to an attachment at a position, recording the visibility
// the transcript held before an attach widened it so detach can restore exactly
// that value. Idempotent on the (attachment, transcript) key.
func (q *Queries) AttachPullRequestTranscript(ctx context.Context, arg AttachPullRequestTranscriptParams) error {
	_, err := q.db.Exec(ctx, attachPullRequestTranscript,
		arg.AttachmentID,
		arg.TranscriptID,
		arg.Position,
		arg.PreviousVisibility,
	)
	return err
}

const createPullRequestAttachment = `-- name: CreatePullRequestAttachment :one

INSERT INTO pull_request_attachments (
    repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote,
    author_id, requester_github_id, state, requested_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now()
)
ON CONFLICT (github_repo_id, number) DO UPDATE SET
    repo_owner   = EXCLUDED.repo_owner,
    repo_name    = EXCLUDED.repo_name,
    head_sha     = EXCLUDED.head_sha,
    base_remote  = EXCLUDED.base_remote,
    head_remote  = EXCLUDED.head_remote,
    updated_at   = now()
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at
`

type CreatePullRequestAttachmentParams struct {
	RepoOwner         string      `db:"repo_owner" json:"repo_owner"`
	RepoName          string      `db:"repo_name" json:"repo_name"`
	GithubRepoID      int64       `db:"github_repo_id" json:"github_repo_id"`
	Number            int32       `db:"number" json:"number"`
	HeadSha           string      `db:"head_sha" json:"head_sha"`
	BaseRemote        string      `db:"base_remote" json:"base_remote"`
	HeadRemote        string      `db:"head_remote" json:"head_remote"`
	AuthorID          pgtype.UUID `db:"author_id" json:"author_id"`
	RequesterGithubID pgtype.Int8 `db:"requester_github_id" json:"requester_github_id"`
	State             string      `db:"state" json:"state"`
}

// Pull request prompt-attachment store (migration 037).
//
// `state` is written by exactly one statement, UpdatePullRequestAttachmentState,
// and only from internal/promptattach.Transition, which enforces the closed
// transition table in Go. Every other statement here reads the state or writes
// rows keyed to an already-decided attachment.
// Records (or re-observes) the attachment row for one pull request. A repeated
// observation of the same (github_repo_id, number) refreshes the head and
// remotes it was seen at, but never resets the lifecycle state.
func (q *Queries) CreatePullRequestAttachment(ctx context.Context, arg CreatePullRequestAttachmentParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, createPullRequestAttachment,
		arg.RepoOwner,
		arg.RepoName,
		arg.GithubRepoID,
		arg.Number,
		arg.HeadSha,
		arg.BaseRemote,
		arg.HeadRemote,
		arg.AuthorID,
		arg.RequesterGithubID,
		arg.State,
	)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestAttachment = `-- name: GetPullRequestAttachment :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at FROM pull_request_attachments WHERE id = $1
`

func (q *Queries) GetPullRequestAttachment(ctx context.Context, id pgtype.UUID) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachment, id)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestAttachmentForPull = `-- name: GetPullRequestAttachmentForPull :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at FROM pull_request_attachments
WHERE lower(repo_owner) = lower($1) AND lower(repo_name) = lower($2) AND number = $3
`

type GetPullRequestAttachmentForPullParams struct {
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower_2"`
	Number  int32  `db:"number" json:"number"`
}

// Addresses an attachment the way the routes do: repository owner/name plus the
// pull request number, case-insensitively on the owner and name.
func (q *Queries) GetPullRequestAttachmentForPull(ctx context.Context, arg GetPullRequestAttachmentForPullParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachmentForPull, arg.Lower, arg.Lower_2, arg.Number)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPullRequestAttachmentTranscripts = `-- name: ListPullRequestAttachmentTranscripts :many
SELECT attachment_id, transcript_id, position, previous_visibility FROM pull_request_attachment_transcripts
WHERE attachment_id = $1
ORDER BY position ASC, transcript_id ASC
`

func (q *Queries) ListPullRequestAttachmentTranscripts(ctx context.Context, attachmentID pgtype.UUID) ([]PullRequestAttachmentTranscript, error) {
	rows, err := q.db.Query(ctx, listPullRequestAttachmentTranscripts, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachmentTranscript{}
	for rows.Next() {
		var i PullRequestAttachmentTranscript
		if err := rows.Scan(
			&i.AttachmentID,
			&i.TranscriptID,
			&i.Position,
			&i.PreviousVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePullRequestAttachmentState = `-- name: UpdatePullRequestAttachmentState :one
UPDATE pull_request_attachments
SET state        = $1,
    updated_at   = now(),
    requested_at = CASE WHEN $1 = 'requested' THEN now() ELSE requested_at END,
    waiting_at   = CASE WHEN $1 = 'waiting'   THEN now() ELSE waiting_at   END,
    preview_at   = CASE WHEN $1 = 'preview'   THEN now() ELSE preview_at   END,
    attached_at  = CASE WHEN $1 = 'attached'  THEN now() ELSE attached_at  END,
    detached_at  = CASE WHEN $1 = 'detached'  THEN now() ELSE detached_at  END
WHERE id = $2 AND state = $3
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at
`

type UpdatePullRequestAttachmentStateParams struct {
	State         string      `db:"state" json:"state"`
	ID            pgtype.UUID `db:"id" json:"id"`
	ExpectedState string      `db:"expected_state" json:"expected_state"`
}

// The ONLY statement that changes pull_request_attachments.state. The
// `state = expected_state` predicate makes the write conditional on the state
// the caller read, so a concurrent transition loses cleanly (no row) instead of
// overwriting another move. Stamps the target state's timestamp.
func (q *Queries) UpdatePullRequestAttachmentState(ctx context.Context, arg UpdatePullRequestAttachmentStateParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, updatePullRequestAttachmentState, arg.State, arg.ID, arg.ExpectedState)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
