// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_request_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPullRequestTranscript = `-- name: AttachPullRequestTranscript :exec
INSERT INTO pull_request_attachment_transcripts (
    attachment_id, transcript_id, position, previous_visibility, attach_widened
) VALUES (
    $1, $2, $3, $4, false
)
ON CONFLICT (attachment_id, transcript_id) DO UPDATE SET
    position = EXCLUDED.position
`

type AttachPullRequestTranscriptParams struct {
	AttachmentID       pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID       pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Position           int32       `db:"position" json:"position"`
	PreviousVisibility string      `db:"previous_visibility" json:"previous_visibility"`
}

// Binds a transcript to an attachment at a position, recording the visibility the
// transcript holds when the binding is made. Attaching binds only and never
// changes who can read a transcript, so this, the only application writer of a
// binding, states attach_widened = false as a literal: no caller can create a
// binding that detach would narrow. The true rows are the ones an older attach
// widened (migration 044). Idempotent on the (attachment, transcript) key:
// re-binding updates the position and preserves previous_visibility and
// attach_widened, so a retry can never turn a widened binding into one detach
// leaves alone.
func (q *Queries) AttachPullRequestTranscript(ctx context.Context, arg AttachPullRequestTranscriptParams) error {
	_, err := q.db.Exec(ctx, attachPullRequestTranscript,
		arg.AttachmentID,
		arg.TranscriptID,
		arg.Position,
		arg.PreviousVisibility,
	)
	return err
}

const createPullRequestAttachment = `-- name: CreatePullRequestAttachment :one

INSERT INTO pull_request_attachments (
    group_id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote,
    author_id, requester_github_id, state, requested_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'requested', now()
)
ON CONFLICT (github_repo_id, number) DO UPDATE SET
    repo_owner   = EXCLUDED.repo_owner,
    repo_name    = EXCLUDED.repo_name,
    head_sha     = EXCLUDED.head_sha,
    base_remote  = EXCLUDED.base_remote,
    head_remote  = EXCLUDED.head_remote,
    updated_at   = now()
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type CreatePullRequestAttachmentParams struct {
	GroupID           pgtype.UUID `db:"group_id" json:"group_id"`
	RepoOwner         string      `db:"repo_owner" json:"repo_owner"`
	RepoName          string      `db:"repo_name" json:"repo_name"`
	GithubRepoID      int64       `db:"github_repo_id" json:"github_repo_id"`
	Number            int32       `db:"number" json:"number"`
	HeadSha           string      `db:"head_sha" json:"head_sha"`
	BaseRemote        string      `db:"base_remote" json:"base_remote"`
	HeadRemote        string      `db:"head_remote" json:"head_remote"`
	AuthorID          pgtype.UUID `db:"author_id" json:"author_id"`
	RequesterGithubID pgtype.Int8 `db:"requester_github_id" json:"requester_github_id"`
}

// Pull request prompt-attachment store (migration 037).
//
// `state` is written by exactly one statement, UpdatePullRequestAttachmentState,
// and only from internal/promptattach.Transition, which enforces the closed
// transition table in Go. Every other statement here reads the state or writes
// rows keyed to an already-decided attachment.
// Records (or re-observes) the attachment row for one pull request, bound to the
// collective whose link enabled it. Creation initialises the closed lifecycle at
// 'requested' with its timestamp; every later move goes through the Go
// transition function. A repeated observation of the same (github_repo_id,
// number) refreshes the head and remotes it was seen at, but never resets the
// lifecycle state and never re-binds the collective: consent belongs to the
// collective that first enabled the attachment.
func (q *Queries) CreatePullRequestAttachment(ctx context.Context, arg CreatePullRequestAttachmentParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, createPullRequestAttachment,
		arg.GroupID,
		arg.RepoOwner,
		arg.RepoName,
		arg.GithubRepoID,
		arg.Number,
		arg.HeadSha,
		arg.BaseRemote,
		arg.HeadRemote,
		arg.AuthorID,
		arg.RequesterGithubID,
	)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const deletePullRequestAttachmentTranscript = `-- name: DeletePullRequestAttachmentTranscript :exec
DELETE FROM pull_request_attachment_transcripts
WHERE attachment_id = $1 AND transcript_id = $2
`

type DeletePullRequestAttachmentTranscriptParams struct {
	AttachmentID pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// Removes one binding that an attach which never completed made.
func (q *Queries) DeletePullRequestAttachmentTranscript(ctx context.Context, arg DeletePullRequestAttachmentTranscriptParams) error {
	_, err := q.db.Exec(ctx, deletePullRequestAttachmentTranscript, arg.AttachmentID, arg.TranscriptID)
	return err
}

const deletePullRequestAttachmentTranscripts = `-- name: DeletePullRequestAttachmentTranscripts :exec
DELETE FROM pull_request_attachment_transcripts WHERE attachment_id = $1
`

// Clears the bindings an earlier cycle left when a new attach begins. Detach
// keeps its bindings, so a detached pull request still lists the transcripts it
// held; the next attach binds afresh and records the visibility that is true at
// that time rather than a snapshot from a cycle that is over. The caller
// releases any binding an older attach widened before clearing it.
func (q *Queries) DeletePullRequestAttachmentTranscripts(ctx context.Context, attachmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePullRequestAttachmentTranscripts, attachmentID)
	return err
}

const getPullRequestAttachment = `-- name: GetPullRequestAttachment :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments WHERE id = $1
`

func (q *Queries) GetPullRequestAttachment(ctx context.Context, id pgtype.UUID) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachment, id)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getPullRequestAttachmentForPull = `-- name: GetPullRequestAttachmentForPull :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE lower(repo_owner) = lower($1) AND lower(repo_name) = lower($2) AND number = $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetPullRequestAttachmentForPullParams struct {
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower_2"`
	Number  int32  `db:"number" json:"number"`
}

// Addresses an attachment the way the routes do: repository owner/name plus the
// pull request number, case-insensitively on the owner and name.
func (q *Queries) GetPullRequestAttachmentForPull(ctx context.Context, arg GetPullRequestAttachmentForPullParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachmentForPull, arg.Lower, arg.Lower_2, arg.Number)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getPullRequestAttachmentTranscript = `-- name: GetPullRequestAttachmentTranscript :one
SELECT attachment_id, transcript_id, position, previous_visibility, attach_widened FROM pull_request_attachment_transcripts
WHERE attachment_id = $1 AND transcript_id = $2
`

type GetPullRequestAttachmentTranscriptParams struct {
	AttachmentID pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// One binding, re-read under the transcript publish lock before releasing
// a visibility change made by an older attach.
func (q *Queries) GetPullRequestAttachmentTranscript(ctx context.Context, arg GetPullRequestAttachmentTranscriptParams) (PullRequestAttachmentTranscript, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachmentTranscript, arg.AttachmentID, arg.TranscriptID)
	var i PullRequestAttachmentTranscript
	err := row.Scan(
		&i.AttachmentID,
		&i.TranscriptID,
		&i.Position,
		&i.PreviousVisibility,
		&i.AttachWidened,
	)
	return i, err
}

const listAttachedPullRequestCandidatesByGroup = `-- name: ListAttachedPullRequestCandidatesByGroup :many
SELECT pt.transcript_id,
       a.repo_owner, a.repo_name, a.number, a.state, a.author_id,
       cr.installation_id,
       cr.is_private,
       (gm.user_id IS NOT NULL)::boolean AS viewer_is_member
FROM transcript_shares ts
JOIN pull_request_attachment_transcripts pt ON pt.transcript_id = ts.transcript_id
JOIN pull_request_attachments a ON a.id = pt.attachment_id
JOIN collective_repositories cr
  ON cr.group_id = a.group_id
 AND lower(cr.owner) = lower(a.repo_owner)
 AND lower(cr.name) = lower(a.repo_name)
LEFT JOIN group_members gm
  ON gm.group_id = a.group_id
 AND gm.user_id = $1::uuid
 AND gm.role <> 'pending'
WHERE ts.group_id = $2
  AND ts.status = 'approved'
  AND a.state = 'attached'
ORDER BY a.id, pt.transcript_id
`

type ListAttachedPullRequestCandidatesByGroupParams struct {
	ViewerID pgtype.UUID `db:"viewer_id" json:"viewer_id"`
	GroupID  pgtype.UUID `db:"group_id" json:"group_id"`
}

type ListAttachedPullRequestCandidatesByGroupRow struct {
	TranscriptID   pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	RepoOwner      string      `db:"repo_owner" json:"repo_owner"`
	RepoName       string      `db:"repo_name" json:"repo_name"`
	Number         int32       `db:"number" json:"number"`
	State          string      `db:"state" json:"state"`
	AuthorID       pgtype.UUID `db:"author_id" json:"author_id"`
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	IsPrivate      bool        `db:"is_private" json:"is_private"`
	ViewerIsMember bool        `db:"viewer_is_member" json:"viewer_is_member"`
}

// The attached pull requests bound to a transcript a collective counts: the
// transcripts with an approved share to it, which is the set
// GetGroupTranscriptStats totals.
func (q *Queries) ListAttachedPullRequestCandidatesByGroup(ctx context.Context, arg ListAttachedPullRequestCandidatesByGroupParams) ([]ListAttachedPullRequestCandidatesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listAttachedPullRequestCandidatesByGroup, arg.ViewerID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachedPullRequestCandidatesByGroupRow{}
	for rows.Next() {
		var i ListAttachedPullRequestCandidatesByGroupRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.State,
			&i.AuthorID,
			&i.InstallationID,
			&i.IsPrivate,
			&i.ViewerIsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachedPullRequestCandidatesByOwner = `-- name: ListAttachedPullRequestCandidatesByOwner :many
SELECT pt.transcript_id,
       a.repo_owner, a.repo_name, a.number, a.state, a.author_id,
       cr.installation_id,
       cr.is_private,
       (gm.user_id IS NOT NULL)::boolean AS viewer_is_member
FROM transcripts t
JOIN pull_request_attachment_transcripts pt ON pt.transcript_id = t.id
JOIN pull_request_attachments a ON a.id = pt.attachment_id
JOIN collective_repositories cr
  ON cr.group_id = a.group_id
 AND lower(cr.owner) = lower(a.repo_owner)
 AND lower(cr.name) = lower(a.repo_name)
LEFT JOIN group_members gm
  ON gm.group_id = a.group_id
 AND gm.user_id = $1::uuid
 AND gm.role <> 'pending'
WHERE t.owner_id = $2
  AND a.state = 'attached'
ORDER BY a.id, pt.transcript_id
`

type ListAttachedPullRequestCandidatesByOwnerParams struct {
	ViewerID pgtype.UUID `db:"viewer_id" json:"viewer_id"`
	OwnerID  pgtype.UUID `db:"owner_id" json:"owner_id"`
}

type ListAttachedPullRequestCandidatesByOwnerRow struct {
	TranscriptID   pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	RepoOwner      string      `db:"repo_owner" json:"repo_owner"`
	RepoName       string      `db:"repo_name" json:"repo_name"`
	Number         int32       `db:"number" json:"number"`
	State          string      `db:"state" json:"state"`
	AuthorID       pgtype.UUID `db:"author_id" json:"author_id"`
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	IsPrivate      bool        `db:"is_private" json:"is_private"`
	ViewerIsMember bool        `db:"viewer_is_member" json:"viewer_is_member"`
}

// The attached pull requests bound to any transcript one person published, for
// their own totals.
func (q *Queries) ListAttachedPullRequestCandidatesByOwner(ctx context.Context, arg ListAttachedPullRequestCandidatesByOwnerParams) ([]ListAttachedPullRequestCandidatesByOwnerRow, error) {
	rows, err := q.db.Query(ctx, listAttachedPullRequestCandidatesByOwner, arg.ViewerID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachedPullRequestCandidatesByOwnerRow{}
	for rows.Next() {
		var i ListAttachedPullRequestCandidatesByOwnerRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.State,
			&i.AuthorID,
			&i.InstallationID,
			&i.IsPrivate,
			&i.ViewerIsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsBindingTranscript = `-- name: ListAttachmentsBindingTranscript :many
SELECT a.id, a.repo_owner, a.repo_name, a.github_repo_id, a.number, a.head_sha, a.base_remote, a.head_remote, a.author_id, a.requester_github_id, a.state, a.comment_id, a.check_run_id, a.digest, a.requested_at, a.waiting_at, a.preview_at, a.attached_at, a.detached_at, a.created_at, a.updated_at, a.group_id FROM pull_request_attachments a
JOIN pull_request_attachment_transcripts pt ON pt.attachment_id = a.id
WHERE pt.transcript_id = $1 AND a.state = 'attached'
ORDER BY a.id ASC
`

// The attachments that bind one transcript. A change to the transcript's
// visibility reads them so a pull request stops listing prompts that are no
// longer public, lists them when they become public, and its check says whether
// anyone besides the author can read what is attached. Only attached
// attachments can be listing anything.
func (q *Queries) ListAttachmentsBindingTranscript(ctx context.Context, transcriptID pgtype.UUID) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsBindingTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsContainingTranscript = `-- name: ListAttachmentsContainingTranscript :many
SELECT a.id, a.repo_owner, a.repo_name, a.github_repo_id, a.number, a.head_sha, a.base_remote, a.head_remote, a.author_id, a.requester_github_id, a.state, a.comment_id, a.check_run_id, a.digest, a.requested_at, a.waiting_at, a.preview_at, a.attached_at, a.detached_at, a.created_at, a.updated_at, a.group_id FROM pull_request_attachments a
WHERE a.author_id = $1
  AND (a.digest->'items' @> jsonb_build_array(jsonb_build_object('transcriptId', $2::text))
    OR EXISTS (SELECT 1 FROM pull_request_attachment_transcripts pt
      WHERE pt.attachment_id = a.id AND pt.transcript_id = $2::uuid))
ORDER BY a.id FOR UPDATE
`

type ListAttachmentsContainingTranscriptParams struct {
	OwnerID      pgtype.UUID `db:"owner_id" json:"owner_id"`
	TranscriptID string      `db:"transcript_id" json:"transcript_id"`
}

// Deletion must prune derived prompt copies, including unbound previews and
// detached digests. Lock rows so pruning and row removal commit together.
func (q *Queries) ListAttachmentsContainingTranscript(ctx context.Context, arg ListAttachmentsContainingTranscriptParams) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsContainingTranscript, arg.OwnerID, arg.TranscriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsForCollectiveGrants = `-- name: ListAttachmentsForCollectiveGrants :many
SELECT DISTINCT a.id, a.repo_owner, a.repo_name, a.github_repo_id, a.number, a.head_sha, a.base_remote, a.head_remote, a.author_id, a.requester_github_id, a.state, a.comment_id, a.check_run_id, a.digest, a.requested_at, a.waiting_at, a.preview_at, a.attached_at, a.detached_at, a.created_at, a.updated_at, a.group_id FROM pull_request_attachments a
JOIN pull_request_attachment_transcripts pt ON pt.attachment_id = a.id
JOIN transcript_shares ts ON ts.transcript_id = pt.transcript_id
WHERE ts.group_id = $1 AND a.state = 'attached'
ORDER BY a.id
`

// Membership changes can alter a bound transcript's readers without changing
// its visibility. Read affected attachments before removing any share rows.
func (q *Queries) ListAttachmentsForCollectiveGrants(ctx context.Context, groupID pgtype.UUID) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForCollectiveGrants, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorAttachmentsForRepo = `-- name: ListAuthorAttachmentsForRepo :many
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE author_id = $1
  AND lower(repo_name) = lower($2)
  AND state = ANY($3::text[])
ORDER BY updated_at ASC, id ASC
`

type ListAuthorAttachmentsForRepoParams struct {
	AuthorID pgtype.UUID `db:"author_id" json:"author_id"`
	RepoName string      `db:"repo_name" json:"repo_name"`
	States   []string    `db:"states" json:"states"`
}

// The author's attachments for one repository name in the states a publish can
// move: a waiting request it can complete, or an attached one it can refresh.
// Matched on the repository NAME, and never the owner: reponame.NormalizeRemote
// reduces a remote to its last path segment, and a fork's clone keeps that name
// while its owner changes, so the name is what makes a fork push match its
// attachment at all. The matcher applies the same equality.
//
// idx_pull_request_attachments_author_repo_name serves this predicate; the
// (repo_owner, repo_name) index cannot, because it leads with a column this WHERE
// never constrains, and the state is filtered rather than indexed.
func (q *Queries) ListAuthorAttachmentsForRepo(ctx context.Context, arg ListAuthorAttachmentsForRepoParams) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAuthorAttachmentsForRepo, arg.AuthorID, arg.RepoName, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorWaitingPromptRequests = `-- name: ListAuthorWaitingPromptRequests :many
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE author_id = $1 AND state = 'waiting'
ORDER BY requested_at ASC NULLS LAST, updated_at ASC, id ASC
`

// The prompt requests waiting on one author, oldest first, for
// GET /users/me/prompt-requests. A waiting attachment is one a non-author asked
// for and no matching publish has completed yet.
func (q *Queries) ListAuthorWaitingPromptRequests(ctx context.Context, authorID pgtype.UUID) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAuthorWaitingPromptRequests, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveOwnedDigestTranscripts = `-- name: ListLiveOwnedDigestTranscripts :many
SELECT id FROM transcripts WHERE owner_id = $1 AND id = ANY($2::uuid[])
`

type ListLiveOwnedDigestTranscriptsParams struct {
	OwnerID       pgtype.UUID   `db:"owner_id" json:"owner_id"`
	TranscriptIds []pgtype.UUID `db:"transcript_ids" json:"transcript_ids"`
}

func (q *Queries) ListLiveOwnedDigestTranscripts(ctx context.Context, arg ListLiveOwnedDigestTranscriptsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listLiveOwnedDigestTranscripts, arg.OwnerID, arg.TranscriptIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestAttachmentTranscriptSummaries = `-- name: ListPullRequestAttachmentTranscriptSummaries :many
SELECT pt.transcript_id, pt.position, pt.previous_visibility, t.title, t.session_start, t.owner_id, t.visibility
FROM pull_request_attachment_transcripts pt
JOIN transcripts t ON t.id = pt.transcript_id
WHERE pt.attachment_id = $1
ORDER BY pt.position ASC, pt.transcript_id ASC
`

type ListPullRequestAttachmentTranscriptSummariesRow struct {
	TranscriptID       pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	Position           int32              `db:"position" json:"position"`
	PreviousVisibility string             `db:"previous_visibility" json:"previous_visibility"`
	Title              pgtype.Text        `db:"title" json:"title"`
	SessionStart       pgtype.Timestamptz `db:"session_start" json:"session_start"`
	OwnerID            pgtype.UUID        `db:"owner_id" json:"owner_id"`
	Visibility         string             `db:"visibility" json:"visibility"`
}

// The transcripts one attachment holds, with the fields the response shows, in
// attachment order. Reads the binding and the transcript together so the caller
// does not stitch two queries per row.
func (q *Queries) ListPullRequestAttachmentTranscriptSummaries(ctx context.Context, attachmentID pgtype.UUID) ([]ListPullRequestAttachmentTranscriptSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestAttachmentTranscriptSummaries, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullRequestAttachmentTranscriptSummariesRow{}
	for rows.Next() {
		var i ListPullRequestAttachmentTranscriptSummariesRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.Position,
			&i.PreviousVisibility,
			&i.Title,
			&i.SessionStart,
			&i.OwnerID,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestAttachmentTranscripts = `-- name: ListPullRequestAttachmentTranscripts :many
SELECT attachment_id, transcript_id, position, previous_visibility, attach_widened FROM pull_request_attachment_transcripts
WHERE attachment_id = $1
ORDER BY position ASC, transcript_id ASC
`

func (q *Queries) ListPullRequestAttachmentTranscripts(ctx context.Context, attachmentID pgtype.UUID) ([]PullRequestAttachmentTranscript, error) {
	rows, err := q.db.Query(ctx, listPullRequestAttachmentTranscripts, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachmentTranscript{}
	for rows.Next() {
		var i PullRequestAttachmentTranscript
		if err := rows.Scan(
			&i.AttachmentID,
			&i.TranscriptID,
			&i.Position,
			&i.PreviousVisibility,
			&i.AttachWidened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestCandidatesByTranscripts = `-- name: ListPullRequestCandidatesByTranscripts :many
SELECT pt.transcript_id,
       a.repo_owner, a.repo_name, a.number, a.state, a.author_id,
       cr.installation_id,
       cr.is_private,
       (gm.user_id IS NOT NULL)::boolean AS viewer_is_member
FROM pull_request_attachment_transcripts pt
JOIN pull_request_attachments a ON a.id = pt.attachment_id
JOIN collective_repositories cr
  ON cr.group_id = a.group_id
 AND lower(cr.owner) = lower(a.repo_owner)
 AND lower(cr.name) = lower(a.repo_name)
LEFT JOIN group_members gm
  ON gm.group_id = a.group_id
 AND gm.user_id = $1::uuid
 AND gm.role <> 'pending'
WHERE pt.transcript_id = ANY($2::uuid[])
  AND a.state = ANY($3::text[])
ORDER BY pt.transcript_id,
         GREATEST(a.attached_at, a.detached_at) DESC NULLS LAST,
         lower(a.repo_owner), lower(a.repo_name), a.number, a.id
`

type ListPullRequestCandidatesByTranscriptsParams struct {
	ViewerID      pgtype.UUID   `db:"viewer_id" json:"viewer_id"`
	TranscriptIds []pgtype.UUID `db:"transcript_ids" json:"transcript_ids"`
	States        []string      `db:"states" json:"states"`
}

type ListPullRequestCandidatesByTranscriptsRow struct {
	TranscriptID   pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	RepoOwner      string      `db:"repo_owner" json:"repo_owner"`
	RepoName       string      `db:"repo_name" json:"repo_name"`
	Number         int32       `db:"number" json:"number"`
	State          string      `db:"state" json:"state"`
	AuthorID       pgtype.UUID `db:"author_id" json:"author_id"`
	InstallationID int64       `db:"installation_id" json:"installation_id"`
	IsPrivate      bool        `db:"is_private" json:"is_private"`
	ViewerIsMember bool        `db:"viewer_is_member" json:"viewer_is_member"`
}

// The pull requests bound to a page of transcripts, in the requested states.
//
// This and the two statements after it are the one candidate read behind every
// pull request a reader is shown: the transcript's pull request list, the
// summary on a list row, the collective's count, and the caller's own count.
// Each returns one row per (transcript, attachment) binding with the repository
// link the attachment's collective holds now and whether the viewer is a member
// of that collective. The visibility rule itself is applied in Go
// (pullRequestReadable), in the one place all four reads share, rather than
// copied into each statement where the copies could drift apart.
//
// The repository comes from the collective's CURRENT link, exactly as the
// attachment read resolves it, so an attachment whose collective is gone or
// whose repository is no longer linked has no row: its visibility check cannot
// complete, and it is omitted rather than guessed. A pending join request is not
// membership. Each is one statement for the whole page or the whole scope, never
// one per row.
//
// Only what the rule and the served rows need is selected - the pull request,
// its state and author, and the repository link - never the attachment row
// whole: its stored digest holds prompt text none of these reads serves, and a
// collective's count would otherwise move every digest it binds to produce one
// integer.
//
// idx_pull_request_attachment_transcripts_transcript serves the transcript
// predicate. Rows come newest first within a transcript: by the latest of
// attached_at and detached_at, which for an attached attachment is when it was
// attached.
func (q *Queries) ListPullRequestCandidatesByTranscripts(ctx context.Context, arg ListPullRequestCandidatesByTranscriptsParams) ([]ListPullRequestCandidatesByTranscriptsRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestCandidatesByTranscripts, arg.ViewerID, arg.TranscriptIds, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullRequestCandidatesByTranscriptsRow{}
	for rows.Next() {
		var i ListPullRequestCandidatesByTranscriptsRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.State,
			&i.AuthorID,
			&i.InstallationID,
			&i.IsPrivate,
			&i.ViewerIsMember,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPullRequestAttachmentArtifacts = `-- name: LockPullRequestAttachmentArtifacts :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments WHERE id = $1 FOR UPDATE
`

// Serializes stored prompt copies with transcript deletion's pruning transaction.
func (q *Queries) LockPullRequestAttachmentArtifacts(ctx context.Context, id pgtype.UUID) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, lockPullRequestAttachmentArtifacts, id)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const releasePullRequestAttachmentTranscript = `-- name: ReleasePullRequestAttachmentTranscript :exec
UPDATE pull_request_attachment_transcripts
SET attach_widened = false
WHERE attachment_id = $1 AND transcript_id = $2
`

type ReleasePullRequestAttachmentTranscriptParams struct {
	AttachmentID pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// Records that a detach has undone what an older attach widened for one
// binding. It runs in the transaction that restores the transcript, under the
// transcript's publish lock. The row stays, so the detached pull request still
// lists it, and a later detach of the same binding restores nothing twice.
func (q *Queries) ReleasePullRequestAttachmentTranscript(ctx context.Context, arg ReleasePullRequestAttachmentTranscriptParams) error {
	_, err := q.db.Exec(ctx, releasePullRequestAttachmentTranscript, arg.AttachmentID, arg.TranscriptID)
	return err
}

const setPullRequestAttachmentArtifacts = `-- name: SetPullRequestAttachmentArtifacts :exec
UPDATE pull_request_attachments
SET head_sha     = $1,
    comment_id   = $2,
    check_run_id = $3,
    digest       = $4,
    updated_at   = now()
WHERE id = $5
`

type SetPullRequestAttachmentArtifactsParams struct {
	HeadSha    string      `db:"head_sha" json:"head_sha"`
	CommentID  pgtype.Int8 `db:"comment_id" json:"comment_id"`
	CheckRunID pgtype.Int8 `db:"check_run_id" json:"check_run_id"`
	Digest     []byte      `db:"digest" json:"digest"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

// Records what a preview or an attach posted and against which commit, with the
// digest it computed. head_sha moves when a new head is attached or refreshed;
// comment_id and check_run_id are the GitHub objects a later preview, attach, or
// refresh edits and a detach deletes or resets.
func (q *Queries) SetPullRequestAttachmentArtifacts(ctx context.Context, arg SetPullRequestAttachmentArtifactsParams) error {
	_, err := q.db.Exec(ctx, setPullRequestAttachmentArtifacts,
		arg.HeadSha,
		arg.CommentID,
		arg.CheckRunID,
		arg.Digest,
		arg.ID,
	)
	return err
}

const setPullRequestAttachmentRequester = `-- name: SetPullRequestAttachmentRequester :one
UPDATE pull_request_attachments
SET requester_github_id = $1, updated_at = now()
WHERE id = $2
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type SetPullRequestAttachmentRequesterParams struct {
	RequesterGithubID pgtype.Int8 `db:"requester_github_id" json:"requester_github_id"`
	ID                pgtype.UUID `db:"id" json:"id"`
}

// Records which GitHub account asked the author to attach, so the author's
// request list can say who is waiting on them.
func (q *Queries) SetPullRequestAttachmentRequester(ctx context.Context, arg SetPullRequestAttachmentRequesterParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, setPullRequestAttachmentRequester, arg.RequesterGithubID, arg.ID)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const updatePullRequestAttachmentState = `-- name: UpdatePullRequestAttachmentState :one
UPDATE pull_request_attachments
SET state        = $1,
    updated_at   = now(),
    requested_at = CASE WHEN $1 = 'requested' THEN now() ELSE requested_at END,
    waiting_at   = CASE WHEN $1 = 'waiting'   THEN now() ELSE waiting_at   END,
    preview_at   = CASE WHEN $1 = 'preview'   THEN now() ELSE preview_at   END,
    attached_at  = CASE WHEN $1 = 'attached'  THEN now() ELSE attached_at  END,
    detached_at  = CASE WHEN $1 = 'detached'  THEN now() ELSE detached_at  END
WHERE id = $2 AND state = $3
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type UpdatePullRequestAttachmentStateParams struct {
	State         string      `db:"state" json:"state"`
	ID            pgtype.UUID `db:"id" json:"id"`
	ExpectedState string      `db:"expected_state" json:"expected_state"`
}

// The ONLY statement that changes pull_request_attachments.state. The
// `state = expected_state` predicate makes the write conditional on the state
// the caller read, so a concurrent transition loses cleanly (no row) instead of
// overwriting another move. Stamps the target state's timestamp.
func (q *Queries) UpdatePullRequestAttachmentState(ctx context.Context, arg UpdatePullRequestAttachmentStateParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, updatePullRequestAttachmentState, arg.State, arg.ID, arg.ExpectedState)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
