// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_request_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPullRequestTranscript = `-- name: AttachPullRequestTranscript :exec
INSERT INTO pull_request_attachment_transcripts (
    attachment_id, transcript_id, position, previous_visibility
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (attachment_id, transcript_id) DO UPDATE SET
    position = EXCLUDED.position
`

type AttachPullRequestTranscriptParams struct {
	AttachmentID       pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID       pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Position           int32       `db:"position" json:"position"`
	PreviousVisibility string      `db:"previous_visibility" json:"previous_visibility"`
}

// Binds a transcript to an attachment at a position, recording the visibility the
// transcript held before an attach widened it so detach can restore exactly that
// value. Idempotent on the (attachment, transcript) key: re-binding updates the
// position but PRESERVES the original previous_visibility, because the snapshot
// describes the transcript before the FIRST widening. A refresh or retry after the
// transcript was widened must not overwrite it with the already-widened tier.
func (q *Queries) AttachPullRequestTranscript(ctx context.Context, arg AttachPullRequestTranscriptParams) error {
	_, err := q.db.Exec(ctx, attachPullRequestTranscript,
		arg.AttachmentID,
		arg.TranscriptID,
		arg.Position,
		arg.PreviousVisibility,
	)
	return err
}

const createPullRequestAttachment = `-- name: CreatePullRequestAttachment :one

INSERT INTO pull_request_attachments (
    group_id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote,
    author_id, requester_github_id, state, requested_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'requested', now()
)
ON CONFLICT (github_repo_id, number) DO UPDATE SET
    repo_owner   = EXCLUDED.repo_owner,
    repo_name    = EXCLUDED.repo_name,
    head_sha     = EXCLUDED.head_sha,
    base_remote  = EXCLUDED.base_remote,
    head_remote  = EXCLUDED.head_remote,
    updated_at   = now()
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type CreatePullRequestAttachmentParams struct {
	GroupID           pgtype.UUID `db:"group_id" json:"group_id"`
	RepoOwner         string      `db:"repo_owner" json:"repo_owner"`
	RepoName          string      `db:"repo_name" json:"repo_name"`
	GithubRepoID      int64       `db:"github_repo_id" json:"github_repo_id"`
	Number            int32       `db:"number" json:"number"`
	HeadSha           string      `db:"head_sha" json:"head_sha"`
	BaseRemote        string      `db:"base_remote" json:"base_remote"`
	HeadRemote        string      `db:"head_remote" json:"head_remote"`
	AuthorID          pgtype.UUID `db:"author_id" json:"author_id"`
	RequesterGithubID pgtype.Int8 `db:"requester_github_id" json:"requester_github_id"`
}

// Pull request prompt-attachment store (migration 037).
//
// `state` is written by exactly one statement, UpdatePullRequestAttachmentState,
// and only from internal/promptattach.Transition, which enforces the closed
// transition table in Go. Every other statement here reads the state or writes
// rows keyed to an already-decided attachment.
// Records (or re-observes) the attachment row for one pull request, bound to the
// collective whose link enabled it. Creation initialises the closed lifecycle at
// 'requested' with its timestamp; every later move goes through the Go
// transition function. A repeated observation of the same (github_repo_id,
// number) refreshes the head and remotes it was seen at, but never resets the
// lifecycle state and never re-binds the collective: consent belongs to the
// collective that first enabled the attachment.
func (q *Queries) CreatePullRequestAttachment(ctx context.Context, arg CreatePullRequestAttachmentParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, createPullRequestAttachment,
		arg.GroupID,
		arg.RepoOwner,
		arg.RepoName,
		arg.GithubRepoID,
		arg.Number,
		arg.HeadSha,
		arg.BaseRemote,
		arg.HeadRemote,
		arg.AuthorID,
		arg.RequesterGithubID,
	)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const deletePullRequestAttachmentTranscript = `-- name: DeletePullRequestAttachmentTranscript :exec
DELETE FROM pull_request_attachment_transcripts
WHERE attachment_id = $1 AND transcript_id = $2
`

type DeletePullRequestAttachmentTranscriptParams struct {
	AttachmentID pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// Removes one binding, paired with restoring its recorded visibility.
func (q *Queries) DeletePullRequestAttachmentTranscript(ctx context.Context, arg DeletePullRequestAttachmentTranscriptParams) error {
	_, err := q.db.Exec(ctx, deletePullRequestAttachmentTranscript, arg.AttachmentID, arg.TranscriptID)
	return err
}

const deletePullRequestAttachmentTranscripts = `-- name: DeletePullRequestAttachmentTranscripts :exec
DELETE FROM pull_request_attachment_transcripts WHERE attachment_id = $1
`

// Clears an attachment's transcript bindings. Called after a detach has restored
// each transcript from its recorded previous_visibility, so the next attach
// records the visibility that is true at that time rather than replaying a
// snapshot from a cycle that is over.
func (q *Queries) DeletePullRequestAttachmentTranscripts(ctx context.Context, attachmentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePullRequestAttachmentTranscripts, attachmentID)
	return err
}

const getPullRequestAttachment = `-- name: GetPullRequestAttachment :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments WHERE id = $1
`

func (q *Queries) GetPullRequestAttachment(ctx context.Context, id pgtype.UUID) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachment, id)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getPullRequestAttachmentForPull = `-- name: GetPullRequestAttachmentForPull :one
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE lower(repo_owner) = lower($1) AND lower(repo_name) = lower($2) AND number = $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type GetPullRequestAttachmentForPullParams struct {
	Lower   string `db:"lower" json:"lower"`
	Lower_2 string `db:"lower_2" json:"lower_2"`
	Number  int32  `db:"number" json:"number"`
}

// Addresses an attachment the way the routes do: repository owner/name plus the
// pull request number, case-insensitively on the owner and name.
func (q *Queries) GetPullRequestAttachmentForPull(ctx context.Context, arg GetPullRequestAttachmentForPullParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachmentForPull, arg.Lower, arg.Lower_2, arg.Number)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const getPullRequestAttachmentTranscript = `-- name: GetPullRequestAttachmentTranscript :one
SELECT attachment_id, transcript_id, position, previous_visibility FROM pull_request_attachment_transcripts
WHERE attachment_id = $1 AND transcript_id = $2
`

type GetPullRequestAttachmentTranscriptParams struct {
	AttachmentID pgtype.UUID `db:"attachment_id" json:"attachment_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// One binding, for a compensation that must undo exactly the transcripts one
// attempt widened rather than every binding the attachment holds.
func (q *Queries) GetPullRequestAttachmentTranscript(ctx context.Context, arg GetPullRequestAttachmentTranscriptParams) (PullRequestAttachmentTranscript, error) {
	row := q.db.QueryRow(ctx, getPullRequestAttachmentTranscript, arg.AttachmentID, arg.TranscriptID)
	var i PullRequestAttachmentTranscript
	err := row.Scan(
		&i.AttachmentID,
		&i.TranscriptID,
		&i.Position,
		&i.PreviousVisibility,
	)
	return i, err
}

const listAttachmentsBindingTranscript = `-- name: ListAttachmentsBindingTranscript :many
SELECT a.id, a.repo_owner, a.repo_name, a.github_repo_id, a.number, a.head_sha, a.base_remote, a.head_remote, a.author_id, a.requester_github_id, a.state, a.comment_id, a.check_run_id, a.digest, a.requested_at, a.waiting_at, a.preview_at, a.attached_at, a.detached_at, a.created_at, a.updated_at, a.group_id FROM pull_request_attachments a
JOIN pull_request_attachment_transcripts pt ON pt.attachment_id = a.id
WHERE pt.transcript_id = $1 AND a.state = 'attached'
ORDER BY a.id ASC
`

// The attachments that bind one transcript. The owner's visibility change reads
// them so an attachment stops advertising prompts that are no longer as visible
// as the repository it belongs to requires. Only attached attachments can be
// advertising anything.
func (q *Queries) ListAttachmentsBindingTranscript(ctx context.Context, transcriptID pgtype.UUID) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsBindingTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorAttachmentsForRepo = `-- name: ListAuthorAttachmentsForRepo :many
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE author_id = $1
  AND lower(repo_name) = lower($2)
  AND state = ANY($3::text[])
ORDER BY updated_at ASC, id ASC
`

type ListAuthorAttachmentsForRepoParams struct {
	AuthorID pgtype.UUID `db:"author_id" json:"author_id"`
	RepoName string      `db:"repo_name" json:"repo_name"`
	States   []string    `db:"states" json:"states"`
}

// The author's attachments for one repository name in the states a publish can
// move: a waiting request it can complete, or an attached one it can refresh.
// Matched on the repository NAME, and never the owner: reponame.NormalizeRemote
// reduces a remote to its last path segment, and a fork's clone keeps that name
// while its owner changes, so the name is what makes a fork push match its
// attachment at all. The matcher applies the same equality.
//
// idx_pull_request_attachments_author_repo_name serves this predicate; the
// (repo_owner, repo_name) index cannot, because it leads with a column this WHERE
// never constrains, and the state is filtered rather than indexed.
func (q *Queries) ListAuthorAttachmentsForRepo(ctx context.Context, arg ListAuthorAttachmentsForRepoParams) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAuthorAttachmentsForRepo, arg.AuthorID, arg.RepoName, arg.States)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorWaitingPromptRequests = `-- name: ListAuthorWaitingPromptRequests :many
SELECT id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id FROM pull_request_attachments
WHERE author_id = $1 AND state = 'waiting'
ORDER BY requested_at ASC NULLS LAST, updated_at ASC, id ASC
`

// The prompt requests waiting on one author, oldest first, for
// GET /users/me/prompt-requests. A waiting attachment is one a non-author asked
// for and no matching publish has completed yet.
func (q *Queries) ListAuthorWaitingPromptRequests(ctx context.Context, authorID pgtype.UUID) ([]PullRequestAttachment, error) {
	rows, err := q.db.Query(ctx, listAuthorWaitingPromptRequests, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachment{}
	for rows.Next() {
		var i PullRequestAttachment
		if err := rows.Scan(
			&i.ID,
			&i.RepoOwner,
			&i.RepoName,
			&i.GithubRepoID,
			&i.Number,
			&i.HeadSha,
			&i.BaseRemote,
			&i.HeadRemote,
			&i.AuthorID,
			&i.RequesterGithubID,
			&i.State,
			&i.CommentID,
			&i.CheckRunID,
			&i.Digest,
			&i.RequestedAt,
			&i.WaitingAt,
			&i.PreviewAt,
			&i.AttachedAt,
			&i.DetachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestAttachmentTranscriptSummaries = `-- name: ListPullRequestAttachmentTranscriptSummaries :many
SELECT pt.transcript_id, pt.position, pt.previous_visibility, t.title, t.session_start
FROM pull_request_attachment_transcripts pt
JOIN transcripts t ON t.id = pt.transcript_id
WHERE pt.attachment_id = $1
ORDER BY pt.position ASC, pt.transcript_id ASC
`

type ListPullRequestAttachmentTranscriptSummariesRow struct {
	TranscriptID       pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	Position           int32              `db:"position" json:"position"`
	PreviousVisibility string             `db:"previous_visibility" json:"previous_visibility"`
	Title              pgtype.Text        `db:"title" json:"title"`
	SessionStart       pgtype.Timestamptz `db:"session_start" json:"session_start"`
}

// The transcripts one attachment holds, with the fields the response shows, in
// attachment order. Reads the binding and the transcript together so the caller
// does not stitch two queries per row.
func (q *Queries) ListPullRequestAttachmentTranscriptSummaries(ctx context.Context, attachmentID pgtype.UUID) ([]ListPullRequestAttachmentTranscriptSummariesRow, error) {
	rows, err := q.db.Query(ctx, listPullRequestAttachmentTranscriptSummaries, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullRequestAttachmentTranscriptSummariesRow{}
	for rows.Next() {
		var i ListPullRequestAttachmentTranscriptSummariesRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.Position,
			&i.PreviousVisibility,
			&i.Title,
			&i.SessionStart,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullRequestAttachmentTranscripts = `-- name: ListPullRequestAttachmentTranscripts :many
SELECT attachment_id, transcript_id, position, previous_visibility FROM pull_request_attachment_transcripts
WHERE attachment_id = $1
ORDER BY position ASC, transcript_id ASC
`

func (q *Queries) ListPullRequestAttachmentTranscripts(ctx context.Context, attachmentID pgtype.UUID) ([]PullRequestAttachmentTranscript, error) {
	rows, err := q.db.Query(ctx, listPullRequestAttachmentTranscripts, attachmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PullRequestAttachmentTranscript{}
	for rows.Next() {
		var i PullRequestAttachmentTranscript
		if err := rows.Scan(
			&i.AttachmentID,
			&i.TranscriptID,
			&i.Position,
			&i.PreviousVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPullRequestAttachmentArtifacts = `-- name: SetPullRequestAttachmentArtifacts :exec
UPDATE pull_request_attachments
SET head_sha     = $1,
    comment_id   = $2,
    check_run_id = $3,
    digest       = $4,
    updated_at   = now()
WHERE id = $5
`

type SetPullRequestAttachmentArtifactsParams struct {
	HeadSha    string      `db:"head_sha" json:"head_sha"`
	CommentID  pgtype.Int8 `db:"comment_id" json:"comment_id"`
	CheckRunID pgtype.Int8 `db:"check_run_id" json:"check_run_id"`
	Digest     []byte      `db:"digest" json:"digest"`
	ID         pgtype.UUID `db:"id" json:"id"`
}

// Records what an attach posted and against which commit. head_sha moves when a
// new head is attached or refreshed; comment_id and check_run_id are the GitHub
// objects a later refresh edits and a detach deletes or resets.
func (q *Queries) SetPullRequestAttachmentArtifacts(ctx context.Context, arg SetPullRequestAttachmentArtifactsParams) error {
	_, err := q.db.Exec(ctx, setPullRequestAttachmentArtifacts,
		arg.HeadSha,
		arg.CommentID,
		arg.CheckRunID,
		arg.Digest,
		arg.ID,
	)
	return err
}

const setPullRequestAttachmentDigest = `-- name: SetPullRequestAttachmentDigest :exec
UPDATE pull_request_attachments
SET digest = $1, updated_at = now()
WHERE id = $2
`

type SetPullRequestAttachmentDigestParams struct {
	Digest []byte      `db:"digest" json:"digest"`
	ID     pgtype.UUID `db:"id" json:"id"`
}

// Stores the digest a preview computed without changing the state: a preview
// exposes the digest on the pull request page but shares and posts nothing.
func (q *Queries) SetPullRequestAttachmentDigest(ctx context.Context, arg SetPullRequestAttachmentDigestParams) error {
	_, err := q.db.Exec(ctx, setPullRequestAttachmentDigest, arg.Digest, arg.ID)
	return err
}

const setPullRequestAttachmentRequester = `-- name: SetPullRequestAttachmentRequester :one
UPDATE pull_request_attachments
SET requester_github_id = $1, updated_at = now()
WHERE id = $2
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type SetPullRequestAttachmentRequesterParams struct {
	RequesterGithubID pgtype.Int8 `db:"requester_github_id" json:"requester_github_id"`
	ID                pgtype.UUID `db:"id" json:"id"`
}

// Records which GitHub account asked the author to attach, so the author's
// request list can say who is waiting on them.
func (q *Queries) SetPullRequestAttachmentRequester(ctx context.Context, arg SetPullRequestAttachmentRequesterParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, setPullRequestAttachmentRequester, arg.RequesterGithubID, arg.ID)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}

const updatePullRequestAttachmentState = `-- name: UpdatePullRequestAttachmentState :one
UPDATE pull_request_attachments
SET state        = $1,
    updated_at   = now(),
    requested_at = CASE WHEN $1 = 'requested' THEN now() ELSE requested_at END,
    waiting_at   = CASE WHEN $1 = 'waiting'   THEN now() ELSE waiting_at   END,
    preview_at   = CASE WHEN $1 = 'preview'   THEN now() ELSE preview_at   END,
    attached_at  = CASE WHEN $1 = 'attached'  THEN now() ELSE attached_at  END,
    detached_at  = CASE WHEN $1 = 'detached'  THEN now() ELSE detached_at  END
WHERE id = $2 AND state = $3
RETURNING id, repo_owner, repo_name, github_repo_id, number, head_sha, base_remote, head_remote, author_id, requester_github_id, state, comment_id, check_run_id, digest, requested_at, waiting_at, preview_at, attached_at, detached_at, created_at, updated_at, group_id
`

type UpdatePullRequestAttachmentStateParams struct {
	State         string      `db:"state" json:"state"`
	ID            pgtype.UUID `db:"id" json:"id"`
	ExpectedState string      `db:"expected_state" json:"expected_state"`
}

// The ONLY statement that changes pull_request_attachments.state. The
// `state = expected_state` predicate makes the write conditional on the state
// the caller read, so a concurrent transition loses cleanly (no row) instead of
// overwriting another move. Stamps the target state's timestamp.
func (q *Queries) UpdatePullRequestAttachmentState(ctx context.Context, arg UpdatePullRequestAttachmentStateParams) (PullRequestAttachment, error) {
	row := q.db.QueryRow(ctx, updatePullRequestAttachmentState, arg.State, arg.ID, arg.ExpectedState)
	var i PullRequestAttachment
	err := row.Scan(
		&i.ID,
		&i.RepoOwner,
		&i.RepoName,
		&i.GithubRepoID,
		&i.Number,
		&i.HeadSha,
		&i.BaseRemote,
		&i.HeadRemote,
		&i.AuthorID,
		&i.RequesterGithubID,
		&i.State,
		&i.CommentID,
		&i.CheckRunID,
		&i.Digest,
		&i.RequestedAt,
		&i.WaitingAt,
		&i.PreviewAt,
		&i.AttachedAt,
		&i.DetachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
	)
	return i, err
}
