// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGroupTranscriptStats = `-- name: GetGroupTranscriptStats :one
SELECT
  COUNT(*)::int AS total_transcripts,
  COUNT(DISTINCT t.owner_id)::int AS contributor_count,
  COALESCE(SUM(t.turn_count), 0)::bigint AS total_turns,
  COALESCE(SUM(t.duration_ms), 0)::bigint AS total_duration_ms,
  COALESCE(SUM(COALESCE(t.tokens_in, 0) + COALESCE(t.tokens_out, 0)), 0)::bigint AS total_tokens
FROM transcripts t
JOIN transcript_shares ts ON t.id = ts.transcript_id
WHERE ts.group_id = $1 AND ts.status = 'approved'
`

type GetGroupTranscriptStatsRow struct {
	TotalTranscripts int32 `db:"total_transcripts" json:"total_transcripts"`
	ContributorCount int32 `db:"contributor_count" json:"contributor_count"`
	TotalTurns       int64 `db:"total_turns" json:"total_turns"`
	TotalDurationMs  int64 `db:"total_duration_ms" json:"total_duration_ms"`
	TotalTokens      int64 `db:"total_tokens" json:"total_tokens"`
}

func (q *Queries) GetGroupTranscriptStats(ctx context.Context, groupID pgtype.UUID) (GetGroupTranscriptStatsRow, error) {
	row := q.db.QueryRow(ctx, getGroupTranscriptStats, groupID)
	var i GetGroupTranscriptStatsRow
	err := row.Scan(
		&i.TotalTranscripts,
		&i.ContributorCount,
		&i.TotalTurns,
		&i.TotalDurationMs,
		&i.TotalTokens,
	)
	return i, err
}

const getLatestShareAttempt = `-- name: GetLatestShareAttempt :one
SELECT id, transcript_id, group_id, event_num, status,
       recorded_at, decided_at, decided_by
FROM transcript_share_attempts
WHERE transcript_id = $1 AND group_id = $2
ORDER BY event_num DESC
LIMIT 1
`

type GetLatestShareAttemptParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
}

// The most recent attempt for a (transcript, collective) pair, or no row when
// the transcript was never submitted there. This is what the share path reads
// to tell a genuine re-submission from a duplicate one.
func (q *Queries) GetLatestShareAttempt(ctx context.Context, arg GetLatestShareAttemptParams) (TranscriptShareAttempt, error) {
	row := q.db.QueryRow(ctx, getLatestShareAttempt, arg.TranscriptID, arg.GroupID)
	var i TranscriptShareAttempt
	err := row.Scan(
		&i.ID,
		&i.TranscriptID,
		&i.GroupID,
		&i.EventNum,
		&i.Status,
		&i.RecordedAt,
		&i.DecidedAt,
		&i.DecidedBy,
	)
	return i, err
}

const listGroupContributors = `-- name: ListGroupContributors :many
SELECT u.id, u.github_username, u.avatar_url, COUNT(*)::int AS transcript_count
FROM transcripts t
JOIN transcript_shares ts ON t.id = ts.transcript_id
JOIN users u ON t.owner_id = u.id
WHERE ts.group_id = $1 AND ts.status = 'approved'
  AND (u.is_discoverable = TRUE OR $2::boolean)
GROUP BY u.id, u.github_username, u.avatar_url
ORDER BY transcript_count DESC
`

type ListGroupContributorsParams struct {
	GroupID       pgtype.UUID `db:"group_id" json:"group_id"`
	ViewerIsOwner bool        `db:"viewer_is_owner" json:"viewer_is_owner"`
}

type ListGroupContributorsRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	GithubUsername  string      `db:"github_username" json:"github_username"`
	AvatarUrl       pgtype.Text `db:"avatar_url" json:"avatar_url"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) ListGroupContributors(ctx context.Context, arg ListGroupContributorsParams) ([]ListGroupContributorsRow, error) {
	rows, err := q.db.Query(ctx, listGroupContributors, arg.GroupID, arg.ViewerIsOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupContributorsRow{}
	for rows.Next() {
		var i ListGroupContributorsRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubUsername,
			&i.AvatarUrl,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupModelBreakdown = `-- name: ListGroupModelBreakdown :many
SELECT t.model_provider, COUNT(*)::int AS transcript_count
FROM transcripts t
JOIN transcript_shares ts ON t.id = ts.transcript_id
WHERE ts.group_id = $1 AND ts.status = 'approved'
GROUP BY t.model_provider
ORDER BY transcript_count DESC
`

type ListGroupModelBreakdownRow struct {
	ModelProvider   string `db:"model_provider" json:"model_provider"`
	TranscriptCount int32  `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) ListGroupModelBreakdown(ctx context.Context, groupID pgtype.UUID) ([]ListGroupModelBreakdownRow, error) {
	rows, err := q.db.Query(ctx, listGroupModelBreakdown, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupModelBreakdownRow{}
	for rows.Next() {
		var i ListGroupModelBreakdownRow
		if err := rows.Scan(&i.ModelProvider, &i.TranscriptCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupOwnersForTranscript = `-- name: ListGroupOwnersForTranscript :many
SELECT DISTINCT gm.user_id
FROM transcript_shares ts
JOIN group_members gm ON gm.group_id = ts.group_id
WHERE ts.transcript_id = $1 AND gm.role = 'owner'
`

// Returns the owner user_ids of every collective that has a share row
// (any status) for the given transcript. Used to grant collective owners
// read access on pending submissions before they approve.
func (q *Queries) ListGroupOwnersForTranscript(ctx context.Context, transcriptID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listGroupOwnersForTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupTranscripts = `-- name: ListGroupTranscripts :many

SELECT t.id, t.owner_id, t.local_id, t.title, t.description, t.visibility,
       t.model_provider, t.model_name, t.harness_version, t.session_start, t.session_end,
       t.turn_count, t.token_count, t.blob_key, t.blob_size_bytes, t.schema_version,
       t.published_at, t.updated_at, t.parent_session_id, t.ingested_at,
       t.source_file_path, t.source_format, t.git_branch, t.git_remote, t.git_worktree,
       t.project_hash, t.project_path, t.project_name, t.tool_call_count, t.subagent_count,
       t.duration_ms, t.subagents, t.diagnostics_warnings, t.diagnostics_partial,
       t.tokens_in, t.tokens_out, t.title_generated, t.outcome, t.files_touched,
       t.lines_changed, t.retry_loops, t.retry_tokens_wasted, t.within_session_reverts,
       t.signal_density, t.spec_quality_score, t.exploration_ratio, t.scope_breadth,
       t.discovery_turns, t.m2_token_outcome_ratio, t.m3_unique_tool_count,
       t.m4_error_recovery_count, t.m4_consecutive_error_max, t.m5_context_utilization_pct,
       t.m5_peak_context_tokens, t.m5_avg_message_tokens, t.m6_output_survival_pct,
       t.m6_lines_survived, t.m6_lines_total, t.m7_spec_word_count,
       t.m7_spec_has_examples, t.m7_spec_has_constraints, t.computed_at,
       t.compute_version, t.content_hash, t.license_id, t.wrapped_data_key,
       t.encryption_algorithm, t.key_version, t.session_origin,
       u.github_username   AS owner_username,
       u.avatar_url        AS owner_avatar_url,
       u.is_discoverable   AS owner_is_discoverable
FROM transcripts t
JOIN transcript_shares ts ON t.id = ts.transcript_id
JOIN users u ON t.owner_id = u.id
WHERE ts.group_id = $1 AND ts.status = 'approved'
ORDER BY t.published_at DESC
LIMIT $2 OFFSET $3
`

type ListGroupTranscriptsParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListGroupTranscriptsRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	OwnerID                 pgtype.UUID        `db:"owner_id" json:"owner_id"`
	LocalID                 string             `db:"local_id" json:"local_id"`
	Title                   pgtype.Text        `db:"title" json:"title"`
	Description             pgtype.Text        `db:"description" json:"description"`
	Visibility              string             `db:"visibility" json:"visibility"`
	ModelProvider           string             `db:"model_provider" json:"model_provider"`
	ModelName               pgtype.Text        `db:"model_name" json:"model_name"`
	HarnessVersion          pgtype.Text        `db:"harness_version" json:"harness_version"`
	SessionStart            pgtype.Timestamptz `db:"session_start" json:"session_start"`
	SessionEnd              pgtype.Timestamptz `db:"session_end" json:"session_end"`
	TurnCount               pgtype.Int4        `db:"turn_count" json:"turn_count"`
	TokenCount              pgtype.Int4        `db:"token_count" json:"token_count"`
	BlobKey                 string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes           pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	SchemaVersion           string             `db:"schema_version" json:"schema_version"`
	PublishedAt             pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ParentSessionID         pgtype.Text        `db:"parent_session_id" json:"parent_session_id"`
	IngestedAt              pgtype.Timestamptz `db:"ingested_at" json:"ingested_at"`
	SourceFilePath          pgtype.Text        `db:"source_file_path" json:"source_file_path"`
	SourceFormat            pgtype.Text        `db:"source_format" json:"source_format"`
	GitBranch               pgtype.Text        `db:"git_branch" json:"git_branch"`
	GitRemote               pgtype.Text        `db:"git_remote" json:"git_remote"`
	GitWorktree             pgtype.Text        `db:"git_worktree" json:"git_worktree"`
	ProjectHash             string             `db:"project_hash" json:"project_hash"`
	ProjectPath             pgtype.Text        `db:"project_path" json:"project_path"`
	ProjectName             pgtype.Text        `db:"project_name" json:"project_name"`
	ToolCallCount           pgtype.Int4        `db:"tool_call_count" json:"tool_call_count"`
	SubagentCount           pgtype.Int4        `db:"subagent_count" json:"subagent_count"`
	DurationMs              pgtype.Int8        `db:"duration_ms" json:"duration_ms"`
	Subagents               []byte             `db:"subagents" json:"subagents"`
	DiagnosticsWarnings     []byte             `db:"diagnostics_warnings" json:"diagnostics_warnings"`
	DiagnosticsPartial      pgtype.Bool        `db:"diagnostics_partial" json:"diagnostics_partial"`
	TokensIn                pgtype.Int8        `db:"tokens_in" json:"tokens_in"`
	TokensOut               pgtype.Int8        `db:"tokens_out" json:"tokens_out"`
	TitleGenerated          pgtype.Text        `db:"title_generated" json:"title_generated"`
	Outcome                 pgtype.Text        `db:"outcome" json:"outcome"`
	FilesTouched            pgtype.Int4        `db:"files_touched" json:"files_touched"`
	LinesChanged            pgtype.Int4        `db:"lines_changed" json:"lines_changed"`
	RetryLoops              pgtype.Int4        `db:"retry_loops" json:"retry_loops"`
	RetryTokensWasted       pgtype.Int4        `db:"retry_tokens_wasted" json:"retry_tokens_wasted"`
	WithinSessionReverts    pgtype.Int4        `db:"within_session_reverts" json:"within_session_reverts"`
	SignalDensity           pgtype.Float4      `db:"signal_density" json:"signal_density"`
	SpecQualityScore        pgtype.Float4      `db:"spec_quality_score" json:"spec_quality_score"`
	ExplorationRatio        pgtype.Float4      `db:"exploration_ratio" json:"exploration_ratio"`
	ScopeBreadth            pgtype.Int4        `db:"scope_breadth" json:"scope_breadth"`
	DiscoveryTurns          pgtype.Int4        `db:"discovery_turns" json:"discovery_turns"`
	M2TokenOutcomeRatio     pgtype.Float4      `db:"m2_token_outcome_ratio" json:"m2_token_outcome_ratio"`
	M3UniqueToolCount       pgtype.Int4        `db:"m3_unique_tool_count" json:"m3_unique_tool_count"`
	M4ErrorRecoveryCount    pgtype.Int4        `db:"m4_error_recovery_count" json:"m4_error_recovery_count"`
	M4ConsecutiveErrorMax   pgtype.Int4        `db:"m4_consecutive_error_max" json:"m4_consecutive_error_max"`
	M5ContextUtilizationPct pgtype.Float4      `db:"m5_context_utilization_pct" json:"m5_context_utilization_pct"`
	M5PeakContextTokens     pgtype.Int4        `db:"m5_peak_context_tokens" json:"m5_peak_context_tokens"`
	M5AvgMessageTokens      pgtype.Int4        `db:"m5_avg_message_tokens" json:"m5_avg_message_tokens"`
	M6OutputSurvivalPct     pgtype.Float4      `db:"m6_output_survival_pct" json:"m6_output_survival_pct"`
	M6LinesSurvived         pgtype.Int4        `db:"m6_lines_survived" json:"m6_lines_survived"`
	M6LinesTotal            pgtype.Int4        `db:"m6_lines_total" json:"m6_lines_total"`
	M7SpecWordCount         pgtype.Int4        `db:"m7_spec_word_count" json:"m7_spec_word_count"`
	M7SpecHasExamples       pgtype.Bool        `db:"m7_spec_has_examples" json:"m7_spec_has_examples"`
	M7SpecHasConstraints    pgtype.Bool        `db:"m7_spec_has_constraints" json:"m7_spec_has_constraints"`
	ComputedAt              pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
	ComputeVersion          pgtype.Int4        `db:"compute_version" json:"compute_version"`
	ContentHash             pgtype.Text        `db:"content_hash" json:"content_hash"`
	LicenseID               pgtype.Text        `db:"license_id" json:"license_id"`
	WrappedDataKey          []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm     string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	SessionOrigin           string             `db:"session_origin" json:"session_origin"`
	OwnerUsername           string             `db:"owner_username" json:"owner_username"`
	OwnerAvatarUrl          pgtype.Text        `db:"owner_avatar_url" json:"owner_avatar_url"`
	OwnerIsDiscoverable     bool               `db:"owner_is_discoverable" json:"owner_is_discoverable"`
}

// The pull-share query ListApprovedTranscriptShareGroups lives in the sibling
// source file queries/shares_pull.sql, mirroring the
// annotations_push convention so sqlc round-trips it into shares_pull.sql.go
// without colliding with this file's generated shares.sql.go.
func (q *Queries) ListGroupTranscripts(ctx context.Context, arg ListGroupTranscriptsParams) ([]ListGroupTranscriptsRow, error) {
	rows, err := q.db.Query(ctx, listGroupTranscripts, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupTranscriptsRow{}
	for rows.Next() {
		var i ListGroupTranscriptsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.LocalID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.ModelProvider,
			&i.ModelName,
			&i.HarnessVersion,
			&i.SessionStart,
			&i.SessionEnd,
			&i.TurnCount,
			&i.TokenCount,
			&i.BlobKey,
			&i.BlobSizeBytes,
			&i.SchemaVersion,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.ParentSessionID,
			&i.IngestedAt,
			&i.SourceFilePath,
			&i.SourceFormat,
			&i.GitBranch,
			&i.GitRemote,
			&i.GitWorktree,
			&i.ProjectHash,
			&i.ProjectPath,
			&i.ProjectName,
			&i.ToolCallCount,
			&i.SubagentCount,
			&i.DurationMs,
			&i.Subagents,
			&i.DiagnosticsWarnings,
			&i.DiagnosticsPartial,
			&i.TokensIn,
			&i.TokensOut,
			&i.TitleGenerated,
			&i.Outcome,
			&i.FilesTouched,
			&i.LinesChanged,
			&i.RetryLoops,
			&i.RetryTokensWasted,
			&i.WithinSessionReverts,
			&i.SignalDensity,
			&i.SpecQualityScore,
			&i.ExplorationRatio,
			&i.ScopeBreadth,
			&i.DiscoveryTurns,
			&i.M2TokenOutcomeRatio,
			&i.M3UniqueToolCount,
			&i.M4ErrorRecoveryCount,
			&i.M4ConsecutiveErrorMax,
			&i.M5ContextUtilizationPct,
			&i.M5PeakContextTokens,
			&i.M5AvgMessageTokens,
			&i.M6OutputSurvivalPct,
			&i.M6LinesSurvived,
			&i.M6LinesTotal,
			&i.M7SpecWordCount,
			&i.M7SpecHasExamples,
			&i.M7SpecHasConstraints,
			&i.ComputedAt,
			&i.ComputeVersion,
			&i.ContentHash,
			&i.LicenseID,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
			&i.SessionOrigin,
			&i.OwnerUsername,
			&i.OwnerAvatarUrl,
			&i.OwnerIsDiscoverable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveShareAttemptsForGroup = `-- name: ListLiveShareAttemptsForGroup :many
SELECT latest.transcript_id, latest.status
FROM (
    SELECT DISTINCT ON (a.transcript_id)
           a.transcript_id, a.status
    FROM transcript_share_attempts a
    WHERE a.group_id = $1
      AND a.transcript_id = ANY($2::uuid[])
    ORDER BY a.transcript_id, a.event_num DESC
) latest
WHERE latest.status IN ('pending', 'approved')
`

type ListLiveShareAttemptsForGroupParams struct {
	GroupID       pgtype.UUID   `db:"group_id" json:"group_id"`
	TranscriptIds []pgtype.UUID `db:"transcript_ids" json:"transcript_ids"`
}

type ListLiveShareAttemptsForGroupRow struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Status       string      `db:"status" json:"status"`
}

// Which of the named transcripts are ALREADY live in one collective. Live means
// the latest event of the (transcript, collective) pair is pending or approved,
// which is exactly what makes a further submission a duplicate rather than the
// next attempt.
//
// This statement reads the attempt LEDGER (transcript_share_attempts) and
// nothing else. It deliberately never mentions the derived transcript_shares
// row: a pair that was submitted, refused and then withdrawn has no derived row,
// and a batch that consulted the projection would report an open submission as
// absent and then be refused by the database instead of answering the person.
func (q *Queries) ListLiveShareAttemptsForGroup(ctx context.Context, arg ListLiveShareAttemptsForGroupParams) ([]ListLiveShareAttemptsForGroupRow, error) {
	rows, err := q.db.Query(ctx, listLiveShareAttemptsForGroup, arg.GroupID, arg.TranscriptIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveShareAttemptsForGroupRow{}
	for rows.Next() {
		var i ListLiveShareAttemptsForGroupRow
		if err := rows.Scan(&i.TranscriptID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerCollectiveSubmissions = `-- name: ListOwnerCollectiveSubmissions :many
SELECT latest.transcript_id, latest.group_id, latest.title, latest.event_num,
       latest.status, latest.recorded_at
FROM (
  SELECT DISTINCT ON (a.transcript_id)
         a.transcript_id, a.group_id, t.title, a.event_num, a.status, a.recorded_at
  FROM transcript_share_attempts a
  JOIN transcripts t ON t.id = a.transcript_id
  WHERE a.group_id = $1 AND t.owner_id = $2
  ORDER BY a.transcript_id, a.event_num DESC
) latest
ORDER BY latest.recorded_at DESC, latest.transcript_id
`

type ListOwnerCollectiveSubmissionsParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

type ListOwnerCollectiveSubmissionsRow struct {
	TranscriptID pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID        `db:"group_id" json:"group_id"`
	Title        pgtype.Text        `db:"title" json:"title"`
	EventNum     int32              `db:"event_num" json:"event_num"`
	Status       string             `db:"status" json:"status"`
	RecordedAt   pgtype.Timestamptz `db:"recorded_at" json:"recorded_at"`
}

// EVERY (transcript, collective) pair the caller has ever offered to ONE
// collective, with the latest recorded event of each pair.
//
// The source is the ATTEMPT LEDGER, never the derived current-state row, and
// that is the whole point of the statement. The derived row is a fold that
// keeps only live states: a pair whose last event was a retraction or a
// revocation has no derived row at all. A listing built on the derived row
// therefore reported nothing for a contribution that was submitted, refused and
// then withdrawn - the person was told they had refusals and then shown an
// empty list. Reading the ledger keeps the fully-withdrawn pair listed, so its
// history stays reachable.
//
// Owner-only: $2 is the authenticated caller, and there is deliberately no
// username parameter and no username route, so no request can name a subject
// other than the caller. A caller with no pair here gets an empty result, which
// the handler answers as 404 - the same answer as a collective that does not
// exist, so asking cannot be used to discover one.
// $1 = group_id, $2 = owner_id.
func (q *Queries) ListOwnerCollectiveSubmissions(ctx context.Context, arg ListOwnerCollectiveSubmissionsParams) ([]ListOwnerCollectiveSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, listOwnerCollectiveSubmissions, arg.GroupID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerCollectiveSubmissionsRow{}
	for rows.Next() {
		var i ListOwnerCollectiveSubmissionsRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.GroupID,
			&i.Title,
			&i.EventNum,
			&i.Status,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGroupShares = `-- name: ListPendingGroupShares :many
SELECT ts.transcript_id, t.title, t.model_provider,
       u.github_username as owner_username,
       u.is_discoverable as owner_is_discoverable,
       ts.shared_at
FROM transcript_shares ts
JOIN transcripts t ON ts.transcript_id = t.id
JOIN users u ON t.owner_id = u.id
WHERE ts.group_id = $1 AND ts.status = 'pending'
ORDER BY ts.shared_at
`

type ListPendingGroupSharesRow struct {
	TranscriptID        pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	Title               pgtype.Text        `db:"title" json:"title"`
	ModelProvider       string             `db:"model_provider" json:"model_provider"`
	OwnerUsername       string             `db:"owner_username" json:"owner_username"`
	OwnerIsDiscoverable bool               `db:"owner_is_discoverable" json:"owner_is_discoverable"`
	SharedAt            pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

func (q *Queries) ListPendingGroupShares(ctx context.Context, groupID pgtype.UUID) ([]ListPendingGroupSharesRow, error) {
	rows, err := q.db.Query(ctx, listPendingGroupShares, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingGroupSharesRow{}
	for rows.Next() {
		var i ListPendingGroupSharesRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.Title,
			&i.ModelProvider,
			&i.OwnerUsername,
			&i.OwnerIsDiscoverable,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShareAttempts = `-- name: ListShareAttempts :many
SELECT id, transcript_id, group_id, event_num, status,
       recorded_at, decided_at, decided_by
FROM transcript_share_attempts
WHERE transcript_id = $1 AND group_id = $2
ORDER BY event_num
`

type ListShareAttemptsParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
}

// The full submission history for a (transcript, collective) pair, oldest
// first. Every rejection and every withdrawal is its own row.
func (q *Queries) ListShareAttempts(ctx context.Context, arg ListShareAttemptsParams) ([]TranscriptShareAttempt, error) {
	rows, err := q.db.Query(ctx, listShareAttempts, arg.TranscriptID, arg.GroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptShareAttempt{}
	for rows.Next() {
		var i TranscriptShareAttempt
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.GroupID,
			&i.EventNum,
			&i.Status,
			&i.RecordedAt,
			&i.DecidedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharesByTranscriptIDs = `-- name: ListSharesByTranscriptIDs :many
SELECT ts.transcript_id, ts.group_id, g.name as group_name,
       g.acceptance_mode, ts.status, ts.shared_at
FROM transcript_shares ts
JOIN groups g ON ts.group_id = g.id
WHERE ts.transcript_id = ANY($1::uuid[]) AND ts.status = 'approved'
`

type ListSharesByTranscriptIDsRow struct {
	TranscriptID   pgtype.UUID        `db:"transcript_id" json:"transcript_id"`
	GroupID        pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupName      string             `db:"group_name" json:"group_name"`
	AcceptanceMode string             `db:"acceptance_mode" json:"acceptance_mode"`
	Status         string             `db:"status" json:"status"`
	SharedAt       pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

func (q *Queries) ListSharesByTranscriptIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListSharesByTranscriptIDsRow, error) {
	rows, err := q.db.Query(ctx, listSharesByTranscriptIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharesByTranscriptIDsRow{}
	for rows.Next() {
		var i ListSharesByTranscriptIDsRow
		if err := rows.Scan(
			&i.TranscriptID,
			&i.GroupID,
			&i.GroupName,
			&i.AcceptanceMode,
			&i.Status,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptShares = `-- name: ListTranscriptShares :many
SELECT ts.group_id, g.name as group_name, ts.shared_at
FROM transcript_shares ts
JOIN groups g ON ts.group_id = g.id
WHERE ts.transcript_id = $1
`

type ListTranscriptSharesRow struct {
	GroupID   pgtype.UUID        `db:"group_id" json:"group_id"`
	GroupName string             `db:"group_name" json:"group_name"`
	SharedAt  pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

func (q *Queries) ListTranscriptShares(ctx context.Context, transcriptID pgtype.UUID) ([]ListTranscriptSharesRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptShares, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptSharesRow{}
	for rows.Next() {
		var i ListTranscriptSharesRow
		if err := rows.Scan(&i.GroupID, &i.GroupName, &i.SharedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSharesInGroup = `-- name: ListUserSharesInGroup :many
SELECT t.id, t.title, t.model_provider, t.model_name, t.visibility,
       t.published_at, t.turn_count, t.tokens_in, t.tokens_out,
       ts.status, ts.shared_at
FROM transcript_shares ts
JOIN transcripts t ON ts.transcript_id = t.id
WHERE ts.group_id = $1 AND t.owner_id = $2
ORDER BY ts.shared_at DESC
`

type ListUserSharesInGroupParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

type ListUserSharesInGroupRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Title         pgtype.Text        `db:"title" json:"title"`
	ModelProvider string             `db:"model_provider" json:"model_provider"`
	ModelName     pgtype.Text        `db:"model_name" json:"model_name"`
	Visibility    string             `db:"visibility" json:"visibility"`
	PublishedAt   pgtype.Timestamptz `db:"published_at" json:"published_at"`
	TurnCount     pgtype.Int4        `db:"turn_count" json:"turn_count"`
	TokensIn      pgtype.Int8        `db:"tokens_in" json:"tokens_in"`
	TokensOut     pgtype.Int8        `db:"tokens_out" json:"tokens_out"`
	Status        string             `db:"status" json:"status"`
	SharedAt      pgtype.Timestamptz `db:"shared_at" json:"shared_at"`
}

// Returns the caller's own transcripts shared with a given collective
// (both approved and pending). Used to power the "Your contributions" card
// on the collective page.
func (q *Queries) ListUserSharesInGroup(ctx context.Context, arg ListUserSharesInGroupParams) ([]ListUserSharesInGroupRow, error) {
	rows, err := q.db.Query(ctx, listUserSharesInGroup, arg.GroupID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserSharesInGroupRow{}
	for rows.Next() {
		var i ListUserSharesInGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ModelProvider,
			&i.ModelName,
			&i.Visibility,
			&i.PublishedAt,
			&i.TurnCount,
			&i.TokensIn,
			&i.TokensOut,
			&i.Status,
			&i.SharedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeGroupTranscript = `-- name: RemoveGroupTranscript :exec
WITH live AS (
    SELECT event_num, status
    FROM transcript_share_attempts
    WHERE group_id = $1 AND transcript_id = $2
      AND status IN ('pending', 'approved')
    ORDER BY event_num DESC
    LIMIT 1
), closed_open_submission AS (
    UPDATE transcript_share_attempts t
    SET status = 'revoked', decided_at = now()
    FROM live
    WHERE t.group_id = $1 AND t.transcript_id = $2
      AND t.event_num = live.event_num
      AND live.status = 'pending'
    RETURNING t.event_num
)
INSERT INTO transcript_share_attempts (transcript_id, group_id, event_num, status, decided_at)
SELECT $2, $1, live.event_num + 1, 'revoked', now()
FROM live
WHERE live.status = 'approved'
`

type RemoveGroupTranscriptParams struct {
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
}

// The collective removes a contribution. 'revoked' is kept distinct from
// 'retracted' because the actor differs: the collective removed it rather than
// the owner withdrawing it, and conflating the two makes the history unreadable
// for the person whose transcript it is.
//
// Same two shapes as a withdrawal: a submission awaiting review is closed in
// place, an accepted contribution gets a further attempt so its acceptance
// stays on record. A submission awaiting review is closed too - before the
// attempt model this route removed the share whatever its state, and leaving it
// open would keep it in the review queue and block re-submission forever.
func (q *Queries) RemoveGroupTranscript(ctx context.Context, arg RemoveGroupTranscriptParams) error {
	_, err := q.db.Exec(ctx, removeGroupTranscript, arg.GroupID, arg.TranscriptID)
	return err
}

const retractUserSharesInGroup = `-- name: RetractUserSharesInGroup :exec
WITH live AS (
    SELECT DISTINCT ON (a.transcript_id)
           a.transcript_id, a.event_num, a.status
    FROM transcript_share_attempts a
    JOIN transcripts t ON t.id = a.transcript_id
    WHERE a.group_id = $1
      AND t.owner_id = $2
      AND a.status IN ('pending', 'approved')
    ORDER BY a.transcript_id, a.event_num DESC
), closed_open_submissions AS (
    UPDATE transcript_share_attempts a
    SET status = 'retracted', decided_at = now()
    FROM live
    WHERE a.group_id = $1
      AND a.transcript_id = live.transcript_id
      AND a.event_num = live.event_num
      AND live.status = 'pending'
    RETURNING a.event_num
)
INSERT INTO transcript_share_attempts (transcript_id, group_id, event_num, status, decided_at)
SELECT live.transcript_id, $1, live.event_num + 1, 'retracted', now()
FROM live
WHERE live.status = 'approved'
`

type RetractUserSharesInGroupParams struct {
	GroupID pgtype.UUID `db:"group_id" json:"group_id"`
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
}

// Closes every live attempt in the given collective whose transcript is owned
// by the given user. Used when a member leaves and chooses to retract, or when
// the collective's deletion policy is 'mandatory', so nothing of theirs is left
// open in a collective they have left.
//
// Per transcript this is the same two shapes as a single withdrawal: a
// submission awaiting review is closed in place, an accepted contribution gets
// a further attempt so its acceptance stays on record.
func (q *Queries) RetractUserSharesInGroup(ctx context.Context, arg RetractUserSharesInGroupParams) error {
	_, err := q.db.Exec(ctx, retractUserSharesInGroup, arg.GroupID, arg.OwnerID)
	return err
}

const shareTranscriptWithStatus = `-- name: ShareTranscriptWithStatus :exec
INSERT INTO transcript_share_attempts (transcript_id, group_id, event_num, status)
SELECT $1, $2, COALESCE(MAX(event_num), 0) + 1, $3
FROM transcript_share_attempts
WHERE transcript_id = $1 AND group_id = $2
`

type ShareTranscriptWithStatusParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	Status       string      `db:"status" json:"status"`
}

// The owner submits the transcript to a collective, opening the next attempt.
// A rejected, retracted or revoked history does not block a new submission -
// that is the point of counting attempts - so there is deliberately no
// ON CONFLICT DO NOTHING here: a duplicate submission while one is already
// live is refused by uq_share_attempt_open rather than silently discarded.
func (q *Queries) ShareTranscriptWithStatus(ctx context.Context, arg ShareTranscriptWithStatusParams) error {
	_, err := q.db.Exec(ctx, shareTranscriptWithStatus, arg.TranscriptID, arg.GroupID, arg.Status)
	return err
}

const unshareTranscript = `-- name: UnshareTranscript :exec
WITH live AS (
    SELECT event_num, status
    FROM transcript_share_attempts
    WHERE transcript_id = $1 AND group_id = $2
      AND status IN ('pending', 'approved')
    ORDER BY event_num DESC
    LIMIT 1
), closed_open_submission AS (
    UPDATE transcript_share_attempts t
    SET status = 'retracted', decided_at = now()
    FROM live
    WHERE t.transcript_id = $1 AND t.group_id = $2
      AND t.event_num = live.event_num
      AND live.status = 'pending'
    RETURNING t.event_num
)
INSERT INTO transcript_share_attempts (transcript_id, group_id, event_num, status, decided_at)
SELECT $1, $2, live.event_num + 1, 'retracted', now()
FROM live
WHERE live.status = 'approved'
`

type UnshareTranscriptParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
}

// The owner withdraws their contribution.
//
// Two shapes, because an accepted contribution and a submission awaiting review
// are different things. A submission still awaiting review is closed in place:
// nothing was decided, and leaving it open would block the owner from ever
// offering that transcript again. An ACCEPTED contribution is history - it was
// accepted, by someone, on a date - so withdrawing it appends a further
// attempt rather than overwriting the acceptance.
//
// Either way the latest attempt ends up 'retracted' and the derivation removes
// the current-state row.
func (q *Queries) UnshareTranscript(ctx context.Context, arg UnshareTranscriptParams) error {
	_, err := q.db.Exec(ctx, unshareTranscript, arg.TranscriptID, arg.GroupID)
	return err
}

const updateShareStatus = `-- name: UpdateShareStatus :exec
UPDATE transcript_share_attempts
SET status = $3, decided_at = now(), decided_by = $4
WHERE transcript_id = $1
  AND group_id = $2
  AND status = 'pending'
`

type UpdateShareStatusParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	GroupID      pgtype.UUID `db:"group_id" json:"group_id"`
	Status       string      `db:"status" json:"status"`
	DecidedBy    pgtype.UUID `db:"decided_by" json:"decided_by"`
}

// A moderator decides the open attempt. Only a still-open attempt can be
// decided; a decided attempt is history, and changing a decision means a new
// submission and a new attempt.
func (q *Queries) UpdateShareStatus(ctx context.Context, arg UpdateShareStatusParams) error {
	_, err := q.db.Exec(ctx, updateShareStatus,
		arg.TranscriptID,
		arg.GroupID,
		arg.Status,
		arg.DecidedBy,
	)
	return err
}
