// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shares_pull.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listApprovedTranscriptShareGroups = `-- name: ListApprovedTranscriptShareGroups :many

SELECT ts.group_id
FROM transcript_shares ts
WHERE ts.transcript_id = $1 AND ts.status = 'approved'
`

// Pull-share queries live in this dedicated source file so sqlc emits them into
// shares_pull.sql.go without colliding with shares.sql.go. This mirrors the
// annotations_push.sql source and generated-file layout.
// Returns the group IDs for a transcript's approved shares.
// canPullTranscript is stricter than canViewTranscript here: a
// pending/rejected share does NOT grant pull access, so the policy fn checks the
// requester's membership only against APPROVED shares (the divergence-table row
// "group-shared, acceptance pending/rejected => deny").
func (q *Queries) ListApprovedTranscriptShareGroups(ctx context.Context, transcriptID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listApprovedTranscriptShareGroups, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var group_id pgtype.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
