// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) GetOrCreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTranscriptTags = `-- name: GetTranscriptTags :many
SELECT t.id, t.name
FROM tags t
JOIN transcript_tags tt ON t.id = tt.tag_id
WHERE tt.transcript_id = $1
`

func (q *Queries) GetTranscriptTags(ctx context.Context, transcriptID pgtype.UUID) ([]Tag, error) {
	rows, err := q.db.Query(ctx, getTranscriptTags, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkTranscriptTag = `-- name: LinkTranscriptTag :exec
INSERT INTO transcript_tags (transcript_id, tag_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type LinkTranscriptTagParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	TagID        pgtype.UUID `db:"tag_id" json:"tag_id"`
}

func (q *Queries) LinkTranscriptTag(ctx context.Context, arg LinkTranscriptTagParams) error {
	_, err := q.db.Exec(ctx, linkTranscriptTag, arg.TranscriptID, arg.TagID)
	return err
}

const listPopularTags = `-- name: ListPopularTags :many
SELECT t.id, t.name, count(tt.transcript_id) as usage_count
FROM tags t
JOIN transcript_tags tt ON t.id = tt.tag_id
GROUP BY t.id, t.name
ORDER BY usage_count DESC
LIMIT $1
`

type ListPopularTagsRow struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	UsageCount int64       `db:"usage_count" json:"usage_count"`
}

func (q *Queries) ListPopularTags(ctx context.Context, limit int32) ([]ListPopularTagsRow, error) {
	rows, err := q.db.Query(ctx, listPopularTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularTagsRow{}
	for rows.Next() {
		var i ListPopularTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, count(tt.transcript_id) as usage_count
FROM tags t
LEFT JOIN transcript_tags tt ON t.id = tt.tag_id
GROUP BY t.id, t.name
ORDER BY t.name
`

type ListTagsRow struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	UsageCount int64       `db:"usage_count" json:"usage_count"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.UsageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkTranscriptTags = `-- name: UnlinkTranscriptTags :exec
DELETE FROM transcript_tags WHERE transcript_id = $1
`

func (q *Queries) UnlinkTranscriptTags(ctx context.Context, transcriptID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unlinkTranscriptTags, transcriptID)
	return err
}
