// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: title_backfill.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndSwapTranscriptTitles = `-- name: CompareAndSwapTranscriptTitles :execrows
UPDATE transcripts
SET title = $1,
    title_generated = $2,
    updated_at = now()
WHERE id = $3
  AND title IS NOT DISTINCT FROM $4
  AND title_generated IS NOT DISTINCT FROM $5
  AND updated_at = $6
`

type CompareAndSwapTranscriptTitlesParams struct {
	Title                  pgtype.Text        `db:"title" json:"title"`
	TitleGenerated         pgtype.Text        `db:"title_generated" json:"title_generated"`
	ID                     pgtype.UUID        `db:"id" json:"id"`
	ExpectedTitle          pgtype.Text        `db:"expected_title" json:"expected_title"`
	ExpectedTitleGenerated pgtype.Text        `db:"expected_title_generated" json:"expected_title_generated"`
	ExpectedUpdatedAt      pgtype.Timestamptz `db:"expected_updated_at" json:"expected_updated_at"`
}

func (q *Queries) CompareAndSwapTranscriptTitles(ctx context.Context, arg CompareAndSwapTranscriptTitlesParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapTranscriptTitles,
		arg.Title,
		arg.TitleGenerated,
		arg.ID,
		arg.ExpectedTitle,
		arg.ExpectedTitleGenerated,
		arg.ExpectedUpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listTranscriptTitleBackfillBatch = `-- name: ListTranscriptTitleBackfillBatch :many
SELECT id, title, title_generated, updated_at, model_provider, project_path,
       blob_key, blob_size_bytes, content_hash, wrapped_data_key,
       encryption_algorithm, key_version
FROM transcripts
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListTranscriptTitleBackfillBatchParams struct {
	AfterID   pgtype.UUID `db:"after_id" json:"after_id"`
	BatchSize int32       `db:"batch_size" json:"batch_size"`
}

type ListTranscriptTitleBackfillBatchRow struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Title               pgtype.Text        `db:"title" json:"title"`
	TitleGenerated      pgtype.Text        `db:"title_generated" json:"title_generated"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ModelProvider       string             `db:"model_provider" json:"model_provider"`
	ProjectPath         pgtype.Text        `db:"project_path" json:"project_path"`
	BlobKey             string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes       pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	ContentHash         pgtype.Text        `db:"content_hash" json:"content_hash"`
	WrappedDataKey      []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion          int32              `db:"key_version" json:"key_version"`
}

func (q *Queries) ListTranscriptTitleBackfillBatch(ctx context.Context, arg ListTranscriptTitleBackfillBatchParams) ([]ListTranscriptTitleBackfillBatchRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptTitleBackfillBatch, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptTitleBackfillBatchRow{}
	for rows.Next() {
		var i ListTranscriptTitleBackfillBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleGenerated,
			&i.UpdatedAt,
			&i.ModelProvider,
			&i.ProjectPath,
			&i.BlobKey,
			&i.BlobSizeBytes,
			&i.ContentHash,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
