// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts_pull.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const compareAndSwapContentIdentity = `-- name: CompareAndSwapContentIdentity :execrows
UPDATE transcripts
SET content_hash = $1,
    blob_size_bytes = $2
WHERE id = $3
  AND blob_key = $4
  AND wrapped_data_key = $5
  AND encryption_algorithm = $6
  AND key_version = $7
  AND content_hash IS NULL
  AND blob_size_bytes IS NOT DISTINCT FROM $8
`

type CompareAndSwapContentIdentityParams struct {
	ContentHash                 pgtype.Text `db:"content_hash" json:"content_hash"`
	PlaintextSize               pgtype.Int8 `db:"plaintext_size" json:"plaintext_size"`
	ID                          pgtype.UUID `db:"id" json:"id"`
	ExpectedBlobKey             string      `db:"expected_blob_key" json:"expected_blob_key"`
	ExpectedWrappedDataKey      []byte      `db:"expected_wrapped_data_key" json:"expected_wrapped_data_key"`
	ExpectedEncryptionAlgorithm string      `db:"expected_encryption_algorithm" json:"expected_encryption_algorithm"`
	ExpectedKeyVersion          int32       `db:"expected_key_version" json:"expected_key_version"`
	ExpectedPriorBlobSizeBytes  pgtype.Int8 `db:"expected_prior_blob_size_bytes" json:"expected_prior_blob_size_bytes"`
}

func (q *Queries) CompareAndSwapContentIdentity(ctx context.Context, arg CompareAndSwapContentIdentityParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapContentIdentity,
		arg.ContentHash,
		arg.PlaintextSize,
		arg.ID,
		arg.ExpectedBlobKey,
		arg.ExpectedWrappedDataKey,
		arg.ExpectedEncryptionAlgorithm,
		arg.ExpectedKeyVersion,
		arg.ExpectedPriorBlobSizeBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const compareAndSwapTranscriptBlob = `-- name: CompareAndSwapTranscriptBlob :one
UPDATE transcripts
SET blob_key = $1,
    wrapped_data_key = $2,
    encryption_algorithm = $3,
    key_version = $4,
    content_hash = $5,
    blob_size_bytes = $6,
    updated_at = now()
WHERE id = $7
  AND blob_key = $8
  AND wrapped_data_key = $9
  AND encryption_algorithm = $10
  AND key_version = $11
RETURNING id, owner_id, local_id, title, description, visibility, model_provider,
    model_name, harness_version, session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version, published_at, updated_at, parent_session_id,
    ingested_at, source_file_path, source_format, git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name, tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial, tokens_in, tokens_out,
    title_generated, outcome, files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio, m3_unique_tool_count,
    m4_error_recovery_count, m4_consecutive_error_max, m5_context_utilization_pct,
    m5_peak_context_tokens, m5_avg_message_tokens, m6_output_survival_pct,
    m6_lines_survived, m6_lines_total, m7_spec_word_count, m7_spec_has_examples,
    m7_spec_has_constraints, computed_at, compute_version, content_hash, license_id,
    wrapped_data_key, encryption_algorithm, key_version, accepted_request_operation_fingerprint
`

type CompareAndSwapTranscriptBlobParams struct {
	BlobKey                     string      `db:"blob_key" json:"blob_key"`
	WrappedDataKey              []byte      `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm         string      `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion                  int32       `db:"key_version" json:"key_version"`
	ContentHash                 pgtype.Text `db:"content_hash" json:"content_hash"`
	PlaintextSize               pgtype.Int8 `db:"plaintext_size" json:"plaintext_size"`
	ID                          pgtype.UUID `db:"id" json:"id"`
	ExpectedBlobKey             string      `db:"expected_blob_key" json:"expected_blob_key"`
	ExpectedWrappedDataKey      []byte      `db:"expected_wrapped_data_key" json:"expected_wrapped_data_key"`
	ExpectedEncryptionAlgorithm string      `db:"expected_encryption_algorithm" json:"expected_encryption_algorithm"`
	ExpectedKeyVersion          int32       `db:"expected_key_version" json:"expected_key_version"`
}

func (q *Queries) CompareAndSwapTranscriptBlob(ctx context.Context, arg CompareAndSwapTranscriptBlobParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, compareAndSwapTranscriptBlob,
		arg.BlobKey,
		arg.WrappedDataKey,
		arg.EncryptionAlgorithm,
		arg.KeyVersion,
		arg.ContentHash,
		arg.PlaintextSize,
		arg.ID,
		arg.ExpectedBlobKey,
		arg.ExpectedWrappedDataKey,
		arg.ExpectedEncryptionAlgorithm,
		arg.ExpectedKeyVersion,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LocalID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ModelProvider,
		&i.ModelName,
		&i.HarnessVersion,
		&i.SessionStart,
		&i.SessionEnd,
		&i.TurnCount,
		&i.TokenCount,
		&i.BlobKey,
		&i.BlobSizeBytes,
		&i.SchemaVersion,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ParentSessionID,
		&i.IngestedAt,
		&i.SourceFilePath,
		&i.SourceFormat,
		&i.GitBranch,
		&i.GitRemote,
		&i.GitWorktree,
		&i.ProjectHash,
		&i.ProjectPath,
		&i.ProjectName,
		&i.ToolCallCount,
		&i.SubagentCount,
		&i.DurationMs,
		&i.Subagents,
		&i.DiagnosticsWarnings,
		&i.DiagnosticsPartial,
		&i.TokensIn,
		&i.TokensOut,
		&i.TitleGenerated,
		&i.Outcome,
		&i.FilesTouched,
		&i.LinesChanged,
		&i.RetryLoops,
		&i.RetryTokensWasted,
		&i.WithinSessionReverts,
		&i.SignalDensity,
		&i.SpecQualityScore,
		&i.ExplorationRatio,
		&i.ScopeBreadth,
		&i.DiscoveryTurns,
		&i.M2TokenOutcomeRatio,
		&i.M3UniqueToolCount,
		&i.M4ErrorRecoveryCount,
		&i.M4ConsecutiveErrorMax,
		&i.M5ContextUtilizationPct,
		&i.M5PeakContextTokens,
		&i.M5AvgMessageTokens,
		&i.M6OutputSurvivalPct,
		&i.M6LinesSurvived,
		&i.M6LinesTotal,
		&i.M7SpecWordCount,
		&i.M7SpecHasExamples,
		&i.M7SpecHasConstraints,
		&i.ComputedAt,
		&i.ComputeVersion,
		&i.ContentHash,
		&i.LicenseID,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
		&i.AcceptedRequestOperationFingerprint,
	)
	return i, err
}

const compareAndSwapWrappedDataKey = `-- name: CompareAndSwapWrappedDataKey :execrows
UPDATE transcripts
SET wrapped_data_key = $1,
    key_version = $2,
    updated_at = now()
WHERE id = $3
  AND blob_key = $4
  AND wrapped_data_key = $5
  AND encryption_algorithm = $6
  AND key_version = $7
`

type CompareAndSwapWrappedDataKeyParams struct {
	WrappedDataKey              []byte      `db:"wrapped_data_key" json:"wrapped_data_key"`
	KeyVersion                  int32       `db:"key_version" json:"key_version"`
	ID                          pgtype.UUID `db:"id" json:"id"`
	ExpectedBlobKey             string      `db:"expected_blob_key" json:"expected_blob_key"`
	ExpectedWrappedDataKey      []byte      `db:"expected_wrapped_data_key" json:"expected_wrapped_data_key"`
	ExpectedEncryptionAlgorithm string      `db:"expected_encryption_algorithm" json:"expected_encryption_algorithm"`
	ExpectedKeyVersion          int32       `db:"expected_key_version" json:"expected_key_version"`
}

func (q *Queries) CompareAndSwapWrappedDataKey(ctx context.Context, arg CompareAndSwapWrappedDataKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapWrappedDataKey,
		arg.WrappedDataKey,
		arg.KeyVersion,
		arg.ID,
		arg.ExpectedBlobKey,
		arg.ExpectedWrappedDataKey,
		arg.ExpectedEncryptionAlgorithm,
		arg.ExpectedKeyVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countPullableTranscripts = `-- name: CountPullableTranscripts :one
SELECT COUNT(DISTINCT t.id)
FROM transcripts t
LEFT JOIN transcript_shares ts
    ON ts.transcript_id = t.id AND t.visibility = 'shared' AND ts.status = 'approved'
LEFT JOIN group_members gm ON gm.group_id = ts.group_id AND gm.user_id = $1
WHERE t.owner_id = $1 OR gm.user_id = $1
`

// Returns PullListResponse.Total, mirroring
// ListPullableTranscripts's predicate exactly.
func (q *Queries) CountPullableTranscripts(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPullableTranscripts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTranscriptAnnotations = `-- name: CountTranscriptAnnotations :one
SELECT COUNT(*) FROM annotations a
JOIN transcripts t ON t.id = $1
WHERE a.target_transcript_id = t.id
   OR (a.owner_id = t.owner_id AND (
       a.session_id = t.local_id
       OR a.entry_session_id = t.local_id
   ))
   OR EXISTS (
       SELECT 1
       FROM transcript_associations ta
       WHERE ta.owner_id = a.owner_id
         AND ta.association_id = a.target_association_id
         AND ta.transcript_id = t.id
   )
`

// Counts annotations for a single transcript's PullTranscriptInfo
// (the single-id meta route). The list route batches this via the correlated
// subquery in ListPullableTranscripts. Annotations target a transcript by its
// transcript UUID. Village-created manual targets use the exact UUID; pushed
// session and entry targets use the transcript's owner-scoped local id;
// association targets use the owner-scoped ledger, mirroring
// ListAnnotationsByTranscriptID's predicate.
func (q *Queries) CountTranscriptAnnotations(ctx context.Context, transcriptID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTranscriptAnnotations, transcriptID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTranscriptReturningDescriptor = `-- name: DeleteTranscriptReturningDescriptor :one
DELETE FROM transcripts
WHERE id = $1
RETURNING blob_key, wrapped_data_key, encryption_algorithm, key_version
`

type DeleteTranscriptReturningDescriptorRow struct {
	BlobKey             string `db:"blob_key" json:"blob_key"`
	WrappedDataKey      []byte `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm string `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion          int32  `db:"key_version" json:"key_version"`
}

func (q *Queries) DeleteTranscriptReturningDescriptor(ctx context.Context, id pgtype.UUID) (DeleteTranscriptReturningDescriptorRow, error) {
	row := q.db.QueryRow(ctx, deleteTranscriptReturningDescriptor, id)
	var i DeleteTranscriptReturningDescriptorRow
	err := row.Scan(
		&i.BlobKey,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
	)
	return i, err
}

const listPullableTranscripts = `-- name: ListPullableTranscripts :many
SELECT DISTINCT t.id, t.local_id, t.owner_id, u.github_username AS owner_username,
       t.title, t.model_provider, t.project_name, t.visibility, t.schema_version,
       t.published_at, t.updated_at, t.content_hash, t.license_id,
        (SELECT COUNT(*) FROM annotations a
            WHERE a.target_transcript_id = t.id
               OR (a.owner_id = t.owner_id AND (
                   a.session_id = t.local_id
                   OR a.entry_session_id = t.local_id
                 ))
              OR EXISTS (
                  SELECT 1 FROM transcript_associations ta
                  WHERE ta.owner_id = a.owner_id
                    AND ta.association_id = a.target_association_id
                    AND ta.transcript_id = t.id
              )) AS annotation_count
FROM transcripts t
JOIN users u ON u.id = t.owner_id
LEFT JOIN transcript_shares ts
    ON ts.transcript_id = t.id AND t.visibility = 'shared' AND ts.status = 'approved'
LEFT JOIN group_members gm ON gm.group_id = ts.group_id AND gm.user_id = $1
WHERE t.owner_id = $1 OR gm.user_id = $1
ORDER BY t.published_at DESC, t.id
LIMIT $2 OFFSET $3
`

type ListPullableTranscriptsParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
}

type ListPullableTranscriptsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	LocalID         string             `db:"local_id" json:"local_id"`
	OwnerID         pgtype.UUID        `db:"owner_id" json:"owner_id"`
	OwnerUsername   string             `db:"owner_username" json:"owner_username"`
	Title           pgtype.Text        `db:"title" json:"title"`
	ModelProvider   string             `db:"model_provider" json:"model_provider"`
	ProjectName     pgtype.Text        `db:"project_name" json:"project_name"`
	Visibility      string             `db:"visibility" json:"visibility"`
	SchemaVersion   string             `db:"schema_version" json:"schema_version"`
	PublishedAt     pgtype.Timestamptz `db:"published_at" json:"published_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ContentHash     pgtype.Text        `db:"content_hash" json:"content_hash"`
	LicenseID       pgtype.Text        `db:"license_id" json:"license_id"`
	AnnotationCount int64              `db:"annotation_count" json:"annotation_count"`
}

// Returns the full rows the requester may pull, encoding the
// canPullTranscript policy's two surviving clauses (owner OR group-shared with an
// APPROVED share to a group the requester is a member of). Public visibility and
// collective-owner preview are DELIBERATELY excluded (pull policy is narrower than
// canViewTranscript). This projects every column pullTranscriptInfo needs —
// including content_hash, the owner's github_username (users join), and a
// per-row annotation count (correlated subquery keyed on transcript UUID, matching
// CountTranscriptAnnotations) — in ONE query per page, so the list handler does
// not issue separate per-row transcript, content-hash, annotation-count, or owner
// lookups. Together with the count query, listing takes two database round trips
// instead of scaling with page size. Offset pagination (MVP). Newest-first by
// published_at for stable listing.
func (q *Queries) ListPullableTranscripts(ctx context.Context, arg ListPullableTranscriptsParams) ([]ListPullableTranscriptsRow, error) {
	rows, err := q.db.Query(ctx, listPullableTranscripts, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullableTranscriptsRow{}
	for rows.Next() {
		var i ListPullableTranscriptsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocalID,
			&i.OwnerID,
			&i.OwnerUsername,
			&i.Title,
			&i.ModelProvider,
			&i.ProjectName,
			&i.Visibility,
			&i.SchemaVersion,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.LicenseID,
			&i.AnnotationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPullableTranscriptsByIDs = `-- name: ListPullableTranscriptsByIDs :many
SELECT DISTINCT t.id, t.content_hash, t.local_id
FROM transcripts t
LEFT JOIN transcript_shares ts
    ON ts.transcript_id = t.id AND t.visibility = 'shared' AND ts.status = 'approved'
LEFT JOIN group_members gm ON gm.group_id = ts.group_id AND gm.user_id = $1
WHERE (t.owner_id = $1 OR gm.user_id = $1) AND t.id = ANY($2::uuid[])
`

type ListPullableTranscriptsByIDsParams struct {
	UserID        pgtype.UUID   `db:"user_id" json:"user_id"`
	TranscriptIds []pgtype.UUID `db:"transcript_ids" json:"transcript_ids"`
}

type ListPullableTranscriptsByIDsRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	ContentHash pgtype.Text `db:"content_hash" json:"content_hash"`
	LocalID     string      `db:"local_id" json:"local_id"`
}

// Pull skip-gate: of the client's requested transcript ids, the ones the caller
// may PULL, reusing the ListPullableTranscripts pull predicate (owner OR an
// approved group-share) narrowed to id = ANY($2). A requested id the caller may
// NOT pull is simply ABSENT from the result, so the handler withholds its
// currency by omission rather than emitting a per-id denial oracle. Projects the
// id, the served-blob content_hash (nullable), and the local_id used to link
// annotations. Keyed on the transcript id (PK), never on content_hash.
func (q *Queries) ListPullableTranscriptsByIDs(ctx context.Context, arg ListPullableTranscriptsByIDsParams) ([]ListPullableTranscriptsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listPullableTranscriptsByIDs, arg.UserID, arg.TranscriptIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPullableTranscriptsByIDsRow{}
	for rows.Next() {
		var i ListPullableTranscriptsByIDsRow
		if err := rows.Scan(&i.ID, &i.ContentHash, &i.LocalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptDescriptorsForRewrap = `-- name: ListTranscriptDescriptorsForRewrap :many
SELECT id, blob_key, wrapped_data_key, encryption_algorithm, key_version
FROM transcripts
WHERE key_version < $1
  AND (key_version > $2
       OR (key_version = $2 AND id > $3))
ORDER BY key_version, id
LIMIT $4
`

type ListTranscriptDescriptorsForRewrapParams struct {
	ActiveKeyVersion int32       `db:"active_key_version" json:"active_key_version"`
	AfterKeyVersion  int32       `db:"after_key_version" json:"after_key_version"`
	AfterID          pgtype.UUID `db:"after_id" json:"after_id"`
	BatchSize        int32       `db:"batch_size" json:"batch_size"`
}

type ListTranscriptDescriptorsForRewrapRow struct {
	ID                  pgtype.UUID `db:"id" json:"id"`
	BlobKey             string      `db:"blob_key" json:"blob_key"`
	WrappedDataKey      []byte      `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm string      `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion          int32       `db:"key_version" json:"key_version"`
}

func (q *Queries) ListTranscriptDescriptorsForRewrap(ctx context.Context, arg ListTranscriptDescriptorsForRewrapParams) ([]ListTranscriptDescriptorsForRewrapRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptDescriptorsForRewrap,
		arg.ActiveKeyVersion,
		arg.AfterKeyVersion,
		arg.AfterID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptDescriptorsForRewrapRow{}
	for rows.Next() {
		var i ListTranscriptDescriptorsForRewrapRow
		if err := rows.Scan(
			&i.ID,
			&i.BlobKey,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptsMissingContentHash = `-- name: ListTranscriptsMissingContentHash :many
SELECT id, blob_key, wrapped_data_key, encryption_algorithm, key_version, blob_size_bytes
FROM transcripts
WHERE content_hash IS NULL
ORDER BY published_at ASC, id
`

type ListTranscriptsMissingContentHashRow struct {
	ID                  pgtype.UUID `db:"id" json:"id"`
	BlobKey             string      `db:"blob_key" json:"blob_key"`
	WrappedDataKey      []byte      `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm string      `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion          int32       `db:"key_version" json:"key_version"`
	BlobSizeBytes       pgtype.Int8 `db:"blob_size_bytes" json:"blob_size_bytes"`
}

// Returns the complete immutable descriptor and nullable prior plaintext size
// needed by a descriptor-conditional identity backfill.
func (q *Queries) ListTranscriptsMissingContentHash(ctx context.Context) ([]ListTranscriptsMissingContentHashRow, error) {
	rows, err := q.db.Query(ctx, listTranscriptsMissingContentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTranscriptsMissingContentHashRow{}
	for rows.Next() {
		var i ListTranscriptsMissingContentHashRow
		if err := rows.Scan(
			&i.ID,
			&i.BlobKey,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
			&i.BlobSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTranscriptContentHash = `-- name: SetTranscriptContentHash :exec

UPDATE transcripts SET content_hash = $2 WHERE id = $1
`

type SetTranscriptContentHashParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	ContentHash pgtype.Text `db:"content_hash" json:"content_hash"`
}

// Pull and content-hash queries live in this dedicated source file so sqlc emits
// them into transcripts_pull.sql.go without colliding with transcripts.sql.go.
// This mirrors the annotations_push.sql source and generated-file layout.
// Records the server-computed hash of the served blob bytes.
// Called at publish (after the S3 upload), at migrate-on-read rewrite, and by the
// content-hash backfill job.
func (q *Queries) SetTranscriptContentHash(ctx context.Context, arg SetTranscriptContentHashParams) error {
	_, err := q.db.Exec(ctx, setTranscriptContentHash, arg.ID, arg.ContentHash)
	return err
}
