// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript_commits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTranscriptCommits = `-- name: DeleteTranscriptCommits :exec
DELETE FROM transcript_commits WHERE transcript_id = $1
`

// Removes all commit rows for a transcript. Used on re-publish to drop commits
// that are no longer present in the latest payload before re-inserting.
func (q *Queries) DeleteTranscriptCommits(ctx context.Context, transcriptID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTranscriptCommits, transcriptID)
	return err
}

const insertTranscriptCommits = `-- name: InsertTranscriptCommits :exec
INSERT INTO transcript_commits (
    transcript_id, commit_order, sha, message,
    author_name, author_email, additions, deletions,
    authored_at, committed_at
)
SELECT
    $1::uuid,
    r.commit_order, r.sha, r.message,
    r.author_name, r.author_email, r.additions, r.deletions,
    r.authored_at, r.committed_at
FROM jsonb_to_recordset($2::jsonb) AS r(
    commit_order int,
    sha text,
    message text,
    author_name text,
    author_email text,
    additions int,
    deletions int,
    authored_at timestamptz,
    committed_at timestamptz
)
ON CONFLICT (transcript_id, sha) DO UPDATE SET
    commit_order = EXCLUDED.commit_order,
    message      = EXCLUDED.message,
    author_name  = EXCLUDED.author_name,
    author_email = EXCLUDED.author_email,
    additions    = EXCLUDED.additions,
    deletions    = EXCLUDED.deletions,
    authored_at  = EXCLUDED.authored_at,
    committed_at = EXCLUDED.committed_at
`

type InsertTranscriptCommitsParams struct {
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Commits      []byte      `db:"commits" json:"commits"`
}

// Batched multi-row upsert of a transcript's commits in a SINGLE statement
// passes commits as one JSONB array expanded via jsonb_to_recordset, so the
// whole payload is one round trip instead of N
// per-row INSERTs. JSONB preserves SQL NULLs (a missing/null field maps to a
// NULL column), unlike parallel text[]/int[] arrays. Idempotent on
// (transcript_id, sha): a repeated SHA refreshes the row in place.
func (q *Queries) InsertTranscriptCommits(ctx context.Context, arg InsertTranscriptCommitsParams) error {
	_, err := q.db.Exec(ctx, insertTranscriptCommits, arg.TranscriptID, arg.Commits)
	return err
}

const listTranscriptCommits = `-- name: ListTranscriptCommits :many
SELECT id, transcript_id, commit_order, sha, message, author_name, author_email, additions, deletions, authored_at, committed_at, created_at FROM transcript_commits
WHERE transcript_id = $1
ORDER BY commit_order ASC, id ASC
`

// Returns every commit linked to a transcript, in payload order.
func (q *Queries) ListTranscriptCommits(ctx context.Context, transcriptID pgtype.UUID) ([]TranscriptCommit, error) {
	rows, err := q.db.Query(ctx, listTranscriptCommits, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptCommit{}
	for rows.Next() {
		var i TranscriptCommit
		if err := rows.Scan(
			&i.ID,
			&i.TranscriptID,
			&i.CommitOrder,
			&i.Sha,
			&i.Message,
			&i.AuthorName,
			&i.AuthorEmail,
			&i.Additions,
			&i.Deletions,
			&i.AuthoredAt,
			&i.CommittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
