// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcripts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOwnerTranscriptsInProject = `-- name: CountOwnerTranscriptsInProject :one
SELECT count(*)::bigint
FROM transcripts
WHERE owner_id = $1 AND project_hash = $2
`

type CountOwnerTranscriptsInProjectParams struct {
	OwnerID     pgtype.UUID `db:"owner_id" json:"owner_id"`
	ProjectHash string      `db:"project_hash" json:"project_hash"`
}

// Ownership probe for the project-correction endpoints: an owner may only name a
// project they have actually published into. It counts rather than returning a row
// because the caller needs the yes/no answer, not the transcripts.
func (q *Queries) CountOwnerTranscriptsInProject(ctx context.Context, arg CountOwnerTranscriptsInProjectParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerTranscriptsInProject, arg.OwnerID, arg.ProjectHash)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTranscript = `-- name: CreateTranscript :one
INSERT INTO transcripts (
    id, owner_id, local_id, title, description, visibility,
    model_provider, model_name, harness_version,
    session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version,
    parent_session_id, ingested_at, source_file_path, source_format,
    git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name,
    tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial,
    tokens_in, tokens_out, title_generated, outcome,
    files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio,
    m3_unique_tool_count, m4_error_recovery_count, m4_consecutive_error_max,
    m5_context_utilization_pct, m5_peak_context_tokens, m5_avg_message_tokens,
    m6_output_survival_pct, m6_lines_survived, m6_lines_total,
    m7_spec_word_count, m7_spec_has_examples, m7_spec_has_constraints,
    computed_at, compute_version, license_id,
    content_hash, wrapped_data_key, encryption_algorithm, key_version,
    session_origin
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31,
    $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46,
    $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61,
    $62, $63, $64, $65, $66, $67
) RETURNING id, owner_id, local_id, title, description, visibility, model_provider,
    model_name, harness_version, session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version, published_at, updated_at, parent_session_id,
    ingested_at, source_file_path, source_format, git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name, tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial, tokens_in, tokens_out,
    title_generated, outcome, files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio, m3_unique_tool_count,
    m4_error_recovery_count, m4_consecutive_error_max, m5_context_utilization_pct,
    m5_peak_context_tokens, m5_avg_message_tokens, m6_output_survival_pct,
    m6_lines_survived, m6_lines_total, m7_spec_word_count, m7_spec_has_examples,
    m7_spec_has_constraints, computed_at, compute_version, content_hash, license_id,
    wrapped_data_key, encryption_algorithm, key_version, accepted_request_operation_fingerprint, session_origin
`

type CreateTranscriptParams struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	OwnerID                 pgtype.UUID        `db:"owner_id" json:"owner_id"`
	LocalID                 string             `db:"local_id" json:"local_id"`
	Title                   pgtype.Text        `db:"title" json:"title"`
	Description             pgtype.Text        `db:"description" json:"description"`
	Visibility              string             `db:"visibility" json:"visibility"`
	ModelProvider           string             `db:"model_provider" json:"model_provider"`
	ModelName               pgtype.Text        `db:"model_name" json:"model_name"`
	HarnessVersion          pgtype.Text        `db:"harness_version" json:"harness_version"`
	SessionStart            pgtype.Timestamptz `db:"session_start" json:"session_start"`
	SessionEnd              pgtype.Timestamptz `db:"session_end" json:"session_end"`
	TurnCount               pgtype.Int4        `db:"turn_count" json:"turn_count"`
	TokenCount              pgtype.Int4        `db:"token_count" json:"token_count"`
	BlobKey                 string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes           pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	SchemaVersion           string             `db:"schema_version" json:"schema_version"`
	ParentSessionID         pgtype.Text        `db:"parent_session_id" json:"parent_session_id"`
	IngestedAt              pgtype.Timestamptz `db:"ingested_at" json:"ingested_at"`
	SourceFilePath          pgtype.Text        `db:"source_file_path" json:"source_file_path"`
	SourceFormat            pgtype.Text        `db:"source_format" json:"source_format"`
	GitBranch               pgtype.Text        `db:"git_branch" json:"git_branch"`
	GitRemote               pgtype.Text        `db:"git_remote" json:"git_remote"`
	GitWorktree             pgtype.Text        `db:"git_worktree" json:"git_worktree"`
	ProjectHash             string             `db:"project_hash" json:"project_hash"`
	ProjectPath             pgtype.Text        `db:"project_path" json:"project_path"`
	ProjectName             pgtype.Text        `db:"project_name" json:"project_name"`
	ToolCallCount           pgtype.Int4        `db:"tool_call_count" json:"tool_call_count"`
	SubagentCount           pgtype.Int4        `db:"subagent_count" json:"subagent_count"`
	DurationMs              pgtype.Int8        `db:"duration_ms" json:"duration_ms"`
	Subagents               []byte             `db:"subagents" json:"subagents"`
	DiagnosticsWarnings     []byte             `db:"diagnostics_warnings" json:"diagnostics_warnings"`
	DiagnosticsPartial      pgtype.Bool        `db:"diagnostics_partial" json:"diagnostics_partial"`
	TokensIn                pgtype.Int8        `db:"tokens_in" json:"tokens_in"`
	TokensOut               pgtype.Int8        `db:"tokens_out" json:"tokens_out"`
	TitleGenerated          pgtype.Text        `db:"title_generated" json:"title_generated"`
	Outcome                 pgtype.Text        `db:"outcome" json:"outcome"`
	FilesTouched            pgtype.Int4        `db:"files_touched" json:"files_touched"`
	LinesChanged            pgtype.Int4        `db:"lines_changed" json:"lines_changed"`
	RetryLoops              pgtype.Int4        `db:"retry_loops" json:"retry_loops"`
	RetryTokensWasted       pgtype.Int4        `db:"retry_tokens_wasted" json:"retry_tokens_wasted"`
	WithinSessionReverts    pgtype.Int4        `db:"within_session_reverts" json:"within_session_reverts"`
	SignalDensity           pgtype.Float4      `db:"signal_density" json:"signal_density"`
	SpecQualityScore        pgtype.Float4      `db:"spec_quality_score" json:"spec_quality_score"`
	ExplorationRatio        pgtype.Float4      `db:"exploration_ratio" json:"exploration_ratio"`
	ScopeBreadth            pgtype.Int4        `db:"scope_breadth" json:"scope_breadth"`
	DiscoveryTurns          pgtype.Int4        `db:"discovery_turns" json:"discovery_turns"`
	M2TokenOutcomeRatio     pgtype.Float4      `db:"m2_token_outcome_ratio" json:"m2_token_outcome_ratio"`
	M3UniqueToolCount       pgtype.Int4        `db:"m3_unique_tool_count" json:"m3_unique_tool_count"`
	M4ErrorRecoveryCount    pgtype.Int4        `db:"m4_error_recovery_count" json:"m4_error_recovery_count"`
	M4ConsecutiveErrorMax   pgtype.Int4        `db:"m4_consecutive_error_max" json:"m4_consecutive_error_max"`
	M5ContextUtilizationPct pgtype.Float4      `db:"m5_context_utilization_pct" json:"m5_context_utilization_pct"`
	M5PeakContextTokens     pgtype.Int4        `db:"m5_peak_context_tokens" json:"m5_peak_context_tokens"`
	M5AvgMessageTokens      pgtype.Int4        `db:"m5_avg_message_tokens" json:"m5_avg_message_tokens"`
	M6OutputSurvivalPct     pgtype.Float4      `db:"m6_output_survival_pct" json:"m6_output_survival_pct"`
	M6LinesSurvived         pgtype.Int4        `db:"m6_lines_survived" json:"m6_lines_survived"`
	M6LinesTotal            pgtype.Int4        `db:"m6_lines_total" json:"m6_lines_total"`
	M7SpecWordCount         pgtype.Int4        `db:"m7_spec_word_count" json:"m7_spec_word_count"`
	M7SpecHasExamples       pgtype.Bool        `db:"m7_spec_has_examples" json:"m7_spec_has_examples"`
	M7SpecHasConstraints    pgtype.Bool        `db:"m7_spec_has_constraints" json:"m7_spec_has_constraints"`
	ComputedAt              pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
	ComputeVersion          pgtype.Int4        `db:"compute_version" json:"compute_version"`
	LicenseID               pgtype.Text        `db:"license_id" json:"license_id"`
	ContentHash             pgtype.Text        `db:"content_hash" json:"content_hash"`
	WrappedDataKey          []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm     string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	SessionOrigin           string             `db:"session_origin" json:"session_origin"`
}

func (q *Queries) CreateTranscript(ctx context.Context, arg CreateTranscriptParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, createTranscript,
		arg.ID,
		arg.OwnerID,
		arg.LocalID,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.ModelProvider,
		arg.ModelName,
		arg.HarnessVersion,
		arg.SessionStart,
		arg.SessionEnd,
		arg.TurnCount,
		arg.TokenCount,
		arg.BlobKey,
		arg.BlobSizeBytes,
		arg.SchemaVersion,
		arg.ParentSessionID,
		arg.IngestedAt,
		arg.SourceFilePath,
		arg.SourceFormat,
		arg.GitBranch,
		arg.GitRemote,
		arg.GitWorktree,
		arg.ProjectHash,
		arg.ProjectPath,
		arg.ProjectName,
		arg.ToolCallCount,
		arg.SubagentCount,
		arg.DurationMs,
		arg.Subagents,
		arg.DiagnosticsWarnings,
		arg.DiagnosticsPartial,
		arg.TokensIn,
		arg.TokensOut,
		arg.TitleGenerated,
		arg.Outcome,
		arg.FilesTouched,
		arg.LinesChanged,
		arg.RetryLoops,
		arg.RetryTokensWasted,
		arg.WithinSessionReverts,
		arg.SignalDensity,
		arg.SpecQualityScore,
		arg.ExplorationRatio,
		arg.ScopeBreadth,
		arg.DiscoveryTurns,
		arg.M2TokenOutcomeRatio,
		arg.M3UniqueToolCount,
		arg.M4ErrorRecoveryCount,
		arg.M4ConsecutiveErrorMax,
		arg.M5ContextUtilizationPct,
		arg.M5PeakContextTokens,
		arg.M5AvgMessageTokens,
		arg.M6OutputSurvivalPct,
		arg.M6LinesSurvived,
		arg.M6LinesTotal,
		arg.M7SpecWordCount,
		arg.M7SpecHasExamples,
		arg.M7SpecHasConstraints,
		arg.ComputedAt,
		arg.ComputeVersion,
		arg.LicenseID,
		arg.ContentHash,
		arg.WrappedDataKey,
		arg.EncryptionAlgorithm,
		arg.KeyVersion,
		arg.SessionOrigin,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LocalID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ModelProvider,
		&i.ModelName,
		&i.HarnessVersion,
		&i.SessionStart,
		&i.SessionEnd,
		&i.TurnCount,
		&i.TokenCount,
		&i.BlobKey,
		&i.BlobSizeBytes,
		&i.SchemaVersion,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ParentSessionID,
		&i.IngestedAt,
		&i.SourceFilePath,
		&i.SourceFormat,
		&i.GitBranch,
		&i.GitRemote,
		&i.GitWorktree,
		&i.ProjectHash,
		&i.ProjectPath,
		&i.ProjectName,
		&i.ToolCallCount,
		&i.SubagentCount,
		&i.DurationMs,
		&i.Subagents,
		&i.DiagnosticsWarnings,
		&i.DiagnosticsPartial,
		&i.TokensIn,
		&i.TokensOut,
		&i.TitleGenerated,
		&i.Outcome,
		&i.FilesTouched,
		&i.LinesChanged,
		&i.RetryLoops,
		&i.RetryTokensWasted,
		&i.WithinSessionReverts,
		&i.SignalDensity,
		&i.SpecQualityScore,
		&i.ExplorationRatio,
		&i.ScopeBreadth,
		&i.DiscoveryTurns,
		&i.M2TokenOutcomeRatio,
		&i.M3UniqueToolCount,
		&i.M4ErrorRecoveryCount,
		&i.M4ConsecutiveErrorMax,
		&i.M5ContextUtilizationPct,
		&i.M5PeakContextTokens,
		&i.M5AvgMessageTokens,
		&i.M6OutputSurvivalPct,
		&i.M6LinesSurvived,
		&i.M6LinesTotal,
		&i.M7SpecWordCount,
		&i.M7SpecHasExamples,
		&i.M7SpecHasConstraints,
		&i.ComputedAt,
		&i.ComputeVersion,
		&i.ContentHash,
		&i.LicenseID,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
		&i.AcceptedRequestOperationFingerprint,
		&i.SessionOrigin,
	)
	return i, err
}

const deleteTranscript = `-- name: DeleteTranscript :exec
DELETE FROM transcripts WHERE id = $1
`

func (q *Queries) DeleteTranscript(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTranscript, id)
	return err
}

const getTranscriptByID = `-- name: GetTranscriptByID :one
SELECT id, owner_id, local_id, title, description, visibility, model_provider,
    model_name, harness_version, session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version, published_at, updated_at, parent_session_id,
    ingested_at, source_file_path, source_format, git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name, tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial, tokens_in, tokens_out,
    title_generated, outcome, files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio, m3_unique_tool_count,
    m4_error_recovery_count, m4_consecutive_error_max, m5_context_utilization_pct,
    m5_peak_context_tokens, m5_avg_message_tokens, m6_output_survival_pct,
    m6_lines_survived, m6_lines_total, m7_spec_word_count, m7_spec_has_examples,
    m7_spec_has_constraints, computed_at, compute_version, content_hash, license_id,
    wrapped_data_key, encryption_algorithm, key_version, accepted_request_operation_fingerprint, session_origin
FROM transcripts WHERE id = $1
`

func (q *Queries) GetTranscriptByID(ctx context.Context, id pgtype.UUID) (Transcript, error) {
	row := q.db.QueryRow(ctx, getTranscriptByID, id)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LocalID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ModelProvider,
		&i.ModelName,
		&i.HarnessVersion,
		&i.SessionStart,
		&i.SessionEnd,
		&i.TurnCount,
		&i.TokenCount,
		&i.BlobKey,
		&i.BlobSizeBytes,
		&i.SchemaVersion,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ParentSessionID,
		&i.IngestedAt,
		&i.SourceFilePath,
		&i.SourceFormat,
		&i.GitBranch,
		&i.GitRemote,
		&i.GitWorktree,
		&i.ProjectHash,
		&i.ProjectPath,
		&i.ProjectName,
		&i.ToolCallCount,
		&i.SubagentCount,
		&i.DurationMs,
		&i.Subagents,
		&i.DiagnosticsWarnings,
		&i.DiagnosticsPartial,
		&i.TokensIn,
		&i.TokensOut,
		&i.TitleGenerated,
		&i.Outcome,
		&i.FilesTouched,
		&i.LinesChanged,
		&i.RetryLoops,
		&i.RetryTokensWasted,
		&i.WithinSessionReverts,
		&i.SignalDensity,
		&i.SpecQualityScore,
		&i.ExplorationRatio,
		&i.ScopeBreadth,
		&i.DiscoveryTurns,
		&i.M2TokenOutcomeRatio,
		&i.M3UniqueToolCount,
		&i.M4ErrorRecoveryCount,
		&i.M4ConsecutiveErrorMax,
		&i.M5ContextUtilizationPct,
		&i.M5PeakContextTokens,
		&i.M5AvgMessageTokens,
		&i.M6OutputSurvivalPct,
		&i.M6LinesSurvived,
		&i.M6LinesTotal,
		&i.M7SpecWordCount,
		&i.M7SpecHasExamples,
		&i.M7SpecHasConstraints,
		&i.ComputedAt,
		&i.ComputeVersion,
		&i.ContentHash,
		&i.LicenseID,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
		&i.AcceptedRequestOperationFingerprint,
		&i.SessionOrigin,
	)
	return i, err
}

const getTranscriptGovernanceForUpdate = `-- name: GetTranscriptGovernanceForUpdate :one
SELECT id, title, description, visibility, license_id
FROM transcripts WHERE id = $1 FOR UPDATE
`

type GetTranscriptGovernanceForUpdateRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Title       pgtype.Text `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Visibility  string      `db:"visibility" json:"visibility"`
	LicenseID   pgtype.Text `db:"license_id" json:"license_id"`
}

// Locks the row (FOR UPDATE) so a mutation can resolve a partial patch / pin
// republish state against the pre-image under one lock, serialising concurrent
// edits to the same transcript. NARROW on purpose: the row lock is column-list-
// independent, and only these five fields are ever resolved — the old SELECT *
// hauled ~60 columns (incl. JSONB) per edit for nothing. The audit events
// themselves are written by the migration-026 triggers, not by callers of this.
func (q *Queries) GetTranscriptGovernanceForUpdate(ctx context.Context, id pgtype.UUID) (GetTranscriptGovernanceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getTranscriptGovernanceForUpdate, id)
	var i GetTranscriptGovernanceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.LicenseID,
	)
	return i, err
}

const getTranscriptIDByOwnerAndLocalID = `-- name: GetTranscriptIDByOwnerAndLocalID :one
SELECT id FROM transcripts WHERE owner_id = $1 AND local_id = $2
`

type GetTranscriptIDByOwnerAndLocalIDParams struct {
	OwnerID pgtype.UUID `db:"owner_id" json:"owner_id"`
	LocalID string      `db:"local_id" json:"local_id"`
}

// Publish-path existence probe (create vs re-publish). ID-only ON PURPOSE: the
// governance pre-image comes from the LOCKED narrow read inside the txn
// (GetTranscriptGovernanceForUpdate); a wide unlocked read here would be dead
// weight superseded under the lock.
func (q *Queries) GetTranscriptIDByOwnerAndLocalID(ctx context.Context, arg GetTranscriptIDByOwnerAndLocalIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getTranscriptIDByOwnerAndLocalID, arg.OwnerID, arg.LocalID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listOwnerProjectIdentities = `-- name: ListOwnerProjectIdentities :many
SELECT
    t.owner_id,
    t.project_hash,
    COALESCE(o.value, '')::text AS override_name,
    COALESCE(
        array_agg(t.project_name ORDER BY t.published_at DESC, t.id)
            FILTER (WHERE t.project_name IS NOT NULL AND t.project_name <> ''),
        ARRAY[]::text[]
    )::text[] AS project_names,
    COALESCE(
        (array_agg(t.git_remote ORDER BY t.published_at DESC, t.id)
            FILTER (WHERE t.git_remote IS NOT NULL AND t.git_remote <> ''))[1],
        ''
    )::text AS git_remote,
    count(*)::bigint AS transcript_count
FROM transcripts t
LEFT JOIN owner_overrides o
       ON o.owner_id = t.owner_id
      AND o.target_kind = 'project'
      AND o.field = 'display_name'
      AND o.target_key = t.project_hash
WHERE t.owner_id = ANY($1::uuid[])
  AND t.project_hash = ANY($2::text[])
GROUP BY t.owner_id, t.project_hash, o.value
ORDER BY t.owner_id, t.project_hash
`

type ListOwnerProjectIdentitiesParams struct {
	OwnerIds      []pgtype.UUID `db:"owner_ids" json:"owner_ids"`
	ProjectHashes []string      `db:"project_hashes" json:"project_hashes"`
}

type ListOwnerProjectIdentitiesRow struct {
	OwnerID         pgtype.UUID `db:"owner_id" json:"owner_id"`
	ProjectHash     string      `db:"project_hash" json:"project_hash"`
	OverrideName    string      `db:"override_name" json:"override_name"`
	ProjectNames    []string    `db:"project_names" json:"project_names"`
	GitRemote       string      `db:"git_remote" json:"git_remote"`
	TranscriptCount int64       `db:"transcript_count" json:"transcript_count"`
}

// One row per (owner_id, project_hash) pair carrying every piece of evidence the
// display-name resolver needs, aggregated in ONE statement so a page of transcripts
// spanning many owners and many projects never issues a query per row.
//
// The candidate project names are returned as an ORDERED ARRAY rather than as a
// pre-classified "consented name" and "privacy label" pair on purpose: telling those
// two apart is the job of projectname.IsPrivacyLabel, and expressing that rule a
// second time as a SQL regex would create two definitions of the same thing that
// must stay identical forever. The ordering (published_at DESC, then id) is the
// deterministic pick the resolver's contract requires, so the caller only has to
// walk the array and take the first name of each class.
//
// The override join is narrowed to the single writable pair, ('project',
// 'display_name'); the table reserves other pairs for later fields, and this read
// must not start returning one the application does not implement.
func (q *Queries) ListOwnerProjectIdentities(ctx context.Context, arg ListOwnerProjectIdentitiesParams) ([]ListOwnerProjectIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listOwnerProjectIdentities, arg.OwnerIds, arg.ProjectHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerProjectIdentitiesRow{}
	for rows.Next() {
		var i ListOwnerProjectIdentitiesRow
		if err := rows.Scan(
			&i.OwnerID,
			&i.ProjectHash,
			&i.OverrideName,
			&i.ProjectNames,
			&i.GitRemote,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTranscriptsForViewer = `-- name: ListProjectTranscriptsForViewer :many
SELECT t.id, t.owner_id, t.local_id, t.title, t.description, t.visibility, t.model_provider,
    t.model_name, t.harness_version, t.session_start, t.session_end, t.turn_count, t.token_count,
    t.blob_key, t.blob_size_bytes, t.schema_version, t.published_at, t.updated_at, t.parent_session_id,
    t.ingested_at, t.source_file_path, t.source_format, t.git_branch, t.git_remote, t.git_worktree,
    t.project_hash, t.project_path, t.project_name, t.tool_call_count, t.subagent_count, t.duration_ms,
    t.subagents, t.diagnostics_warnings, t.diagnostics_partial, t.tokens_in, t.tokens_out,
    t.title_generated, t.outcome, t.files_touched, t.lines_changed, t.retry_loops, t.retry_tokens_wasted,
    t.within_session_reverts, t.signal_density, t.spec_quality_score, t.exploration_ratio,
    t.scope_breadth, t.discovery_turns, t.m2_token_outcome_ratio, t.m3_unique_tool_count,
    t.m4_error_recovery_count, t.m4_consecutive_error_max, t.m5_context_utilization_pct,
    t.m5_peak_context_tokens, t.m5_avg_message_tokens, t.m6_output_survival_pct,
    t.m6_lines_survived, t.m6_lines_total, t.m7_spec_word_count, t.m7_spec_has_examples,
    t.m7_spec_has_constraints, t.computed_at, t.compute_version, t.content_hash, t.license_id,
    t.wrapped_data_key, t.encryption_algorithm, t.key_version,
    t.accepted_request_operation_fingerprint, t.session_origin
FROM transcripts t
WHERE t.owner_id = $1
  AND t.project_hash = $2
  AND (
        t.visibility = 'public'
        OR t.owner_id = $3
        OR (t.visibility = 'shared' AND EXISTS (
                SELECT 1
                FROM transcript_shares ts
                JOIN group_members gm ON gm.group_id = ts.group_id
                WHERE ts.transcript_id = t.id AND gm.user_id = $3))
      )
ORDER BY t.published_at DESC, t.id DESC
`

type ListProjectTranscriptsForViewerParams struct {
	OwnerID     pgtype.UUID `db:"owner_id" json:"owner_id"`
	ProjectHash string      `db:"project_hash" json:"project_hash"`
	ViewerID    pgtype.UUID `db:"viewer_id" json:"viewer_id"`
}

// The transcripts of one owner's project that one viewer may see. The predicate is
// the SHIPPED web read policy, character-for-character the same disjunction the
// discovery listing applies (public, or the viewer's own, or shared into a
// collective the viewer belongs to); this route deliberately introduces no new
// visibility rule of its own. An anonymous viewer passes a NULL id, which makes the
// owner and membership arms unsatisfiable and leaves only the public arm.
//
// The membership arm is an EXISTS rather than a join so a transcript shared into
// several of the viewer's collectives is still returned exactly once, with no
// DISTINCT over the whole wide row.
func (q *Queries) ListProjectTranscriptsForViewer(ctx context.Context, arg ListProjectTranscriptsForViewerParams) ([]Transcript, error) {
	rows, err := q.db.Query(ctx, listProjectTranscriptsForViewer, arg.OwnerID, arg.ProjectHash, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transcript{}
	for rows.Next() {
		var i Transcript
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.LocalID,
			&i.Title,
			&i.Description,
			&i.Visibility,
			&i.ModelProvider,
			&i.ModelName,
			&i.HarnessVersion,
			&i.SessionStart,
			&i.SessionEnd,
			&i.TurnCount,
			&i.TokenCount,
			&i.BlobKey,
			&i.BlobSizeBytes,
			&i.SchemaVersion,
			&i.PublishedAt,
			&i.UpdatedAt,
			&i.ParentSessionID,
			&i.IngestedAt,
			&i.SourceFilePath,
			&i.SourceFormat,
			&i.GitBranch,
			&i.GitRemote,
			&i.GitWorktree,
			&i.ProjectHash,
			&i.ProjectPath,
			&i.ProjectName,
			&i.ToolCallCount,
			&i.SubagentCount,
			&i.DurationMs,
			&i.Subagents,
			&i.DiagnosticsWarnings,
			&i.DiagnosticsPartial,
			&i.TokensIn,
			&i.TokensOut,
			&i.TitleGenerated,
			&i.Outcome,
			&i.FilesTouched,
			&i.LinesChanged,
			&i.RetryLoops,
			&i.RetryTokensWasted,
			&i.WithinSessionReverts,
			&i.SignalDensity,
			&i.SpecQualityScore,
			&i.ExplorationRatio,
			&i.ScopeBreadth,
			&i.DiscoveryTurns,
			&i.M2TokenOutcomeRatio,
			&i.M3UniqueToolCount,
			&i.M4ErrorRecoveryCount,
			&i.M4ConsecutiveErrorMax,
			&i.M5ContextUtilizationPct,
			&i.M5PeakContextTokens,
			&i.M5AvgMessageTokens,
			&i.M6OutputSurvivalPct,
			&i.M6LinesSurvived,
			&i.M6LinesTotal,
			&i.M7SpecWordCount,
			&i.M7SpecHasExamples,
			&i.M7SpecHasConstraints,
			&i.ComputedAt,
			&i.ComputeVersion,
			&i.ContentHash,
			&i.LicenseID,
			&i.WrappedDataKey,
			&i.EncryptionAlgorithm,
			&i.KeyVersion,
			&i.AcceptedRequestOperationFingerprint,
			&i.SessionOrigin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAcceptedRequestOperationFingerprint = `-- name: SetAcceptedRequestOperationFingerprint :exec
UPDATE transcripts
SET accepted_request_operation_fingerprint = $2
WHERE id = $1
`

type SetAcceptedRequestOperationFingerprintParams struct {
	ID                                  pgtype.UUID `db:"id" json:"id"`
	AcceptedRequestOperationFingerprint pgtype.Text `db:"accepted_request_operation_fingerprint" json:"accepted_request_operation_fingerprint"`
}

func (q *Queries) SetAcceptedRequestOperationFingerprint(ctx context.Context, arg SetAcceptedRequestOperationFingerprintParams) error {
	_, err := q.db.Exec(ctx, setAcceptedRequestOperationFingerprint, arg.ID, arg.AcceptedRequestOperationFingerprint)
	return err
}

const updateTranscriptByOwnerAndLocalID = `-- name: UpdateTranscriptByOwnerAndLocalID :one
UPDATE transcripts SET
    title = $3,
    description = $4,
    visibility = $5,
    model_provider = $6,
    model_name = $7,
    harness_version = $8,
    session_start = $9,
    session_end = $10,
    turn_count = $11,
    token_count = $12,
    blob_key = $13,
    blob_size_bytes = $14,
    schema_version = $15,
    parent_session_id = $16,
    ingested_at = $17,
    source_file_path = $18,
    source_format = $19,
    git_branch = $20,
    git_remote = $21,
    git_worktree = $22,
    project_hash = $23,
    project_path = $24,
    project_name = $25,
    tool_call_count = $26,
    subagent_count = $27,
    duration_ms = $28,
    subagents = $29,
    diagnostics_warnings = $30,
    diagnostics_partial = $31,
    tokens_in = $32,
    tokens_out = $33,
    title_generated = $34,
    outcome = $35,
    files_touched = $36,
    lines_changed = $37,
    retry_loops = $38,
    retry_tokens_wasted = $39,
    within_session_reverts = $40,
    signal_density = $41,
    spec_quality_score = $42,
    exploration_ratio = $43,
    scope_breadth = $44,
    discovery_turns = $45,
    m2_token_outcome_ratio = $46,
    m3_unique_tool_count = $47,
    m4_error_recovery_count = $48,
    m4_consecutive_error_max = $49,
    m5_context_utilization_pct = $50,
    m5_peak_context_tokens = $51,
    m5_avg_message_tokens = $52,
    m6_output_survival_pct = $53,
    m6_lines_survived = $54,
    m6_lines_total = $55,
    m7_spec_word_count = $56,
    m7_spec_has_examples = $57,
    m7_spec_has_constraints = $58,
    computed_at = $59,
    compute_version = $60,
    license_id = $61,
    content_hash = $62,
    wrapped_data_key = $63,
    encryption_algorithm = $64,
    key_version = $65,
    session_origin = $66,
    updated_at = now()
WHERE owner_id = $1 AND local_id = $2
RETURNING id, owner_id, local_id, title, description, visibility, model_provider,
    model_name, harness_version, session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version, published_at, updated_at, parent_session_id,
    ingested_at, source_file_path, source_format, git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name, tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial, tokens_in, tokens_out,
    title_generated, outcome, files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio, m3_unique_tool_count,
    m4_error_recovery_count, m4_consecutive_error_max, m5_context_utilization_pct,
    m5_peak_context_tokens, m5_avg_message_tokens, m6_output_survival_pct,
    m6_lines_survived, m6_lines_total, m7_spec_word_count, m7_spec_has_examples,
    m7_spec_has_constraints, computed_at, compute_version, content_hash, license_id,
    wrapped_data_key, encryption_algorithm, key_version, accepted_request_operation_fingerprint, session_origin
`

type UpdateTranscriptByOwnerAndLocalIDParams struct {
	OwnerID                 pgtype.UUID        `db:"owner_id" json:"owner_id"`
	LocalID                 string             `db:"local_id" json:"local_id"`
	Title                   pgtype.Text        `db:"title" json:"title"`
	Description             pgtype.Text        `db:"description" json:"description"`
	Visibility              string             `db:"visibility" json:"visibility"`
	ModelProvider           string             `db:"model_provider" json:"model_provider"`
	ModelName               pgtype.Text        `db:"model_name" json:"model_name"`
	HarnessVersion          pgtype.Text        `db:"harness_version" json:"harness_version"`
	SessionStart            pgtype.Timestamptz `db:"session_start" json:"session_start"`
	SessionEnd              pgtype.Timestamptz `db:"session_end" json:"session_end"`
	TurnCount               pgtype.Int4        `db:"turn_count" json:"turn_count"`
	TokenCount              pgtype.Int4        `db:"token_count" json:"token_count"`
	BlobKey                 string             `db:"blob_key" json:"blob_key"`
	BlobSizeBytes           pgtype.Int8        `db:"blob_size_bytes" json:"blob_size_bytes"`
	SchemaVersion           string             `db:"schema_version" json:"schema_version"`
	ParentSessionID         pgtype.Text        `db:"parent_session_id" json:"parent_session_id"`
	IngestedAt              pgtype.Timestamptz `db:"ingested_at" json:"ingested_at"`
	SourceFilePath          pgtype.Text        `db:"source_file_path" json:"source_file_path"`
	SourceFormat            pgtype.Text        `db:"source_format" json:"source_format"`
	GitBranch               pgtype.Text        `db:"git_branch" json:"git_branch"`
	GitRemote               pgtype.Text        `db:"git_remote" json:"git_remote"`
	GitWorktree             pgtype.Text        `db:"git_worktree" json:"git_worktree"`
	ProjectHash             string             `db:"project_hash" json:"project_hash"`
	ProjectPath             pgtype.Text        `db:"project_path" json:"project_path"`
	ProjectName             pgtype.Text        `db:"project_name" json:"project_name"`
	ToolCallCount           pgtype.Int4        `db:"tool_call_count" json:"tool_call_count"`
	SubagentCount           pgtype.Int4        `db:"subagent_count" json:"subagent_count"`
	DurationMs              pgtype.Int8        `db:"duration_ms" json:"duration_ms"`
	Subagents               []byte             `db:"subagents" json:"subagents"`
	DiagnosticsWarnings     []byte             `db:"diagnostics_warnings" json:"diagnostics_warnings"`
	DiagnosticsPartial      pgtype.Bool        `db:"diagnostics_partial" json:"diagnostics_partial"`
	TokensIn                pgtype.Int8        `db:"tokens_in" json:"tokens_in"`
	TokensOut               pgtype.Int8        `db:"tokens_out" json:"tokens_out"`
	TitleGenerated          pgtype.Text        `db:"title_generated" json:"title_generated"`
	Outcome                 pgtype.Text        `db:"outcome" json:"outcome"`
	FilesTouched            pgtype.Int4        `db:"files_touched" json:"files_touched"`
	LinesChanged            pgtype.Int4        `db:"lines_changed" json:"lines_changed"`
	RetryLoops              pgtype.Int4        `db:"retry_loops" json:"retry_loops"`
	RetryTokensWasted       pgtype.Int4        `db:"retry_tokens_wasted" json:"retry_tokens_wasted"`
	WithinSessionReverts    pgtype.Int4        `db:"within_session_reverts" json:"within_session_reverts"`
	SignalDensity           pgtype.Float4      `db:"signal_density" json:"signal_density"`
	SpecQualityScore        pgtype.Float4      `db:"spec_quality_score" json:"spec_quality_score"`
	ExplorationRatio        pgtype.Float4      `db:"exploration_ratio" json:"exploration_ratio"`
	ScopeBreadth            pgtype.Int4        `db:"scope_breadth" json:"scope_breadth"`
	DiscoveryTurns          pgtype.Int4        `db:"discovery_turns" json:"discovery_turns"`
	M2TokenOutcomeRatio     pgtype.Float4      `db:"m2_token_outcome_ratio" json:"m2_token_outcome_ratio"`
	M3UniqueToolCount       pgtype.Int4        `db:"m3_unique_tool_count" json:"m3_unique_tool_count"`
	M4ErrorRecoveryCount    pgtype.Int4        `db:"m4_error_recovery_count" json:"m4_error_recovery_count"`
	M4ConsecutiveErrorMax   pgtype.Int4        `db:"m4_consecutive_error_max" json:"m4_consecutive_error_max"`
	M5ContextUtilizationPct pgtype.Float4      `db:"m5_context_utilization_pct" json:"m5_context_utilization_pct"`
	M5PeakContextTokens     pgtype.Int4        `db:"m5_peak_context_tokens" json:"m5_peak_context_tokens"`
	M5AvgMessageTokens      pgtype.Int4        `db:"m5_avg_message_tokens" json:"m5_avg_message_tokens"`
	M6OutputSurvivalPct     pgtype.Float4      `db:"m6_output_survival_pct" json:"m6_output_survival_pct"`
	M6LinesSurvived         pgtype.Int4        `db:"m6_lines_survived" json:"m6_lines_survived"`
	M6LinesTotal            pgtype.Int4        `db:"m6_lines_total" json:"m6_lines_total"`
	M7SpecWordCount         pgtype.Int4        `db:"m7_spec_word_count" json:"m7_spec_word_count"`
	M7SpecHasExamples       pgtype.Bool        `db:"m7_spec_has_examples" json:"m7_spec_has_examples"`
	M7SpecHasConstraints    pgtype.Bool        `db:"m7_spec_has_constraints" json:"m7_spec_has_constraints"`
	ComputedAt              pgtype.Timestamptz `db:"computed_at" json:"computed_at"`
	ComputeVersion          pgtype.Int4        `db:"compute_version" json:"compute_version"`
	LicenseID               pgtype.Text        `db:"license_id" json:"license_id"`
	ContentHash             pgtype.Text        `db:"content_hash" json:"content_hash"`
	WrappedDataKey          []byte             `db:"wrapped_data_key" json:"wrapped_data_key"`
	EncryptionAlgorithm     string             `db:"encryption_algorithm" json:"encryption_algorithm"`
	KeyVersion              int32              `db:"key_version" json:"key_version"`
	SessionOrigin           string             `db:"session_origin" json:"session_origin"`
}

func (q *Queries) UpdateTranscriptByOwnerAndLocalID(ctx context.Context, arg UpdateTranscriptByOwnerAndLocalIDParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, updateTranscriptByOwnerAndLocalID,
		arg.OwnerID,
		arg.LocalID,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.ModelProvider,
		arg.ModelName,
		arg.HarnessVersion,
		arg.SessionStart,
		arg.SessionEnd,
		arg.TurnCount,
		arg.TokenCount,
		arg.BlobKey,
		arg.BlobSizeBytes,
		arg.SchemaVersion,
		arg.ParentSessionID,
		arg.IngestedAt,
		arg.SourceFilePath,
		arg.SourceFormat,
		arg.GitBranch,
		arg.GitRemote,
		arg.GitWorktree,
		arg.ProjectHash,
		arg.ProjectPath,
		arg.ProjectName,
		arg.ToolCallCount,
		arg.SubagentCount,
		arg.DurationMs,
		arg.Subagents,
		arg.DiagnosticsWarnings,
		arg.DiagnosticsPartial,
		arg.TokensIn,
		arg.TokensOut,
		arg.TitleGenerated,
		arg.Outcome,
		arg.FilesTouched,
		arg.LinesChanged,
		arg.RetryLoops,
		arg.RetryTokensWasted,
		arg.WithinSessionReverts,
		arg.SignalDensity,
		arg.SpecQualityScore,
		arg.ExplorationRatio,
		arg.ScopeBreadth,
		arg.DiscoveryTurns,
		arg.M2TokenOutcomeRatio,
		arg.M3UniqueToolCount,
		arg.M4ErrorRecoveryCount,
		arg.M4ConsecutiveErrorMax,
		arg.M5ContextUtilizationPct,
		arg.M5PeakContextTokens,
		arg.M5AvgMessageTokens,
		arg.M6OutputSurvivalPct,
		arg.M6LinesSurvived,
		arg.M6LinesTotal,
		arg.M7SpecWordCount,
		arg.M7SpecHasExamples,
		arg.M7SpecHasConstraints,
		arg.ComputedAt,
		arg.ComputeVersion,
		arg.LicenseID,
		arg.ContentHash,
		arg.WrappedDataKey,
		arg.EncryptionAlgorithm,
		arg.KeyVersion,
		arg.SessionOrigin,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LocalID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ModelProvider,
		&i.ModelName,
		&i.HarnessVersion,
		&i.SessionStart,
		&i.SessionEnd,
		&i.TurnCount,
		&i.TokenCount,
		&i.BlobKey,
		&i.BlobSizeBytes,
		&i.SchemaVersion,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ParentSessionID,
		&i.IngestedAt,
		&i.SourceFilePath,
		&i.SourceFormat,
		&i.GitBranch,
		&i.GitRemote,
		&i.GitWorktree,
		&i.ProjectHash,
		&i.ProjectPath,
		&i.ProjectName,
		&i.ToolCallCount,
		&i.SubagentCount,
		&i.DurationMs,
		&i.Subagents,
		&i.DiagnosticsWarnings,
		&i.DiagnosticsPartial,
		&i.TokensIn,
		&i.TokensOut,
		&i.TitleGenerated,
		&i.Outcome,
		&i.FilesTouched,
		&i.LinesChanged,
		&i.RetryLoops,
		&i.RetryTokensWasted,
		&i.WithinSessionReverts,
		&i.SignalDensity,
		&i.SpecQualityScore,
		&i.ExplorationRatio,
		&i.ScopeBreadth,
		&i.DiscoveryTurns,
		&i.M2TokenOutcomeRatio,
		&i.M3UniqueToolCount,
		&i.M4ErrorRecoveryCount,
		&i.M4ConsecutiveErrorMax,
		&i.M5ContextUtilizationPct,
		&i.M5PeakContextTokens,
		&i.M5AvgMessageTokens,
		&i.M6OutputSurvivalPct,
		&i.M6LinesSurvived,
		&i.M6LinesTotal,
		&i.M7SpecWordCount,
		&i.M7SpecHasExamples,
		&i.M7SpecHasConstraints,
		&i.ComputedAt,
		&i.ComputeVersion,
		&i.ContentHash,
		&i.LicenseID,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
		&i.AcceptedRequestOperationFingerprint,
		&i.SessionOrigin,
	)
	return i, err
}

const updateTranscriptMetadata = `-- name: UpdateTranscriptMetadata :one
UPDATE transcripts SET
    title = $2,
    description = $3,
    visibility = $4,
    license_id = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, owner_id, local_id, title, description, visibility, model_provider,
    model_name, harness_version, session_start, session_end, turn_count, token_count,
    blob_key, blob_size_bytes, schema_version, published_at, updated_at, parent_session_id,
    ingested_at, source_file_path, source_format, git_branch, git_remote, git_worktree,
    project_hash, project_path, project_name, tool_call_count, subagent_count, duration_ms,
    subagents, diagnostics_warnings, diagnostics_partial, tokens_in, tokens_out,
    title_generated, outcome, files_touched, lines_changed, retry_loops, retry_tokens_wasted,
    within_session_reverts, signal_density, spec_quality_score, exploration_ratio,
    scope_breadth, discovery_turns, m2_token_outcome_ratio, m3_unique_tool_count,
    m4_error_recovery_count, m4_consecutive_error_max, m5_context_utilization_pct,
    m5_peak_context_tokens, m5_avg_message_tokens, m6_output_survival_pct,
    m6_lines_survived, m6_lines_total, m7_spec_word_count, m7_spec_has_examples,
    m7_spec_has_constraints, computed_at, compute_version, content_hash, license_id,
    wrapped_data_key, encryption_algorithm, key_version, accepted_request_operation_fingerprint, session_origin
`

type UpdateTranscriptMetadataParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Title       pgtype.Text `db:"title" json:"title"`
	Description pgtype.Text `db:"description" json:"description"`
	Visibility  string      `db:"visibility" json:"visibility"`
	LicenseID   pgtype.Text `db:"license_id" json:"license_id"`
}

func (q *Queries) UpdateTranscriptMetadata(ctx context.Context, arg UpdateTranscriptMetadataParams) (Transcript, error) {
	row := q.db.QueryRow(ctx, updateTranscriptMetadata,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.LicenseID,
	)
	var i Transcript
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.LocalID,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.ModelProvider,
		&i.ModelName,
		&i.HarnessVersion,
		&i.SessionStart,
		&i.SessionEnd,
		&i.TurnCount,
		&i.TokenCount,
		&i.BlobKey,
		&i.BlobSizeBytes,
		&i.SchemaVersion,
		&i.PublishedAt,
		&i.UpdatedAt,
		&i.ParentSessionID,
		&i.IngestedAt,
		&i.SourceFilePath,
		&i.SourceFormat,
		&i.GitBranch,
		&i.GitRemote,
		&i.GitWorktree,
		&i.ProjectHash,
		&i.ProjectPath,
		&i.ProjectName,
		&i.ToolCallCount,
		&i.SubagentCount,
		&i.DurationMs,
		&i.Subagents,
		&i.DiagnosticsWarnings,
		&i.DiagnosticsPartial,
		&i.TokensIn,
		&i.TokensOut,
		&i.TitleGenerated,
		&i.Outcome,
		&i.FilesTouched,
		&i.LinesChanged,
		&i.RetryLoops,
		&i.RetryTokensWasted,
		&i.WithinSessionReverts,
		&i.SignalDensity,
		&i.SpecQualityScore,
		&i.ExplorationRatio,
		&i.ScopeBreadth,
		&i.DiscoveryTurns,
		&i.M2TokenOutcomeRatio,
		&i.M3UniqueToolCount,
		&i.M4ErrorRecoveryCount,
		&i.M4ConsecutiveErrorMax,
		&i.M5ContextUtilizationPct,
		&i.M5PeakContextTokens,
		&i.M5AvgMessageTokens,
		&i.M6OutputSurvivalPct,
		&i.M6LinesSurvived,
		&i.M6LinesTotal,
		&i.M7SpecWordCount,
		&i.M7SpecHasExamples,
		&i.M7SpecHasConstraints,
		&i.ComputedAt,
		&i.ComputeVersion,
		&i.ContentHash,
		&i.LicenseID,
		&i.WrappedDataKey,
		&i.EncryptionAlgorithm,
		&i.KeyVersion,
		&i.AcceptedRequestOperationFingerprint,
		&i.SessionOrigin,
	)
	return i, err
}
