// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcript_associations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertTranscriptAssociations = `-- name: InsertTranscriptAssociations :exec
INSERT INTO transcript_associations (
    owner_id, association_id, transcript_id, observed_commit_sha
)
SELECT
    $1::uuid,
    item.association_id,
    $2::uuid,
    item.observed_commit_sha
FROM jsonb_to_recordset($3::jsonb) AS item(
    association_id text,
    observed_commit_sha text
)
`

type InsertTranscriptAssociationsParams struct {
	OwnerID      pgtype.UUID `db:"owner_id" json:"owner_id"`
	TranscriptID pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	Items        []byte      `db:"items" json:"items"`
}

func (q *Queries) InsertTranscriptAssociations(ctx context.Context, arg InsertTranscriptAssociationsParams) error {
	_, err := q.db.Exec(ctx, insertTranscriptAssociations, arg.OwnerID, arg.TranscriptID, arg.Items)
	return err
}

const listTranscriptAssociationIDsByOwner = `-- name: ListTranscriptAssociationIDsByOwner :many
SELECT association_id
FROM transcript_associations
WHERE owner_id = $1
  AND association_id = ANY($2::text[])
`

type ListTranscriptAssociationIDsByOwnerParams struct {
	OwnerID        pgtype.UUID `db:"owner_id" json:"owner_id"`
	AssociationIds []string    `db:"association_ids" json:"association_ids"`
}

func (q *Queries) ListTranscriptAssociationIDsByOwner(ctx context.Context, arg ListTranscriptAssociationIDsByOwnerParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listTranscriptAssociationIDsByOwner, arg.OwnerID, arg.AssociationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var association_id string
		if err := rows.Scan(&association_id); err != nil {
			return nil, err
		}
		items = append(items, association_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptAssociationsByOwnerAndIDs = `-- name: ListTranscriptAssociationsByOwnerAndIDs :many
SELECT owner_id, association_id, transcript_id, observed_commit_sha, created_at FROM transcript_associations
WHERE owner_id = $1
  AND association_id = ANY($2::text[])
`

type ListTranscriptAssociationsByOwnerAndIDsParams struct {
	OwnerID        pgtype.UUID `db:"owner_id" json:"owner_id"`
	AssociationIds []string    `db:"association_ids" json:"association_ids"`
}

func (q *Queries) ListTranscriptAssociationsByOwnerAndIDs(ctx context.Context, arg ListTranscriptAssociationsByOwnerAndIDsParams) ([]TranscriptAssociation, error) {
	rows, err := q.db.Query(ctx, listTranscriptAssociationsByOwnerAndIDs, arg.OwnerID, arg.AssociationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptAssociation{}
	for rows.Next() {
		var i TranscriptAssociation
		if err := rows.Scan(
			&i.OwnerID,
			&i.AssociationID,
			&i.TranscriptID,
			&i.ObservedCommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashes = `-- name: ListTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashes :many
SELECT owner_id, association_id, transcript_id, observed_commit_sha, created_at FROM transcript_associations
WHERE owner_id = $1
  AND transcript_id = $2
  AND observed_commit_sha = ANY($3::text[])
`

type ListTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashesParams struct {
	OwnerID              pgtype.UUID `db:"owner_id" json:"owner_id"`
	TranscriptID         pgtype.UUID `db:"transcript_id" json:"transcript_id"`
	ObservedCommitHashes []string    `db:"observed_commit_hashes" json:"observed_commit_hashes"`
}

func (q *Queries) ListTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashes(ctx context.Context, arg ListTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashesParams) ([]TranscriptAssociation, error) {
	rows, err := q.db.Query(ctx, listTranscriptAssociationsByOwnerTranscriptAndObservedCommitHashes, arg.OwnerID, arg.TranscriptID, arg.ObservedCommitHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptAssociation{}
	for rows.Next() {
		var i TranscriptAssociation
		if err := rows.Scan(
			&i.OwnerID,
			&i.AssociationID,
			&i.TranscriptID,
			&i.ObservedCommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranscriptAssociationsByTranscript = `-- name: ListTranscriptAssociationsByTranscript :many
SELECT owner_id, association_id, transcript_id, observed_commit_sha, created_at
FROM transcript_associations
WHERE transcript_id = $1
ORDER BY association_id, observed_commit_sha
`

func (q *Queries) ListTranscriptAssociationsByTranscript(ctx context.Context, transcriptID pgtype.UUID) ([]TranscriptAssociation, error) {
	rows, err := q.db.Query(ctx, listTranscriptAssociationsByTranscript, transcriptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TranscriptAssociation{}
	for rows.Next() {
		var i TranscriptAssociation
		if err := rows.Scan(
			&i.OwnerID,
			&i.AssociationID,
			&i.TranscriptID,
			&i.ObservedCommitSha,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
