// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_orgs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteStaleUserOrgs = `-- name: DeleteStaleUserOrgs :exec
DELETE FROM user_github_orgs
WHERE user_id = $1 AND fetched_at < $2
`

type DeleteStaleUserOrgsParams struct {
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	FetchedAt pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

func (q *Queries) DeleteStaleUserOrgs(ctx context.Context, arg DeleteStaleUserOrgsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleUserOrgs, arg.UserID, arg.FetchedAt)
	return err
}

const getOrgStats = `-- name: GetOrgStats :one
SELECT
    ugo.org_login,
    MAX(ugo.avatar_url) AS avatar_url,
    COUNT(DISTINCT ugo.user_id)::int AS member_count,
    COUNT(DISTINCT t.id)::int AS transcript_count
FROM user_github_orgs ugo
LEFT JOIN transcripts t
    ON t.owner_id = ugo.user_id AND t.visibility = 'public'
WHERE ugo.visible = true
  AND lower(ugo.org_login) = lower($1)
GROUP BY ugo.org_login
`

type GetOrgStatsRow struct {
	OrgLogin        string      `db:"org_login" json:"org_login"`
	AvatarUrl       interface{} `db:"avatar_url" json:"avatar_url"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) GetOrgStats(ctx context.Context, lower string) (GetOrgStatsRow, error) {
	row := q.db.QueryRow(ctx, getOrgStats, lower)
	var i GetOrgStatsRow
	err := row.Scan(
		&i.OrgLogin,
		&i.AvatarUrl,
		&i.MemberCount,
		&i.TranscriptCount,
	)
	return i, err
}

const getUserVisibleOrgsByUsername = `-- name: GetUserVisibleOrgsByUsername :many
SELECT ugo.org_login, ugo.avatar_url
FROM user_github_orgs ugo
JOIN users u ON ugo.user_id = u.id
WHERE lower(u.github_username) = lower($1) AND ugo.visible = true
ORDER BY ugo.org_login
`

type GetUserVisibleOrgsByUsernameRow struct {
	OrgLogin  string      `db:"org_login" json:"org_login"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) GetUserVisibleOrgsByUsername(ctx context.Context, lower string) ([]GetUserVisibleOrgsByUsernameRow, error) {
	rows, err := q.db.Query(ctx, getUserVisibleOrgsByUsername, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserVisibleOrgsByUsernameRow{}
	for rows.Next() {
		var i GetUserVisibleOrgsByUsernameRow
		if err := rows.Scan(&i.OrgLogin, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasUserVisibleOrg = `-- name: HasUserVisibleOrg :one
SELECT EXISTS (
    SELECT 1 FROM user_github_orgs
    WHERE user_id = $1
      AND lower(org_login) = lower($2)
      AND visible = true
) AS has_org
`

type HasUserVisibleOrgParams struct {
	UserID pgtype.UUID `db:"user_id" json:"user_id"`
	Lower  string      `db:"lower" json:"lower"`
}

// Returns true if the user has the given org_login marked visible=true.
// Used to validate "linked_github_org" claims and the verified_only org-specific gate.
func (q *Queries) HasUserVisibleOrg(ctx context.Context, arg HasUserVisibleOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserVisibleOrg, arg.UserID, arg.Lower)
	var has_org bool
	err := row.Scan(&has_org)
	return has_org, err
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT
    u.id,
    u.github_username,
    u.display_name,
    u.avatar_url,
    COUNT(DISTINCT t.id)::int AS transcript_count
FROM user_github_orgs ugo
JOIN users u ON ugo.user_id = u.id
LEFT JOIN transcripts t
    ON t.owner_id = u.id AND t.visibility = 'public'
WHERE ugo.visible = true
  AND lower(ugo.org_login) = lower($1)
GROUP BY u.id, u.github_username, u.display_name, u.avatar_url
ORDER BY transcript_count DESC, u.github_username
`

type ListOrgMembersRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	GithubUsername  string      `db:"github_username" json:"github_username"`
	DisplayName     pgtype.Text `db:"display_name" json:"display_name"`
	AvatarUrl       pgtype.Text `db:"avatar_url" json:"avatar_url"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) ListOrgMembers(ctx context.Context, lower string) ([]ListOrgMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrgMembersRow{}
	for rows.Next() {
		var i ListOrgMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAllOrgs = `-- name: ListUserAllOrgs :many
SELECT org_login, org_id, avatar_url, visible, fetched_at
FROM user_github_orgs
WHERE user_id = $1
ORDER BY org_login
`

type ListUserAllOrgsRow struct {
	OrgLogin  string             `db:"org_login" json:"org_login"`
	OrgID     int64              `db:"org_id" json:"org_id"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Visible   bool               `db:"visible" json:"visible"`
	FetchedAt pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

func (q *Queries) ListUserAllOrgs(ctx context.Context, userID pgtype.UUID) ([]ListUserAllOrgsRow, error) {
	rows, err := q.db.Query(ctx, listUserAllOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAllOrgsRow{}
	for rows.Next() {
		var i ListUserAllOrgsRow
		if err := rows.Scan(
			&i.OrgLogin,
			&i.OrgID,
			&i.AvatarUrl,
			&i.Visible,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserVisibleOrgs = `-- name: ListUserVisibleOrgs :many
SELECT org_login, org_id, avatar_url, visible, fetched_at
FROM user_github_orgs
WHERE user_id = $1 AND visible = true
ORDER BY org_login
`

type ListUserVisibleOrgsRow struct {
	OrgLogin  string             `db:"org_login" json:"org_login"`
	OrgID     int64              `db:"org_id" json:"org_id"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatar_url"`
	Visible   bool               `db:"visible" json:"visible"`
	FetchedAt pgtype.Timestamptz `db:"fetched_at" json:"fetched_at"`
}

func (q *Queries) ListUserVisibleOrgs(ctx context.Context, userID pgtype.UUID) ([]ListUserVisibleOrgsRow, error) {
	rows, err := q.db.Query(ctx, listUserVisibleOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserVisibleOrgsRow{}
	for rows.Next() {
		var i ListUserVisibleOrgsRow
		if err := rows.Scan(
			&i.OrgLogin,
			&i.OrgID,
			&i.AvatarUrl,
			&i.Visible,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleOrgsByUserIDs = `-- name: ListVisibleOrgsByUserIDs :many
SELECT ugo.user_id, ugo.org_login, ugo.avatar_url
FROM user_github_orgs ugo
WHERE ugo.user_id = ANY($1::uuid[]) AND ugo.visible = true
ORDER BY ugo.org_login
`

type ListVisibleOrgsByUserIDsRow struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	OrgLogin  string      `db:"org_login" json:"org_login"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) ListVisibleOrgsByUserIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListVisibleOrgsByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleOrgsByUserIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleOrgsByUserIDsRow{}
	for rows.Next() {
		var i ListVisibleOrgsByUserIDsRow
		if err := rows.Scan(&i.UserID, &i.OrgLogin, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchOrgs = `-- name: SearchOrgs :many
SELECT
    ugo.org_login,
    MAX(ugo.avatar_url) AS avatar_url,
    COUNT(DISTINCT ugo.user_id)::int AS member_count,
    COUNT(DISTINCT t.id)::int AS transcript_count
FROM user_github_orgs ugo
LEFT JOIN transcripts t
    ON t.owner_id = ugo.user_id AND t.visibility = 'public'
WHERE ugo.visible = true
  AND ugo.org_login ILIKE '%' || $1 || '%'
GROUP BY ugo.org_login
ORDER BY member_count DESC, transcript_count DESC
LIMIT $2
`

type SearchOrgsParams struct {
	Column1 pgtype.Text `db:"column_1" json:"column_1"`
	Limit   int32       `db:"limit" json:"limit"`
}

type SearchOrgsRow struct {
	OrgLogin        string      `db:"org_login" json:"org_login"`
	AvatarUrl       interface{} `db:"avatar_url" json:"avatar_url"`
	MemberCount     int32       `db:"member_count" json:"member_count"`
	TranscriptCount int32       `db:"transcript_count" json:"transcript_count"`
}

func (q *Queries) SearchOrgs(ctx context.Context, arg SearchOrgsParams) ([]SearchOrgsRow, error) {
	rows, err := q.db.Query(ctx, searchOrgs, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchOrgsRow{}
	for rows.Next() {
		var i SearchOrgsRow
		if err := rows.Scan(
			&i.OrgLogin,
			&i.AvatarUrl,
			&i.MemberCount,
			&i.TranscriptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrgVisibility = `-- name: SetOrgVisibility :exec
UPDATE user_github_orgs
SET visible = $3
WHERE user_id = $1 AND org_login = $2
`

type SetOrgVisibilityParams struct {
	UserID   pgtype.UUID `db:"user_id" json:"user_id"`
	OrgLogin string      `db:"org_login" json:"org_login"`
	Visible  bool        `db:"visible" json:"visible"`
}

func (q *Queries) SetOrgVisibility(ctx context.Context, arg SetOrgVisibilityParams) error {
	_, err := q.db.Exec(ctx, setOrgVisibility, arg.UserID, arg.OrgLogin, arg.Visible)
	return err
}

const upsertUserGitHubOrg = `-- name: UpsertUserGitHubOrg :exec
INSERT INTO user_github_orgs (user_id, org_login, org_id, avatar_url, fetched_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, org_login) DO UPDATE
SET org_id = EXCLUDED.org_id,
    avatar_url = EXCLUDED.avatar_url,
    fetched_at = now()
`

type UpsertUserGitHubOrgParams struct {
	UserID    pgtype.UUID `db:"user_id" json:"user_id"`
	OrgLogin  string      `db:"org_login" json:"org_login"`
	OrgID     int64       `db:"org_id" json:"org_id"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

func (q *Queries) UpsertUserGitHubOrg(ctx context.Context, arg UpsertUserGitHubOrgParams) error {
	_, err := q.db.Exec(ctx, upsertUserGitHubOrg,
		arg.UserID,
		arg.OrgLogin,
		arg.OrgID,
		arg.AvatarUrl,
	)
	return err
}
