// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests FROM users WHERE id = $1
`

// ⚠️ DO-NOT-TOUCH (TRAP — NOT the harness wire key): users.provider here is the
// OAuth AUTH IDENTITY (github/gitlab/...), unrelated to the transcript harness.
// It must NEVER be flipped to `harness` during the push-wire provider→harness
// changeover. (users.sql.go is sqlc-GENERATED from this file — change neither.)
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const getUserByProviderIdentity = `-- name: GetUserByProviderIdentity :one
SELECT id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests FROM users WHERE provider = $1 AND provider_user_id = $2
`

type GetUserByProviderIdentityParams struct {
	Provider       string `db:"provider" json:"provider"`
	ProviderUserID string `db:"provider_user_id" json:"provider_user_id"`
}

// Resolves a signed-in identity to a user by the provider that authenticated
// them, in the exact text form sign-in stored: GitHub OAuth writes
// provider_user_id = github_id::text, so a webhook's numeric sender id is
// compared as text and never by login (a login can be renamed and re-used).
// A caller with no row — never signed in, or signed in through another provider
// — is pgx.ErrNoRows, which the matcher reports as unresolved.
func (q *Queries) GetUserByProviderIdentity(ctx context.Context, arg GetUserByProviderIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderIdentity, arg.Provider, arg.ProviderUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests FROM users WHERE lower(github_username) = lower($1)
`

// Canonical handle lookup. github_username is globally unique (case-insensitive),
// so this resolves to exactly one user.
func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests FROM users WHERE id = ANY($1::uuid[])
`

// Several users in one statement, for list surfaces that would otherwise read
// GetUserByID once per row.
func (q *Queries) ListUsersByIDs(ctx context.Context, ids []pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.GithubUsername,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDiscoverable,
			&i.Provider,
			&i.ProviderUserID,
			&i.UsernameChosen,
			&i.ProviderUsername,
			&i.PreviewBeforeAttach,
			&i.AutoAttachPullRequests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUsername = `-- name: SetUsername :one
UPDATE users SET
    github_username = $2,
    username_chosen = true,
    updated_at = now()
WHERE id = $1
RETURNING id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests
`

type SetUsernameParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	GithubUsername string      `db:"github_username" json:"github_username"`
}

// Sets the user's canonical handle and marks it explicitly chosen. Relies on the
// case-insensitive unique index to reject collisions (caller maps 23505 -> 409).
func (q *Queries) SetUsername(ctx context.Context, arg SetUsernameParams) (User, error) {
	row := q.db.QueryRow(ctx, setUsername, arg.ID, arg.GithubUsername)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const updateUserAttachSettings = `-- name: UpdateUserAttachSettings :one
UPDATE users
SET preview_before_attach     = COALESCE($1, preview_before_attach),
    auto_attach_pull_requests = COALESCE($2, auto_attach_pull_requests),
    updated_at                = now()
WHERE id = $3
RETURNING id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests
`

type UpdateUserAttachSettingsParams struct {
	PreviewBeforeAttach    pgtype.Bool `db:"preview_before_attach" json:"preview_before_attach"`
	AutoAttachPullRequests pgtype.Bool `db:"auto_attach_pull_requests" json:"auto_attach_pull_requests"`
	ID                     pgtype.UUID `db:"id" json:"id"`
}

// Sets the attach choices one settings PATCH carries: whether this user's own
// pull request attachments stop at a preview the user confirms, and whether
// their transcripts are linked automatically when a pull request opens in a
// repository one of their collectives links. A NULL leaves that choice as it
// is, so a PATCH that carries one field changes that one only, in one
// statement.
func (q *Queries) UpdateUserAttachSettings(ctx context.Context, arg UpdateUserAttachSettingsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserAttachSettings, arg.PreviewBeforeAttach, arg.AutoAttachPullRequests, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const updateUserDiscoverable = `-- name: UpdateUserDiscoverable :one
UPDATE users SET
    is_discoverable = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests
`

type UpdateUserDiscoverableParams struct {
	ID             pgtype.UUID `db:"id" json:"id"`
	IsDiscoverable bool        `db:"is_discoverable" json:"is_discoverable"`
}

func (q *Queries) UpdateUserDiscoverable(ctx context.Context, arg UpdateUserDiscoverableParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserDiscoverable, arg.ID, arg.IsDiscoverable)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (github_id, github_username, provider_username, display_name, avatar_url, provider, provider_user_id, username_chosen)
VALUES ($1, $2, $3, $4, $5, 'github', $1::bigint::text, false)
ON CONFLICT (github_id) DO UPDATE SET
    provider_username = EXCLUDED.provider_username,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests
`

type UpsertUserParams struct {
	GithubID         int64       `db:"github_id" json:"github_id"`
	GithubUsername   string      `db:"github_username" json:"github_username"`
	ProviderUsername pgtype.Text `db:"provider_username" json:"provider_username"`
	DisplayName      pgtype.Text `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text `db:"avatar_url" json:"avatar_url"`
}

// github_username here is a freshly-generated unique candidate handle used only
// on INSERT; on a returning user (conflict) we preserve their chosen handle and
// only refresh the raw provider handle / profile fields.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubID,
		arg.GithubUsername,
		arg.ProviderUsername,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}

const upsertUserByProvider = `-- name: UpsertUserByProvider :one
INSERT INTO users (github_id, github_username, provider_username, display_name, avatar_url, provider, provider_user_id, username_chosen)
VALUES ($1, $2, $3, $4, $5, $6, $7, false)
ON CONFLICT (provider, provider_user_id) DO UPDATE SET
    provider_username = EXCLUDED.provider_username,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = now()
RETURNING id, github_id, github_username, display_name, avatar_url, created_at, updated_at, is_discoverable, provider, provider_user_id, username_chosen, provider_username, preview_before_attach, auto_attach_pull_requests
`

type UpsertUserByProviderParams struct {
	GithubID         int64       `db:"github_id" json:"github_id"`
	GithubUsername   string      `db:"github_username" json:"github_username"`
	ProviderUsername pgtype.Text `db:"provider_username" json:"provider_username"`
	DisplayName      pgtype.Text `db:"display_name" json:"display_name"`
	AvatarUrl        pgtype.Text `db:"avatar_url" json:"avatar_url"`
	Provider         string      `db:"provider" json:"provider"`
	ProviderUserID   string      `db:"provider_user_id" json:"provider_user_id"`
}

// Upsert a user identified by (provider, provider_user_id). github_id is a
// synthesized stable BIGINT (caller computes from sha256 of the external id);
// it is not a real GitHub ID for non-github providers. github_username is the
// canonical, user-chosen handle: on INSERT it's a generated unique candidate,
// and on a returning user (conflict) it is preserved — only provider_username
// and profile fields are refreshed.
func (q *Queries) UpsertUserByProvider(ctx context.Context, arg UpsertUserByProviderParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByProvider,
		arg.GithubID,
		arg.GithubUsername,
		arg.ProviderUsername,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderUserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubUsername,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDiscoverable,
		&i.Provider,
		&i.ProviderUserID,
		&i.UsernameChosen,
		&i.ProviderUsername,
		&i.PreviewBeforeAttach,
		&i.AutoAttachPullRequests,
	)
	return i, err
}
